{
  "hash": "aa0a1c369ae69bc200323bcc227e20e6",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: html\npractical: Practical_6_Further_Statistics\ndoc-id: \"0605\"\nauthor: \"Katy Brown\"\n---\n\n\n\n# Part 5: Generalised Linear Models - Poisson  {#sec-p5_glms_pois}\n\n::: {.callout-note .partmenu #parts-0605}\n## Sections\n- @sec-poisson_glms\n- @sec-log_link\n- @sec-fitting_pois_glms\n- @sec-prediction_pois_glm\n- @sec-assumptions_glms\n- @sec-summary_0605\n:::\n\n:::{.callout-tip .objectives}\n#### Learning objectives\n\n\nBy the end of this part of the practical you will be able to:\n\n* Explain when a Poisson generalised linear model (GLM) is appropriate.\n* Fit and interpret a Poisson GLM in R.\n* Explain the role of the log link function in a Poisson GLM.\n* Use a fitted Poisson GLM to predict expected counts.\n* Assess whether count data are overdispersed relative to a fitted Poisson model.\n\n:::\n\nIn this part of the practical, you will need one Quarto document:\n\n* `glms.qmd` for applying GLMs to pollinator data.\n\n## Poisson GLMs {#sec-poisson_glms .core}\n\n[**Core**]{.core-text}\n\n[↑ top](#)\n\nA binomial GLM is appropriate when the response variable represents one of two possible outcomes. A Poisson GLM can be used to model count data when a Poisson distribution (@sec-comparing_sim_real) is appropriate. In a Poisson GLM, we model how $\\lambda$, the expected count, changes with our explanatory variables.\n\nAs with the binomial GLM, the model coefficients are estimated using maximum likelihood. The likelihood is now calculated using the Poisson rather than the binomial distribution, but the principle is the same: R finds the combination of parameter values that makes the observed data most likely.\n\nNote: Although Poisson GLMs are used for count data, not every count response is adequately described by a Poisson model. We will discuss this below in @sec-assumptions_glms.\n\n## Log-link function {#sec-log_link .core}\n\n[**Core**]{.core-text}\n\n[↑ top](#)\n\nBy default, a Poisson GLM uses a log link function, which models the logarithm of the expected count, $\\lambda$, as a linear function of the explanatory variables, with $\\beta_0$ as the intercept and $\\beta_1$ as the coefficient for the explanatory variable.\n\n$$\n\\log(\\lambda) = \\beta_0 + \\beta_1 x\n$$\nThe inverse of this is:\n\n$$\n\\lambda = e^{\\beta_0 + \\beta_1 x}\n$$\nThis transformation ensures that the expected count is always positive, even though the linear predictor can take any value.\n\n## Fitting Poisson GLMs in R {#sec-fitting_pois_glms .core}\n\n[**Core**]{.core-text}\n\n[↑ top](#)\n\nLet's use a Poisson GLM to test the following hypotheses:\n\n* **Null hypothesis**: There is no association between the number of non-Apidae insect species and the expected number of Apidae species found at a site.\n\n* **Alternative hypothesis**: There is an association between the number of non-Apidae insect species and the expected number of Apidae species found at a site.\n\nFirst we need to read our data, and add a column containing the number of non-Apidae species at each site.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsite_metadata <- read_csv(\"data/site_metadata.csv\")\nsite_metadata <- site_metadata |>\n  mutate(n_non_apidae = n_unique - n_apidae)\n```\n:::\n\n\nNow we are ready to fit the GLM. This is very similar to fitting a binomial GLM, except we use the argument `family = poisson` for the Poisson model.\n\n::: {.callout-exercise #ex-fit_pois_glm .core}\n\n### Fitting a Poisson GLM\n\n[**Core**]{.core-text}\n\nIn your `glms.qmd` Quarto file, use a GLM to test whether the number of Apidae species at a site is associated with the number of non-Apidae insect species.\n\nUse:\n\n- `n_apidae` as the response variable\n- `n_non_apidae` as the explanatory variable\n- `family = poisson` to fit a Poisson GLM\n\nStore your model in a variable, `glm_apidae`, and examine it using `summary()`.\n\n::: {.callout-answer collapse=\"true\" #ex-fit_pois_glm_ans}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm_apidae <- glm(\n  n_apidae ~ n_non_apidae,\n  family = poisson,\n  data = site_metadata\n)\n\nsummary(glm_apidae)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = n_apidae ~ n_non_apidae, family = poisson, data = site_metadata)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  2.100522   0.080032  26.246  < 2e-16 ***\nn_non_apidae 0.020057   0.002673   7.503 6.23e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 180.30  on 75  degrees of freedom\nResidual deviance: 123.59  on 74  degrees of freedom\nAIC: 455.22\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\nThe estimated coefficient for the number of non-Apidae species is 0.02. This coefficient is positive, indicating that sites with more non-Apidae insect species are expected to also contain more Apidae species.\n\nThe Poisson GLM uses a **log link**, so the coefficients represent changes in the log of the expected count. We can exponentiate the coefficient to make it easier to interpret:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint (exp(coef(glm_apidae)[\"n_non_apidae\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn_non_apidae \n    1.020259 \n```\n\n\n:::\n:::\n\n\nFor each additional non-Apidae species, the expected number of Apidae species is therefore multiplied by 1.02, corresponding to an increase of approximately 2%.\n\nThe p-value associated with this coefficient is 6.23e-14. We therefore reject the null hypothesis and conclude that there is evidence of an association between the number of non-Apidae insect species and the expected number of Apidae species found at a site.\n\nLet's plot the data and our model, as usual. `geom_smooth()` transforms the fitted values back from the log scale to the response scale, so the fitted line shows the expected number of Apidae species.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(site_metadata,\n       aes(x = n_non_apidae, y = n_apidae)) +\n  geom_point() +\n  geom_smooth(\n    method = \"glm\",\n    method.args = list(family = poisson)\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](06-05_glms_pois_files/figure-html/plot_glm_apidae-1.png){width=672}\n:::\n:::\n\n\n## Prediction {#sec-prediction_pois_glm .core}\n\n[**Core**]{.core-text}\n\n[↑ top](#)\n\nWe can make predictions with our Poisson GLMs using the `predict()` function, just like for our other models.\n\n::: {.callout-exercise #ex-prediction_pois_glm .core}\n\n### Making predictions\n\n[**Core**]{.core-text}\n\nUse `predict()` to estimate the expected number of Apidae species at a site with **8 non-Apidae species**.\n\nRemember to use `type = \"response\"` to return the prediction as an expected count rather than on the log scale.\n\n::: {.callout-answer collapse=\"true\" #ex-prediction_pois_glm_ans}\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred <- predict(\n  glm_apidae,\n  newdata = tibble(n_non_apidae = 8),\n  type = \"response\"\n)\nprint (pred)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n9.592428 \n```\n\n\n:::\n:::\n\nThe model predicts an expected count of 9.59 Apidae species at a site with 8 non-Apidae species.\n\n:::\n:::\n\n## Assumptions of Poisson GLMs {#sec-assumptions_glms .core}\n\n[**Core**]{.core-text}\n\n[↑ top](#)\n\nAs well as the assumptions we discussed in @sec-assumptions_binom, for Poisson GLMs, we additionally assume that:\n\n* The response is compatible with a Poisson distribution (see @sec-p3_distributions).\n* The variance of the response, conditional on the explanatory variables, is equal to its mean.\n\nThe relationship between the variance of the response and the mean can be calculated from our model.\n\nTwo statistics are commonly used:\n\n### Pearson dispersion {#sec-pearson .core}\n\n$$\n\\hat{\\phi}_{P} =\n\\frac{\\sum_{i=1}^{n} r_{P,i}^{2}}\n{n-p}\n$$\n\nwhere $r_{P,i}$ is the Pearson residual for observation $i$, $n$ is the number of observations and $p$ is the number of model parameters.\n\nWe can extract the residuals directly from the fitted GLM using the `residuals()` function with the argument `type = \"pearson\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresid <- residuals(glm_apidae, type = \"pearson\")\n```\n:::\n\n\nThe sum of the squares of these values is ${\\sum_{i=1}^{n} r_{P,i}^{2}}$.\n\n$(n - p)$ is the residual degrees of freedom, which we can also access from the model, as e.g. `glm_apidae$df.residual`.\n\n::: {.callout-exercise #ex_pearson_dispersion .core}\n\n### Calculating Pearson dispersion \n\n[**Core**]{.core-text}\n\nIn your `glms.qmd` Quarto file, write a function named `pearson_dispersion` to calculate the Pearson dispersion of a GLM, where the input is the fitted GLM and the output is the Pearson dispersion. Apply it to your fitted Apidae GLM.\n\n::: {.callout-answer #ex_pearson_dispersion_ans}\n\n::: {.cell}\n\n```{.r .cell-code}\npearson_dispersion <- function(fitted_glm){\n  resid <- residuals(fitted_glm, type = \"pearson\")\n  ss <- sum(resid ^ 2)\n  df <- fitted_glm$df.residual\n  disp <- ss / df\n  return (disp)\n}\np_disp_apidae <- pearson_dispersion(glm_apidae)\nprint (p_disp_apidae)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.347039\n```\n\n\n:::\n:::\n\n:::\n:::\n\n### Deviance dispersion {#sec-deviance .core}\n\n$$\n\\hat{\\phi}_{D} =\n\\frac{D}\n{n-p}\n$$\n\nwhere $D$ is the residual **deviance**, $n$ is the number of observations and $p$ is the number of model parameters.\n\n![Deviance](images/bob.png){#fig-bob width=\"25%\"}\n\nThe residual deviance is a measure of how much mismatch remains between the observed data and the fitted GLM.\n\nIt's based on likelihood, comparing the fitted model with a hypothetical saturated model — a model with enough parameters to fit the observations perfectly. We will come back to this later when we compare models.\n\nWe can access the residual deviance using e.g. `glm_apidae$deviance`.\n\nAs we know, $n - p$ is the residual degrees of freedom.\n\n::: {.callout-exercise #ex_dev_dispersion .core}\n\n### Calculating deviance dispersion\n\n[**Core**]{.core-text}\n\nIn your `glms.qmd` Quarto file, write a function named `deviance_dispersion` to calculate the deviance dispersion of a GLM, where the input is the fitted GLM and the output is the deviance dispersion. Apply it to your fitted Apidae GLM.\n\n::: {.callout-answer #ex_dev_dispersion_ans}\n\n::: {.cell}\n\n```{.r .cell-code}\ndeviance_dispersion <- function(fitted_glm){\n  devi <- fitted_glm$deviance\n  df <- fitted_glm$df.residual\n  disp <- devi / df\n  return (disp)\n}\nd_disp_apidae <- deviance_dispersion(glm_apidae)\nprint (d_disp_apidae)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.67018\n```\n\n\n:::\n:::\n\n:::\n:::\n\nIn general, we want both of these statistics to be close to 1. Values substantially greater than 1 can indicate **overdispersion** - the variance in the data is greater than the model expects. Values substantially less than 1 can indicate **underdispersion** - the variance in the data is less than the model expects.\n\nLet's fit another GLM to demonstrate how this can impact our model.\n\n::: {.callout-exercise #ex-overdispersion .core}\n\n### Fitting a Poisson GLM and checking dispersion\n\n[**Core**]{.core-text}\n\nIn your `glms.qmd` Quarto file, using your site metadata data frame, fit a Poisson GLM to address the following hypotheses based on our pollinator data:\n\n* **Null hypothesis**: There is no association between the number of unique flower species (column `n_unique_flowers`) at a site and the number of unique insect species (column `n_unique`).\n* **Alternative hypothesis**: There is an association between the number of unique flower species at a site and the number of unique insect species.\n\nUsing your functions from the previous exercises, calculate the Pearson dispersion and deviance dispersion of the model. Do you think the data is overdispersed?\n\n::: {.callout-answer collapse=\"true\" #ex-overdispersion_ans}\n\n\n[Fit a Poisson GLM to address the following hypotheses.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm_unique_spp <- glm(n_unique ~ n_unique_flowers, data = site_metadata, family = poisson)\nprint(summary(glm_unique_spp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = n_unique ~ n_unique_flowers, family = poisson, \n    data = site_metadata)\n\nCoefficients:\n                 Estimate Std. Error z value Pr(>|z|)    \n(Intercept)      3.295700   0.042666  77.244   <2e-16 ***\nn_unique_flowers 0.014282   0.001453   9.827   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 527.21  on 75  degrees of freedom\nResidual deviance: 432.37  on 74  degrees of freedom\nAIC: 845.53\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n[Calculate the Pearson dispersion.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_disp_unique_spp <- pearson_dispersion(glm_unique_spp)\nprint(p_disp_unique_spp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.385223\n```\n\n\n:::\n:::\n\n[Calculate the deviance dispersion.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd_disp_unique_spp <- deviance_dispersion(glm_unique_spp)\nprint(d_disp_unique_spp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.842826\n```\n\n\n:::\n:::\n\n:::\n:::\n\nBoth dispersion statistics are greater than 1, indicating that there is more variation in the observed counts than expected under the fitted Poisson model. A Poisson model may therefore not be appropriate for these data.\n\n### Visualising overdispersion {#sec-visualising_dispersion .fold .extension}\n\n[**Extension**]{.extension-text}\n\n[↑ top](#)\n\nOur dispersion statistics suggest that the observed insect counts vary more than we would expect under our fitted Poisson model. We can use simulation to visualise what this means.\n\nThe fitted values from our model are the expected counts ($\\lambda$) for each site. If the Poisson model is appropriate, we can use these values to simulate the sort of counts we would expect to observe under the fitted model.\n\n::: {.callout-exercise #ex-visualise_overdispersion .extension}\n\n### Visualising overdispersion\n\n[**Extension**]{.extension-text}\n\nIn your `glms.qmd` Quarto file:\n\n* Use `fitted()` to extract the expected insect count for each site from your fitted Poisson GLM.\n* Use `rpois()` to simulate one new insect count for each site (so set `n` to be the number of sites), using the fitted values as the values of $\\lambda$.\n* Create a data frame containing:\n    * the fitted count for each site\n    * the observed insect count\n    * the simulated insect count\n* Calculate the difference between the fitted count and the observed count and add this as a column, `observed_difference`.\n* Calculate the difference between the fitted count and the simulated count and add this as a column, `simulated_difference`.\n* Plot these differences as a box plot.\n\nWhat does this tell you about the variation in the observed data compared with the variation expected under the fitted Poisson model?\n\n::: {.callout-answer collapse=\"true\" #ex-visualise_overdispersion_ans}\n\n[Use `fitted()` to extract the expected insect count for each site from your fitted Poisson GLM.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract expected counts from the fitted model\nfitted_counts <- fitted(glm_unique_spp)\n```\n:::\n\n\n[Use `rpois()` to simulate one new insect count for each site, using the fitted values as the values of $\\lambda$.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimulated_counts <- rpois(\n  n = length(fitted_counts),\n  lambda = fitted_counts\n)\n```\n:::\n\n\n[Create a data frame containing: the fitted count for each site, the observed insect count, the simulated insect count]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndispersion_df <- tibble(\n  fitted = fitted_counts,\n  observed = site_metadata$n_unique,\n  simulated = simulated_counts\n)\n```\n:::\n\n\n[Calculate the difference between the fitted count and the observed count and add this as a column, `observed_difference`.]{.blue-text}\n\n[Calculate the difference between the fitted count and the simulated count and add this as a column, `simulated_difference`.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndispersion_df <-  dispersion_df |>\n  mutate(\n    observed_difference = observed - fitted,\n    simulated_difference = simulated - fitted\n  )\n```\n:::\n\n\n[Plot these differences as a box plot.]{.blue-text}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert to long format for plotting\ndispersion_long <- dispersion_df |>\n  select(observed_difference, simulated_difference) |>\n  pivot_longer(\n    cols = everything(),\n    names_to = \"data\",\n    values_to = \"difference\"\n  )\n\n# Plot\nggplot(dispersion_long, aes(x = data, y = difference, fill = data)) +\n  geom_boxplot() +\n  geom_hline(yintercept = 0) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06-05_glms_pois_files/figure-html/visualise_overdispersion_ans5-1.png){width=672}\n:::\n:::\n\nClearly, our data are more dispersed than the model predicts.\n\n:::\n:::\n\n### Accounting for overdispersion {#sec-accounting_for_overdispersion .fold .extension}\n\nOne way to account for overdispersion is to use a **quasi-Poisson model**. A standard Poisson model assumes:\n\n$$\n\\operatorname{Var}(Y) = \\mu\n$$\n\nA quasi-Poisson model introduces an additional dispersion parameter, $\\phi$:\n\n$$\n\\operatorname{Var}(Y) = \\phi\\mu\n$$\n\nWhen $\\phi > 1$, this allows the variance to be greater than the mean.\n\n![Quasi-modo](images/quasi.png){#fig-bob width=\"25%\"}\n\n\nIn R, we can fit this model by replacing `family = poisson` with `family = quasipoisson`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm_unique_spp_quasi <- glm(\n  n_unique ~ n_unique_flowers,\n  family = quasipoisson,\n  data = site_metadata\n)\n\nsummary(glm_unique_spp_quasi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = n_unique ~ n_unique_flowers, family = quasipoisson, \n    data = site_metadata)\n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      3.295700   0.099012  33.286  < 2e-16 ***\nn_unique_flowers 0.014282   0.003373   4.235  6.5e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for quasipoisson family taken to be 5.38531)\n\n    Null deviance: 527.21  on 75  degrees of freedom\nResidual deviance: 432.37  on 74  degrees of freedom\nAIC: NA\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n::: {.callout-exercise #ex-quasipoisson .extension}\n\n### Examining quasi-Poisson output\n\n[**Extension**]{.extension-text}\n\nCompare the output from the Poisson and quasi-Poisson models.\n\n* What has happened to the coefficient estimates?\n* What has happened to their standard errors?\n* What has happened to the p-value for `n_unique_flowers`?\n* Has accounting for overdispersion changed your conclusion about the association between flower and insect species richness?\n\n::: {.callout-answer collapse=\"true\" #ex-quasipoisson_ans}\n\n* The coefficient estimates are identical, but their standard errors are larger in the quasi-Poisson model. The quasi-Poisson model accounts for the additional variation in the data, and therefore gives us less certainty about the estimated coefficients.\n* The p-value for `n_unique_flowers` has increased from <2 × 10^-16^ to 6.5 × 10^-5^, although there is still strong evidence of an association between flower and insect species richness.\n\nThis does not change our conclusion, but accounting for the overdispersion gives us a more appropriate estimate of the uncertainty around the coefficients.\n\n:::\n:::\n\n## Review {#sec-summary_0605}\n\n[↑ top](#)\n\n::: {.callout-note #note-summary_0605}\n\n### Summary\n\n* A **Poisson GLM** can be used to model count data when a Poisson distribution is appropriate.\n* A Poisson GLM models how the expected count, $\\lambda$, changes with one or more explanatory variables.\n* By default, a Poisson GLM uses a **log link function**, ensuring that predicted expected counts are always positive.\n* Poisson GLM coefficients represent changes in the log of the expected count. Exponentiating a coefficient gives the factor by which the expected count is multiplied for a one-unit increase in the explanatory variable.\n* We can use a fitted Poisson GLM to predict expected counts for new values of the explanatory variables.\n* A Poisson model assumes that the conditional variance of the response is equal to its conditional mean.\n* **Pearson dispersion** and **deviance dispersion** can be used to assess whether the variation in the data is consistent with that expected under a Poisson model.\n* Dispersion substantially greater than 1 indicates **overdispersion**, while dispersion substantially less than 1 indicates **underdispersion**.\n\n#### Programming\n\n* We can fit a Poisson GLM using `glm()` with `family = poisson`.\n* We can use `predict()` with `type = \"response\"` to obtain predicted expected counts on the response scale.\n* We can extract Pearson residuals from a fitted GLM using `residuals()` with `type = \"pearson\"`.\n* Components of a fitted model, such as its residual degrees of freedom and deviance, can be accessed using `$`.\n\n:::\n\nFor this part of the practical, the main file you have edited is:\n\n* `glms.qmd`\n\nThis is the file you should select when making your Git commit.\n\n\nRemember to save and commit your work before moving on to Part 6.\n\n::: {.callout-tip}\n## Commit your changes\nRemember to save your progress regularly by committing your changes with Git.\n\n1. Save your changes to the files above in RStudio with the `Save` button.\n2. Render any Quarto documents with the `Render` button.\n3. Open the `Git` tab in RStudio.\n4. Tick the files listed above, don't worry about any others.\n5. Click `Commit` and write a short message in the `Commit message` describing your changes, something like e.g. \"Practical 1 part 1\" is sufficient, then click `Commit`. Close the `Commit` popup.\n\n:::\n\t\n\n",
    "supporting": [
      "06-05_glms_pois_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}