---
title: "Plan and Learning Objectives"
format: html
practical: Practical_5_Bioinformatics
doc-id: "0500"
author: "Katy Brown"
---

```{r setup, include=FALSE}
library(tidyverse)
```

# Practical 5 - Bioinformatics

::: {.callout-tip .partmenu #parts-0500}

## Practical 5 - Bioinformatics

### @sec-p1_intro_bioconductor

#### Sections
- @sec-ervs
- @sec-aims
- @sec-bioconductor
- @sec-get_sequence
- @sec-summary_0501


#### Learning objectives
By the end of this part of the practical you will be able to:

* Describe the basic structure of a FASTA file.
* Use Bioconductor packages for biological sequence analysis.
* Read DNA sequences from a FASTA file into R.
* Examine the lengths of sequences in a `DNAStringSet`.
* Extract an individual sequence from a `DNAStringSet` using its identifier.


### @sec-p2_finding_orfs

#### Sections
- @sec-genes
- @sec-orfs
- @sec-add_names
- @sec-translate
- @sec-save
- @sec-summary_0502


#### Learning objectives
By the end of this part of the practical you will be able to:

* Identify open reading frames in a DNA/RNA sequence.
* Extract ORF sequences from DNA/RNA sequences.
* Translate DNA/RNA sequences into amino acid sequences.
* Save biological sequences in FASTA format.


### @sec-p3_blast

#### Sections
- @sec-run_blast
- @sec-blast_results
- @sec-process_blast
- @sec-join_orf_blast
- @sec-select_longest
- @sec-summary_0503


#### Learning objectives
By the end of this part of the practical you will be able to:

* Use BLASTp to find proteins related to a sequence of interest.
* Interpret the results of a BLAST search.
* Extract and organise information from BLAST results.
* Use BLAST results to identify likely retroviral genes and genera.


### @sec-p4_msa_phylogeny

#### Sections
- @sec-alignment
- @sec-phylogeny
- @sec-visualise_phylogeny
- @sec-summary_0504

#### Learning objectives
By the end of this part of the practical you will be able to:

* Construct multiple sequence alignments of related sequences.
* Build phylogenetic trees.
* Visualise phylogenetic trees.


### @sec-p5_share_results

#### Sections
- @sec-fork_ervs
- @sec-clone_ervs
- @sec-transfer_ervs
- @sec-push_ervs
- @sec-pull_request_ervs
- @sec-summary_0505

#### Learning objectives
By the end of this part of the practical you will have:

* Forked the MB1A_ERV_Submissions GitHub repository.
* Cloned your fork onto your computer using RStudio.
* Transferred your final results and analysis pipeline to the submission repository.
* Pushed your results to your GitHub fork.
* Created a Pull Request to contribute your results to the central MB1A_ERV_Submissions repositoryry

:::
