{
  "hash": "8f1f59bf7ee1e609b8e112679df8e484",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: html\npractical: Practical_4_Statistics\ndoc-id: \"0603\"\nauthor: \"Katy Brown\"\n---\n\n\n# Part 3: Can we break a t-test? {#sec-p3_break_t}\n\n::: {.callout-note .partmenu #parts-0603}\n## Sections\n- @sec-data_break_t\n- @sec-helper_functions\n- @sec-p_distributions\n- @sec-true_normal\n- @sec-breaking_assumptions\n- @sec-summary_0603\n:::\n\n:::{.callout-tip .objectives #objectives-0603}\n#### Learning objectives\n:::\n\nA standard two-sample t-test assumes that the populations being compared are normally distributed and that their residuals have equal variance, but the t-test is often described as robust to violations of these assumptions. What does this actually mean?\n\nLet's investigate two sets of hypotheses, in one we will simulate a true difference in means and in the other we will not.\n\n## Data {#sec-data_break_t}\n\n#### Scenario 1\n\n* **Alternative**: The mean running speed of cats through a course is associated with the colour of their fur.\n* **Null**: The mean running speed of cats through a course is not associated with the colour of their fur.\n\nPopulation values:\n\n* Orange cats: mean speed, **20km/h**\n* Black cats: mean speed, **20km/h**\n\n#### Scenario 2\n\n* **Alternative**: The mean running speed of dogs through a course differs depending on whether there is a biscuit at the end of the course.\n* **Null**: The mean running speed of dogs through a course does not differ depending on whether there is a biscuit at the end of the course.\n\nPopulation values:\n\n* Biscuit absent: mean speed, **20km/hr**\n* Biscuit present: mean speed, **24km/hr**\n\nFor the **cat** data, the **null hypothesis** is true, so the proportion of significant results estimates a **Type I** error rate.\n\nFor the **dog** data, the **alternative hypothesis** is true, so the proportion of non-significant results estimates a **Type II** error rate.\n\n## Helper functions {#sec-helper_functions}\n\nWe are going to perform the same steps lots of times, so we need a function.\n\n::: {.callout-exercise #ex-function_ttest}\nIn your `break_t.qmd` Quarto file:\n\n* Write a function named `compare_vectors` for which the input is two vectors of measurements. The function should:\n  * Create a data frame with two columns, \"group\" and \"measurement\", where each vector contributes one group. As our groups won't always be the same size, a good option is to create one data frame per group then combine them with `bind_rows()`.\n  * Create a summary data frame containing the mean and standard deviation of each group\n  * Perform an equal variance t-test comparing the measurements for the two groups.\n  * Fit a linear model to the measurements for the two groups.\n  * Put the residuals from the linear model into the long format data frame.\n  * Plot a histogram showing the distribution of the residuals in each group.\n  * Return a list containing:\n    * `df` - The data frame\n    * `summ_df` - The summary data frame\n    * `t_test` - The t-test result\n    * `linear_model` - The fitted linear model\n    * `distri` - the plotted distribution\n\n::: {.callout-answer collapse=\"true\" #ex_function_ttest_ans}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare_vectors <- function(vector1, vector2) {\n  # Create the data frame\n  v1_df <- tibble(group = \"group_1\",\n                  measurement = vector1)\n  v2_df <- tibble(group = \"group_2\",\n                  measurement = vector2)\n  comp_df <- bind_rows(v1_df, v2_df)\n\n  # Create a summary data frame\n  summ_df <- comp_df |>\n    group_by(group) |>\n    summarise(\n      group_mean = mean(measurement),\n      group_sd = sd(measurement)\n    )\n\n  # Do the t-test\n  t_test <- t.test(measurement ~ group,\n    data = comp_df,\n    var.equal = TRUE\n  )\n\n  # Fit the linear model\n  linear_model <- lm(measurement ~ group, data = comp_df)\n\n  # Put the residuals from the linear model into the\n  # data frame\n  comp_df <- comp_df |> mutate(\n    residuals = linear_model$residuals\n  )\n\n  # Plot a histogram showing the distribution of the\n  # residuals in each group.\n  distri <- ggplot(comp_df, aes(x = residuals)) +\n    geom_histogram(bins=15) +\n    facet_wrap(~group) +\n    theme_bw()\n\n  # Put the results into a list\n  results <- list(\n    df = comp_df,\n    summ_df = summ_df,\n    t_test = t_test,\n    linear_model = linear_model,\n    distri = distri\n  )\n  # Return the list\n  return(results)\n}\n```\n:::\n\n:::\n:::\n\nThis function will be useful for thoroughly examining a single dataset, however we also want to repeat our analysis on multiple simulated datasets and store only the t-test results.\n\nWe can use a shortened version of this function in this case.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare_vectors_short <- function(vector1, vector2) {\n  # Create the data frame\n  v1_df <- tibble(group = \"group_1\",\n                  measurement = vector1)\n  v2_df <- tibble(group = \"group_2\",\n                  measurement = vector2)\n  comp_df <- bind_rows(v1_df, v2_df)\n\n  # Do the t-test\n  t_test <- t.test(measurement ~ group, data = comp_df, var.equal = TRUE)\n\n  # Return the t-test p-value\n  return(t_test$p.value)\n}\n```\n:::\n\n\nWe also need an empty data frame in which to store our results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomparison_df <- tibble()\n```\n:::\n\n\n## Distributions of p-values {#sec-p_distributions}\n\nWhen we repeat a statistical test many times, we can examine the distribution of the p-values it produces.\n\nWhen the null hypothesis is true and the test is working correctly, p-values should be approximately uniformly distributed between 0 and 1. For example, around 5% should be less than or equal to 0.05, giving the expected 5% type I error rate.\n\nFor example, here is a very clean scenario of two fairly big, normally distributed groups with the same mean and variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nps <- c()\nfor (i in seq_len(10000)){\n  group_1 <- rnorm(100, mean = 10, sd = 5)\n  group_2 <- rnorm(100, mean = 10, sd = 5)\n\n  t_test <- t.test(group_1, group_2, var.equal = TRUE)\n  ps <- c(ps, t_test$p.value)\n}\np_df <- tibble(pval = ps)\n\nggplot(p_df, aes(x = pval)) +\n  geom_histogram(boundary = 0, binwidth = 0.05) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/uniform_p-1.png){width=672}\n:::\n:::\n\n\nWhen the alternative hypothesis is true, we expect more small p-values. The stronger the evidence the test is able to detect, the more strongly the distribution will be concentrated towards zero.\n\nFor example, here is a very clean scenario of two fairly big, normally distributed groups with a different mean and the same variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nps <- c()\nfor (i in seq_len(10000)){\n  group_1 <- rnorm(100, mean = 10, sd = 5)\n  group_2 <- rnorm(100, mean = 13, sd = 5)\n\n  t_test <- t.test(group_1, group_2, var.equal = TRUE)\n  ps <- c(ps, t_test$p.value)\n}\np_df <- tibble(pval = ps)\n\nggplot(p_df, aes(x = pval)) +\n  geom_histogram(boundary = 0, binwidth = 0.05) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/real_diff_p-1.png){width=672}\n:::\n:::\n\n\nTherefore, if we are running many tests we can use p-value distributions to investigate whether a statistical test is behaving as expected, rather than judging it from the result of a single test.\n\n## True normally distributed data {#sec-true_normal}\n\nFirst, let's take values from normal distributions with equal variance which meet the assumptions of our t-test and see how the t-test performs.\n\n::: {.callout-exercise #ex-break_t_1}\n\nIn your `break_t.qmd` Quarto file:\n\n1. Simulate **30** data points from each of these populations (orange cats, black cats, dogs with a biscuit, dogs without a biscuit), assuming they are normally distributed with a standard deviation of 5.\n\n2.  Pass the sets of data points for each scenario (one scenario at a time) to your `compare_vectors()` function, store the result as `results_cat` or `results_dog`.\n\n3. Based on the output of your function, for each scenario:\n    * Examine the summary table (e.g. `results_cat$summ_df`) to check the mean of each group is approximately as expected. \n    * Examine the distribution of the residuals (e.g. `results_cat$distri`). \n    * Plot and examine diagnostic plots for the linear model (e.g. `results_cat$linear_model`) in each scenario.\n    * Examine the t-test (e.g. `results_cat$t_test`) result. \n\n4. In a for loop, repeat the following 1000 times for each scenario:\n    * Simulate 30 data points from each of the populations with the same parameters you used above.\n    * Pass the data points to `compare_vectors_short()` to get the p-value of the t-test\n    * Store the p-value in a vector.\n\n5.  Plot histograms of the p-values for both sets of simulations. Use `geom_histogram()` as follows `geom_histogram(boundary = 0, binwidth = 0.05)` to divide into bins of width 0.05.\n\n6. Calculate the proportion of significant p-values (p <= 0.05) you have for the cat dataset - these are type I errors - and the proportion of insignificant p-values you have for the dog dataset (p > 0.05) - these are type II errors.\n\n7. Store the type I and type II error rates as a data frame as follows (if your type I error rate were saved as `type1err` and your type II error rate as `type2err`), then append this to the data frame `comparison_df` using the `bind_rows()` function.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndd <- tibble(\n  situation = \"normal\",\n  type_I = type1err,\n  type_II = type2err\n)\ncomparison_df <- bind_rows(comparison_df, dd)\n```\n:::\n\n\n\n:::{.callout-answer collapse=\"true\" #ex_break_t_1_ans}\n\n#### 1\n[Simulate 30 data points from each of these populations, assuming they are normally distributed with a standard deviation of 5.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncats_orange <- rnorm(30, mean = 20, sd = 5)\ncats_black <- rnorm(30, mean = 20, sd = 5)\n\ndogs_no_biscuit <- rnorm(30, mean = 20, sd = 5)\ndogs_biscuit <- rnorm(30, mean = 24, sd = 5)\n```\n:::\n\n\n#### 2\n\n[Pass the sets of data points for each scenario (one scenario at a time) to your `compare_vectors` function.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults_cat <- compare_vectors(cats_orange, cats_black)\n\nresults_dog <- compare_vectors(dogs_no_biscuit, dogs_biscuit)\n```\n:::\n\n\n#### 3\n\n[Look at the summary table to check the mean of each group is approximately as expected.]{.blue-text}\n\nCats:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_cat$summ_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  group   group_mean group_sd\n  <chr>        <dbl>    <dbl>\n1 group_1       19.3     4.79\n2 group_2       21.7     5.24\n```\n\n\n:::\n:::\n\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_dog$summ_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  group   group_mean group_sd\n  <chr>        <dbl>    <dbl>\n1 group_1       19.9     5.53\n2 group_2       26.2     4.05\n```\n\n\n:::\n:::\n\n\n[Examine the distribution of the residuals.]{.blue-text}\n\nCats:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_cat$distri)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans1.5-1.png){width=672}\n:::\n:::\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_dog$distri)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans1.6-1.png){width=672}\n:::\n:::\n\n\n[Plot and examine diagnostic plots for the linear model in each scenario, using the base R `plot` function on the linear model.]{.blue-text}\n\nCat:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(results_cat$linear_model)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans1.7-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans1.7-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans1.7-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans1.7-4.png){width=672}\n:::\n:::\n\nDog:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(results_dog$linear_model)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans1.8-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans1.8-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans1.8-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans1.8-4.png){width=672}\n:::\n:::\n\n\n\n[Examine the t-test result.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_cat$t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  measurement by group\nt = -1.8211, df = 58, p-value = 0.07376\nalternative hypothesis: true difference in means between group group_1 and group group_2 is not equal to 0\n95 percent confidence interval:\n -4.950221  0.233926\nsample estimates:\nmean in group group_1 mean in group group_2 \n             19.33890              21.69705 \n```\n\n\n:::\n:::\n\n\nIn most cases, the p-value here will be insignificant and we will not be able to reject the null hypothesis that the mean running speed of cats through a course is not associated with the colour of their fur.\n\n:::{.callout-note #note-significant_p}\n\nNote that even when the data perfectly meets the assumptions for a t-test, it is subject to type I error - we expect to see false positives about 5% of the time. If everyone in the course runs this test, the chances are at least a few people will see significant results here.\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_dog$t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  measurement by group\nt = -5.0268, df = 58, p-value = 5.098e-06\nalternative hypothesis: true difference in means between group group_1 and group group_2 is not equal to 0\n95 percent confidence interval:\n -8.797394 -3.786415\nsample estimates:\nmean in group group_1 mean in group group_2 \n             19.93804              26.22995 \n```\n\n\n:::\n:::\n\n\nIn most cases, the p-value here will be significant and will support rejecting the null hypothesis that the mean running speed of dogs through a course is not associated with the presence of a biscuit at the end of the course.\n\n::: {.callout-note #note-insignificant_p}\n\nNote that even when the data perfectly meets the assumptions for a t-test, it is subject to type II error - we expect to see false negatives. If everyone in the course runs this test, the chances are at least a few people will see insignificant results here.\n\n:::\n\n#### 4\n\n[In a for loop, repeat the following 1000 times for each scenario:]{.blue-text}\n\n* [Simulate 30 data points from each of the populations with the same parameters you used above.]{.blue-text}\n* [Pass the data points to `compare_vectors_short()` to get the p-value of the t-test]{.blue-text}\n* [Store the p-value in a vector.]{.blue-text}\n\nCats:\n \n\n::: {.cell}\n\n```{.r .cell-code}\ncat_ps <- c()\n\nfor (i in seq_len(1000)) {\n  cats_orange <- rnorm(30, mean = 20, sd = 5)\n  cats_black <- rnorm(30, mean = 20, sd = 5)\n\n  cat_p <- compare_vectors_short(cats_orange, cats_black)\n  cat_ps <- c(cat_ps, cat_p)\n}\n```\n:::\n\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndog_ps <- c()\nfor (i in seq_len(1000)) {\n  dogs_no_biscuit <- rnorm(30, mean = 20, sd = 5)\n  dogs_biscuit <- rnorm(30, mean = 24, sd = 5)\n\n\n  dog_p <- compare_vectors_short(dogs_biscuit, dogs_no_biscuit)\n  dog_ps <- c(dog_ps, dog_p)\n}\n```\n:::\n\n\n#### 5\n\n[Plot histograms of the p-values for both sets of simulations.]{.blue-text}\n\nCats:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_cat_ps <- tibble(pvalues = cat_ps)\nggplot(df_cat_ps, aes(x = pvalues)) +\n  geom_histogram(boundary = 0, binwidth = 0.05) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans1.13-1.png){width=672}\n:::\n:::\n\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_dog_ps <- tibble(pvalues = dog_ps)\nggplot(df_dog_ps, aes(x = pvalues)) +\n  geom_histogram(boundary = 0, binwidth = 0.05) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans1.14-1.png){width=672}\n:::\n:::\n\n\n#### 6\n\n[Calculate the type I and type II error rates.]{.blue-text}\n\nType I:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_cat_sig <- sum(cat_ps <= 0.05)\nprop_cat_sig <- n_cat_sig / 1000\nprint(prop_cat_sig)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.048\n```\n\n\n:::\n:::\n\n\nThe percentage of significant p-values for the cat dataset is 4.8% - this is the type I error rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_dog_insig <- sum(dog_ps > 0.05)\nprop_dog_insig <- n_dog_insig / 1000\nprint(prop_dog_insig)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.114\n```\n\n\n:::\n:::\n\n\nThe percentage of insignificant p-values for the dog dataset is 11.4% - this is the type II error rate.\n\n#### 7\n\n[Store the type I and type II error rates as a row in a data frame.]{.blue_text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndd <- tibble(\n  situation = \"normal\",\n  type_I = prop_cat_sig,\n  type_II = prop_dog_insig\n)\ncomparison_df <- bind_rows(comparison_df, dd)\n```\n:::\n\n\n:::\n:::\n\nIn this first analysis, the data **explicitly meet the assumptions for a t-test**, as we have drawn them from a normal distribution and fixed the standard deviation.\n\nTherefore, our diagnostic plots are **within the range of deviations** which are possible with data which does meet the t-test assumptions, even if they are imperfect. We still see type I and type II error.\n\nIf there is no significant effect we expect to see type I error **5%** of the time, if our critical p-value is 0.05.\nTherefore, our expected type I error rate is 0.05, our simulated rate was 0.05\n\nWhen the alternative hypothesis is true, the probability of correctly rejecting the null hypothesis is called the power of the test. The type II error rate is therefore $1-power$. Here, our simulations give us an estimate of the type II error rate directly - 0.11\n\n## Breaking assumptions {#sec-breaking_assumptions}\n\nNow we're going to repeat these similar steps with data which violates the assumptions of a t-test in various ways.\n\n::: {.callout-exercise #ex-break_t_2}\n\nIn your `break_t.qmd` Quarto file, follow these steps for **2** of the following situations. They are the same steps as for the previous exercise and you should be able to reuse the majority of the code. For the situations you didn't choose, please look at the results and conclusions, or compare results with your neighbours. \n\n1. Simulate data points from each of the populations (orange cats, black cats, dogs with a biscuit, dogs without a biscuit) with the specified parameters.\n2.  Pass the sets of data points for each scenario (one scenario at a time) to your `compare_vectors()` function, store the result as `results_cat` or `results_dog`.\n\n3. Based on the output of your function, for each scenario:\n    * Examine the summary table (e.g. `results_cat$summ_df`) to check the mean of each group is approximately as expected. \n    * Examine the distribution of the residuals (e.g. `results_cat$distri`). \n    * Plot and examine diagnostic plots for the linear model (e.g. `results_cat$linear_model`) in each scenario.\n    * Examine the t-test (e.g. `results_cat$t_test`) result. \n\n4. In a for loop, repeat the following 1000 times for each scenario:\n    * Simulate data points from each of the populations with the same parameters you used above.\n    * Pass the data points to `compare_vectors_short()` to get the p-value of the t-test\n    * Store the p-value in a vector.\n\n5.  Plot histograms of the p-values for both sets of simulations. Use `geom_histogram()` as follows `geom_histogram(boundary = 0, binwidth = 0.05)` to divide into bins of width 0.05.\n\n6. Calculate the proportion of significant p-values (p <= 0.05) you have for the cat dataset - these are type I errors - and the proportion of insignificant p-values you have for the dog dataset (p > 0.05) - these are type II errors.\n\n7. Store the type I and type II error rates in the `comparison_df` data frame, with the situation name column value as `skewed`, `unequal_variance`, `unequal_samples_same_var`, and `unequal_samples_diff_var` as specified below.\n\n8. Briefly describe your conclusions.\n\n#### Situation 1 - `skewed`\n\nThe four populations are **right skewed**. Each has 30 individuals and the means and standard deviations are as for our first simulation.\n\nWe can produce right-skewed data using an exponential distribution, with a rate parameter of \\(1/5\\) to give a standard deviation of 5. For an exponential distribution, the mean is equal to the standard deviation, so this distribution will also have a mean of 5. We can shift the distribution to our desired mean by adding a fixed value, as follows:\n  \n\n::: {.cell}\n\n```{.r .cell-code}\ncats_orange <- 15 + rexp(30, rate = 1 / 5)\ncats_black <- 15 + rexp(30, rate = 1 / 5)\ndogs_no_biscuit <- 15 + rexp(30, rate = 1 / 5)\ndogs_biscuit <- 19 + rexp(30, rate = 1 / 5)\n```\n:::\n\n\n:::{.callout-answer collapse=\"true\" #ex_break_t_2_ans}\n\n#### 1\n[Simulate data points from each of the populations with the specified parameters.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncats_orange <- 15 + rexp(30, rate = 1 / 5)\ncats_black <- 15 + rexp(30, rate = 1 / 5)\ndogs_no_biscuit <- 15 + rexp(30, rate = 1 / 5)\ndogs_biscuit <- 19 + rexp(30, rate = 1 / 5)\n```\n:::\n\n\n#### 2\n\n[Pass the sets of data points for each scenario (one scenario at a time) to your `compare_vectors` function.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults_cat <- compare_vectors(cats_orange, cats_black)\n\nresults_dog <- compare_vectors(dogs_no_biscuit, dogs_biscuit)\n```\n:::\n\n\n#### 3\n\n[Look at the summary table to check the mean of each group is approximately as expected.]{.blue-text}\n\nCats:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_cat$summ_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  group   group_mean group_sd\n  <chr>        <dbl>    <dbl>\n1 group_1       20.4     3.79\n2 group_2       19.6     4.83\n```\n\n\n:::\n:::\n\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_dog$summ_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  group   group_mean group_sd\n  <chr>        <dbl>    <dbl>\n1 group_1       19.0     3.21\n2 group_2       23.9     4.78\n```\n\n\n:::\n:::\n\n\n[Examine the distribution of the residuals.]{.blue-text}\n\nCats:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_cat$distri)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans2.5-1.png){width=672}\n:::\n:::\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_dog$distri)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans2.6-1.png){width=672}\n:::\n:::\n\n\n[Plot and examine diagnostic plots for the linear model in each scenario, using the base R `plot` function on the linear model.]{.blue-text}\n\nCat:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(results_cat$linear_model)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans2.7-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans2.7-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans2.7-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans2.7-4.png){width=672}\n:::\n:::\n\nDog:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(results_dog$linear_model)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans2.8-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans2.8-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans2.8-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans2.8-4.png){width=672}\n:::\n:::\n\n\n\n[Examine the t-test result.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_cat$t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  measurement by group\nt = 0.72506, df = 58, p-value = 0.4713\nalternative hypothesis: true difference in means between group group_1 and group group_2 is not equal to 0\n95 percent confidence interval:\n -1.431386  3.057248\nsample estimates:\nmean in group group_1 mean in group group_2 \n             20.44455              19.63162 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_dog$t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  measurement by group\nt = -4.6216, df = 58, p-value = 2.171e-05\nalternative hypothesis: true difference in means between group group_1 and group group_2 is not equal to 0\n95 percent confidence interval:\n -6.963094 -2.754292\nsample estimates:\nmean in group group_1 mean in group group_2 \n             19.03032              23.88901 \n```\n\n\n:::\n:::\n\n\n#### 4\n\n[In a for loop, repeat the following 1000 times for each scenario:]{.blue-text}\n\n* [Simulate data points from each of the populations with the same parameters you used above.]{.blue-text}\n* [Pass the data points to `compare_vectors_short()` to get the p-value of the t-test]{.blue-text}\n* [Store the p-value in a vector.]{.blue-text}\n\nCats:\n \n\n::: {.cell}\n\n```{.r .cell-code}\ncat_ps <- c()\n\nfor (i in seq_len(1000)) {\n  cats_orange <- 15 + rexp(30, rate = 1 / 5)\n  cats_black <- 15 + rexp(30, rate = 1 / 5)\n\n  cat_p <- compare_vectors_short(cats_orange, cats_black)\n  cat_ps <- c(cat_ps, cat_p)\n}\n```\n:::\n\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndog_ps <- c()\nfor (i in seq_len(1000)) {\n  dogs_no_biscuit <- 15 + rexp(30, rate = 1 / 5)\n  dogs_biscuit <- 19 + rexp(30, rate = 1 / 5)\n  dog_p <- compare_vectors_short(dogs_biscuit, dogs_no_biscuit)\n  dog_ps <- c(dog_ps, dog_p)\n}\n```\n:::\n\n\n#### 5\n\n[Plot histograms of the p-values for both sets of simulations.]{.blue-text}\n\nCats:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_cat_ps <- tibble(pvalues = cat_ps)\nggplot(df_cat_ps, aes(x = pvalues)) +\n  geom_histogram(boundary = 0, binwidth = 0.05) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans2.13-1.png){width=672}\n:::\n:::\n\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_dog_ps <- tibble(pvalues = dog_ps)\nggplot(df_dog_ps, aes(x = pvalues)) +\n  geom_histogram(boundary = 0, binwidth = 0.05) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans2.14-1.png){width=672}\n:::\n:::\n\n\n#### 6\n\n[Calculate the type I and type II error rates.]{.blue-text}\n\nType I:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_cat_sig <- sum(cat_ps <= 0.05)\nprop_cat_sig <- n_cat_sig / 1000\nprint(prop_cat_sig)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.041\n```\n\n\n:::\n:::\n\n\nThe percentage of significant p-values for the cat dataset is 4.1% - this is the type I error rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_dog_insig <- sum(dog_ps > 0.05)\nprop_dog_insig <- n_dog_insig / 1000\nprint(prop_dog_insig)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.162\n```\n\n\n:::\n:::\n\n\nThe percentage of insignificant p-values for the dog dataset is 16.2% - this is the type II error rate.\n\n#### 7\n[Store the type I and type II error rates in the `comparison_df` data frame]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndd <- tibble(\n  situation = \"skewed\",\n  type_I = prop_cat_sig,\n  type_II = prop_dog_insig\n)\ncomparison_df <- bind_rows(comparison_df, dd)\n```\n:::\n\n\n#### 8 - Conclusion\n\nThis data is strongly right-skewed, as we can see in the distribution plots. The Q-Q plot also demonstrates that the data is not normally distributed.\n\nNevertheless, the type I and type II error rates here were very similar to those obtained with normally distributed data and the p-value histograms look as expected. The t-test is therefore robust to this violation of the normality assumption **in this example**.\n\nThis is partly because all of the groups are skewed in the same way - the t-test is generally more robust when the groups have similarly shaped distributions than when the distributions differ substantially between groups.\n\n:::\n\n#### Situation 2 - `unequal_variance`\n\n* The four populations are normally distributed but with different **variance**. Each has 30 individuals and the means are as for our first simulation.\n  * Orange cats - 30 data points, mean 20, standard deviation 7\n  * Black cats - 30 data points, mean 20, standard deviation 1\n  * Dogs without biscuits - 30 data points, mean 20, standard deviation 7\n  * Dogs with biscuits - 30 data points with mean 24 and standard deviation 1.\n  \n:::{.callout-answer collapse=\"true\" #ex_break_t_4_ans}\n\n#### 1\n\n[Simulate data points from each of the populations with the specified parameters.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncats_orange <- rnorm(30, 20, 7)\ncats_black <- rnorm(30, 20, 1)\n\ndogs_no_biscuit <- rnorm(30, 20, 7)\ndogs_biscuit <- rnorm(30, 24, 1)\n```\n:::\n\n\n#### 2\n\n[Pass the sets of data points for each scenario (one scenario at a time) to your `compare_vectors` function.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults_cat <- compare_vectors(cats_orange, cats_black)\n\nresults_dog <- compare_vectors(dogs_no_biscuit, dogs_biscuit)\n```\n:::\n\n\n#### 3\n\n[Look at the summary table to check the mean of each group is approximately as expected.]{.blue-text}\n\nCats:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_cat$summ_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  group   group_mean group_sd\n  <chr>        <dbl>    <dbl>\n1 group_1       20.2     4.77\n2 group_2       19.8     1.21\n```\n\n\n:::\n:::\n\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_dog$summ_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  group   group_mean group_sd\n  <chr>        <dbl>    <dbl>\n1 group_1       20.4    7.61 \n2 group_2       24.2    0.915\n```\n\n\n:::\n:::\n\n\n[Examine the distribution of the residuals.]{.blue-text}\n\nCats:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_cat$distri)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans4.5-1.png){width=672}\n:::\n:::\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_dog$distri)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans4.6-1.png){width=672}\n:::\n:::\n\n\n[Plot and examine diagnostic plots for the linear model in each scenario, using the base R `plot` function on the linear model.]{.blue-text}\n\nCat:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(results_cat$linear_model)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans4.7-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans4.7-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans4.7-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans4.7-4.png){width=672}\n:::\n:::\n\nDog:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(results_dog$linear_model)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans4.8-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans4.8-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans4.8-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans4.8-4.png){width=672}\n:::\n:::\n\n\n\n[Examine the t-test result.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_cat$t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  measurement by group\nt = 0.50206, df = 58, p-value = 0.6175\nalternative hypothesis: true difference in means between group group_1 and group group_2 is not equal to 0\n95 percent confidence interval:\n -1.347670  2.250016\nsample estimates:\nmean in group group_1 mean in group group_2 \n             20.20217              19.75100 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_dog$t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  measurement by group\nt = -2.7008, df = 58, p-value = 0.009052\nalternative hypothesis: true difference in means between group group_1 and group group_2 is not equal to 0\n95 percent confidence interval:\n -6.5775361 -0.9778703\nsample estimates:\nmean in group group_1 mean in group group_2 \n              20.4064               24.1841 \n```\n\n\n:::\n:::\n\n\n#### 4\n\n[In a for loop, repeat the following 1000 times for each scenario:]{.blue-text}\n\n* [Simulate data points from each of the populations with the same parameters you used above.]{.blue-text}\n* [Pass the data points to `compare_vectors_short()` to get the p-value of the t-test]{.blue-text}\n* [Store the p-value in a vector.]{.blue-text}\n\nCats:\n \n\n::: {.cell}\n\n```{.r .cell-code}\ncat_ps <- c()\n\nfor (i in seq_len(1000)) {\n  cats_orange <- rnorm(30, 20, 7)\n  cats_black <- rnorm(30, 20, 1)\n\n  cat_p <- compare_vectors_short(cats_orange, cats_black)\n  cat_ps <- c(cat_ps, cat_p)\n}\n```\n:::\n\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndog_ps <- c()\nfor (i in seq_len(1000)) {\n  dogs_no_biscuit <- rnorm(30, 20, 7)\n  dogs_biscuit <- rnorm(30, 24, 1)\n\n  dog_p <- compare_vectors_short(dogs_biscuit, dogs_no_biscuit)\n  dog_ps <- c(dog_ps, dog_p)\n}\n```\n:::\n\n\n#### 5\n\n[Plot histograms of the p-values for both sets of simulations.]{.blue-text}\n\nCats:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_cat_ps <- tibble(pvalues = cat_ps)\nggplot(df_cat_ps, aes(x = pvalues)) +\n  geom_histogram(boundary = 0, binwidth = 0.05) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans4.13-1.png){width=672}\n:::\n:::\n\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_dog_ps <- tibble(pvalues = dog_ps)\nggplot(df_dog_ps, aes(x = pvalues)) +\n  geom_histogram(boundary = 0, binwidth = 0.05) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans4.14-1.png){width=672}\n:::\n:::\n\n\n#### 6\n\n[Calculate the type I and type II error rates.]{.blue-text}\n\nType I:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_cat_sig <- sum(cat_ps <= 0.05)\nprop_cat_sig <- n_cat_sig / 1000\nprint(prop_cat_sig)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.049\n```\n\n\n:::\n:::\n\n\nThe percentage of significant p-values for the cat dataset is 4.9% - this is the type I error rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_dog_insig <- sum(dog_ps > 0.05)\nprop_dog_insig <- n_dog_insig / 1000\nprint(prop_dog_insig)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.137\n```\n\n\n:::\n:::\n\n\nThe percentage of insignificant p-values for the dog dataset is 13.7% - this is the type II error rate.\n\n#### 7\n\n[Store the type I and type II error rates in the `comparison_df` data frame]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndd <- tibble(\n  situation = \"unequal_variance\",\n  type_I = prop_cat_sig,\n  type_II = prop_dog_insig\n)\ncomparison_df <- bind_rows(comparison_df, dd)\n```\n:::\n\n\n#### 8 - Conclusion\nThese two groups have very different variances, as we can clearly see in the distribution plot, the residuals vs fitted plot and the scale-location plot.\n\nDespite the two groups having substantially different variances, the type I error rate remained close to 5% and the p-value plots look as expected. The t-test was therefore fairly robust to unequal variance **in this example**, where groups differ **only** in their variance.\n\n:::\n\n#### Situation 3 - `unequal_samples_same_var`\n\n* The four populations are normally distributed with the same **variance** and different **sample size**. The means are the same as for our first simulation.\n  * Orange cats - 40 data points, mean 20, standard deviation 5\n  * Black cats - 20 data points, mean 20, standard deviation 5\n  * Dogs without biscuits - 40 data points, mean 20, standard deviation 5\n  * Dogs with biscuits - 20 data points with mean 24 and standard deviation 5.\n\n\n:::{.callout-answer collapse=\"true\" #ex_break_t_5_ans}\n\n#### 1\n\n[Simulate data points from each of the populations with the specified parameters.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncats_orange <- rnorm(40, 20, 5)\ncats_black <- rnorm(20, 20, 5)\n\ndogs_no_biscuit <- rnorm(40, 20, 5)\ndogs_biscuit <- rnorm(20, 24, 5)\n```\n:::\n\n\n#### 2\n\n[Pass the sets of data points for each scenario (one scenario at a time) to your `compare_vectors` function.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults_cat <- compare_vectors(cats_orange, cats_black)\n\nresults_dog <- compare_vectors(dogs_no_biscuit, dogs_biscuit)\n```\n:::\n\n\n#### 3\n\n[Look at the summary table to check the mean of each group is approximately as expected.]{.blue-text}\n\nCats:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_cat$summ_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  group   group_mean group_sd\n  <chr>        <dbl>    <dbl>\n1 group_1       19.7     6.08\n2 group_2       20.5     5.01\n```\n\n\n:::\n:::\n\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_dog$summ_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  group   group_mean group_sd\n  <chr>        <dbl>    <dbl>\n1 group_1       20.5     4.19\n2 group_2       22.7     4.85\n```\n\n\n:::\n:::\n\n\n[Examine the distribution of the residuals.]{.blue-text}\n\nCats:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_cat$distri)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans6.5-1.png){width=672}\n:::\n:::\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_dog$distri)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans6.6-1.png){width=672}\n:::\n:::\n\n\n[Plot and examine diagnostic plots for the linear model in each scenario, using the base R `plot` function on the linear model.]{.blue-text}\n\nCat:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(results_cat$linear_model)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans6.7-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans6.7-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans6.7-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans6.7-4.png){width=672}\n:::\n:::\n\nDog:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(results_dog$linear_model)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans6.8-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans6.8-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans6.8-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans6.8-4.png){width=672}\n:::\n:::\n\n\n\n[Examine the t-test result.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_cat$t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  measurement by group\nt = -0.49156, df = 58, p-value = 0.6249\nalternative hypothesis: true difference in means between group group_1 and group group_2 is not equal to 0\n95 percent confidence interval:\n -3.927796  2.379043\nsample estimates:\nmean in group group_1 mean in group group_2 \n             19.69459              20.46897 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_dog$t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  measurement by group\nt = -1.7963, df = 58, p-value = 0.07765\nalternative hypothesis: true difference in means between group group_1 and group group_2 is not equal to 0\n95 percent confidence interval:\n -4.5927115  0.2483447\nsample estimates:\nmean in group group_1 mean in group group_2 \n             20.54557              22.71776 \n```\n\n\n:::\n:::\n\n\n#### 4\n\n[In a for loop, repeat the following 1000 times for each scenario:]{.blue-text}\n\n* [Simulate data points from each of the populations with the same parameters you used above.]{.blue-text}\n* [Pass the data points to `compare_vectors_short()` to get the p-value of the t-test]{.blue-text}\n* [Store the p-value in a vector.]{.blue-text}\n\nCats:\n \n\n::: {.cell}\n\n```{.r .cell-code}\ncat_ps <- c()\n\nfor (i in seq_len(1000)) {\n  cats_orange <- rnorm(40, 20, 5)\n  cats_black <- rnorm(20, 20, 5)\n\n  cat_p <- compare_vectors_short(cats_orange, cats_black)\n  cat_ps <- c(cat_ps, cat_p)\n}\n```\n:::\n\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndog_ps <- c()\nfor (i in seq_len(1000)) {\n  dogs_no_biscuit <- rnorm(40, 20, 5)\n  dogs_biscuit <- rnorm(20, 24, 5)\n\n  dog_p <- compare_vectors_short(dogs_biscuit, dogs_no_biscuit)\n  dog_ps <- c(dog_ps, dog_p)\n}\n```\n:::\n\n\n#### 5\n\n[Plot histograms of the p-values for both sets of simulations.]{.blue-text}\n\nCats:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_cat_ps <- tibble(pvalues = cat_ps)\nggplot(df_cat_ps, aes(x = pvalues)) +\n  geom_histogram(boundary = 0, binwidth = 0.05) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans6.13-1.png){width=672}\n:::\n:::\n\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_dog_ps <- tibble(pvalues = dog_ps)\nggplot(df_dog_ps, aes(x = pvalues)) +\n  geom_histogram(boundary = 0, binwidth = 0.05) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans6.14-1.png){width=672}\n:::\n:::\n\n\n#### 6\n\n[Calculate the type I and type II error rates.]{.blue-text}\n\nType I:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_cat_sig <- sum(cat_ps <= 0.05)\nprop_cat_sig <- n_cat_sig / 1000\nprint(prop_cat_sig)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.047\n```\n\n\n:::\n:::\n\n\nThe percentage of significant p-values for the cat dataset is 4.7% - this is the type I error rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_dog_insig <- sum(dog_ps > 0.05)\nprop_dog_insig <- n_dog_insig / 1000\nprint(prop_dog_insig)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.163\n```\n\n\n:::\n:::\n\n\nThe percentage of insignificant p-values for the dog dataset is 16.3% - this is the type II error rate.\n\n#### 7\n\n[Store the type I and type II error rates in the `comparison_df` data frame]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndd <- tibble(\n  situation = \"unequal_samples_same_var\",\n  type_I = prop_cat_sig,\n  type_II = prop_dog_insig\n)\ncomparison_df <- bind_rows(comparison_df, dd)\n```\n:::\n\n\n#### 8 - Conclusion\n\nThe unequal sample sizes in this data set don't have much apparent impact on any of the diagnostic plots - the populations are still normally distributed with equal variance.\n\nThe t-test is also still functioning well, the p-value plots look as expected and the type I and type II error rates are similar to those when sample sizes were the same.\n\nEqual sample sizes are not an assumption of the t-test. A t-test can compare groups of different sizes, provided its other assumptions are reasonably well met.\n\n:::\n\n#### Situation 4 - `unequal_samples_different_var`\n\n* The four populations are normally distributed with different **variance** and different **sample size**. The means are the same as for our first simulation.\n  * Orange cats - 40 data points, mean 20, standard deviation 7.\n  * Black cats - 20 data points, mean 20, standard deviation 1.\n  * Dogs without biscuits - 40 data points, mean 20, standard deviation 7.\n  * Dogs with biscuits - 20 data points with mean 24 and standard deviation 1.\n\n\n:::{.callout-answer collapse=\"true\" #ex_break_t_7_ans}\n\n#### 1\n\n[Simulate data points from each of the populations with the specified parameters.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncats_orange <- rnorm(40, 20, 7)\ncats_black <- rnorm(20, 20, 1)\n\ndogs_no_biscuit <- rnorm(40, 20, 7)\ndogs_biscuit <- rnorm(20, 24, 1)\n```\n:::\n\n\n#### 2\n\n[Pass the sets of data points for each scenario (one scenario at a time) to your `compare_vectors` function.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults_cat <- compare_vectors(cats_orange, cats_black)\n\nresults_dog <- compare_vectors(dogs_no_biscuit, dogs_biscuit)\n```\n:::\n\n\n#### 3\n\n[Look at the summary table to check the mean of each group is approximately as expected.]{.blue-text}\n\nCats:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_cat$summ_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  group   group_mean group_sd\n  <chr>        <dbl>    <dbl>\n1 group_1       19.4    6.58 \n2 group_2       19.7    0.895\n```\n\n\n:::\n:::\n\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_dog$summ_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  group   group_mean group_sd\n  <chr>        <dbl>    <dbl>\n1 group_1       19.4     7.89\n2 group_2       23.9     1.01\n```\n\n\n:::\n:::\n\n\n[Examine the distribution of the residuals.]{.blue-text}\n\nCats:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_cat$distri)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans7.5-1.png){width=672}\n:::\n:::\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_dog$distri)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans7.6-1.png){width=672}\n:::\n:::\n\n\n[Plot and examine diagnostic plots for the linear model in each scenario, using the base R `plot` function on the linear model.]{.blue-text}\n\nCat:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(results_cat$linear_model)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans7.7-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans7.7-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans7.7-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans7.7-4.png){width=672}\n:::\n:::\n\nDog:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(results_dog$linear_model)\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans7.8-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans7.8-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans7.8-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans7.8-4.png){width=672}\n:::\n:::\n\n\n\n[Examine the t-test result.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_cat$t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  measurement by group\nt = -0.15983, df = 58, p-value = 0.8736\nalternative hypothesis: true difference in means between group group_1 and group group_2 is not equal to 0\n95 percent confidence interval:\n -3.208551  2.734055\nsample estimates:\nmean in group group_1 mean in group group_2 \n             19.44962              19.68686 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(results_dog$t_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  measurement by group\nt = -2.5362, df = 58, p-value = 0.01392\nalternative hypothesis: true difference in means between group group_1 and group group_2 is not equal to 0\n95 percent confidence interval:\n -8.0679693 -0.9503349\nsample estimates:\nmean in group group_1 mean in group group_2 \n             19.37217              23.88132 \n```\n\n\n:::\n:::\n\n\n#### 4\n\n[In a for loop, repeat the following 1000 times for each scenario:]{.blue-text}\n\n* [Simulate data points from each of the populations with the same parameters you used above.]{.blue-text}\n* [Pass the data points to `compare_vectors_short()` to get the p-value of the t-test]{.blue-text}\n* [Store the p-value in a vector.]{.blue-text}\n\nCats:\n \n\n::: {.cell}\n\n```{.r .cell-code}\ncat_ps <- c()\n\nfor (i in seq_len(1000)) {\n  cats_orange <- rnorm(40, 20, 7)\n  cats_black <- rnorm(20, 20, 1)\n\n  cat_p <- compare_vectors_short(cats_orange, cats_black)\n  cat_ps <- c(cat_ps, cat_p)\n}\n```\n:::\n\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndog_ps <- c()\nfor (i in seq_len(1000)) {\n  dogs_no_biscuit <- rnorm(40, 20, 7)\n  dogs_biscuit <- rnorm(20, 24, 1)\n\n  dog_p <- compare_vectors_short(dogs_biscuit, dogs_no_biscuit)\n  dog_ps <- c(dog_ps, dog_p)\n}\n```\n:::\n\n\n#### 5\n\n[Plot histograms of the p-values for both sets of simulations.]{.blue-text}\n\nCats:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_cat_ps <- tibble(pvalues = cat_ps)\nggplot(df_cat_ps, aes(x = pvalues)) +\n  geom_histogram(boundary = 0, binwidth = 0.05) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans7.13-1.png){width=672}\n:::\n:::\n\n\nDogs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_dog_ps <- tibble(pvalues = dog_ps)\nggplot(df_dog_ps, aes(x = pvalues)) +\n  geom_histogram(boundary = 0, binwidth = 0.05) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06-03_breaking_assumptions_files/figure-html/break_t_ans7.14-1.png){width=672}\n:::\n:::\n\n\n#### 6\n\n[Calculate the type I and type II error rates.]{.blue-text}\n\nType I:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_cat_sig <- sum(cat_ps <= 0.05)\nprop_cat_sig <- n_cat_sig / 1000\nprint(prop_cat_sig)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.009\n```\n\n\n:::\n:::\n\n\nThe percentage of significant p-values for the cat dataset is 0.9% - this is the type I error rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_dog_insig <- sum(dog_ps > 0.05)\nprop_dog_insig <- n_dog_insig / 1000\nprint(prop_dog_insig)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.217\n```\n\n\n:::\n:::\n\n\nThe percentage of insignificant p-values for the dog dataset is 21.7% - this is the type II error rate.\n\n#### 7\n\n[Store the type I and type II error rates in the `comparison_df` data frame]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndd <- tibble(\n  situation = \"unequal_samples_diff_var\",\n  type_I = prop_cat_sig,\n  type_II = prop_dog_insig\n)\ncomparison_df <- bind_rows(comparison_df, dd)\n```\n:::\n\n\n#### 8 - Conclusion\n\nWhen the groups have both unequal variances and unequal sample sizes, the diagnostic plots show the difference in variance, but may not look dramatically worse than when the sample sizes were equal.\n\nHowever, the p-values produced when the null hypothesis is true are no longer uniformly distributed. Instead of the approximately flat distribution seen in the previous examples, the p-value distribution is curved, with relatively few very small p-values. The type I error rate is therefore lower than the expected 5%. In this example, the t-test has become too conservative: it rejects the null hypothesis less often than it should.\n\nImportantly, unequal sample sizes and unequal variances interact. Neither caused a major problem on its own in our previous examples, but together they can make the standard t-test unreliable.\n\nThis also demonstrates why diagnostic plots should not be treated as a simple pass/fail test: the plots do not necessarily look dramatically different even though the behaviour of the statistical test has changed.\n\n:::\n:::\n\nNow let's look at the error rates for all of the simulations above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngt(comparison_df)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"rohomhqvpy\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rohomhqvpy table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rohomhqvpy thead, #rohomhqvpy tbody, #rohomhqvpy tfoot, #rohomhqvpy tr, #rohomhqvpy td, #rohomhqvpy th {\n  border-style: none;\n}\n\n#rohomhqvpy p {\n  margin: 0;\n  padding: 0;\n}\n\n#rohomhqvpy .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rohomhqvpy .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rohomhqvpy .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rohomhqvpy .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rohomhqvpy .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rohomhqvpy .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rohomhqvpy .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rohomhqvpy .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rohomhqvpy .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rohomhqvpy .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rohomhqvpy .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rohomhqvpy .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rohomhqvpy .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rohomhqvpy .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rohomhqvpy .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rohomhqvpy .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rohomhqvpy .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rohomhqvpy .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rohomhqvpy .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rohomhqvpy .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rohomhqvpy .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rohomhqvpy .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rohomhqvpy .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rohomhqvpy .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rohomhqvpy .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rohomhqvpy .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rohomhqvpy .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rohomhqvpy .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rohomhqvpy .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rohomhqvpy .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rohomhqvpy .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rohomhqvpy .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rohomhqvpy .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rohomhqvpy .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rohomhqvpy .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rohomhqvpy .gt_left {\n  text-align: left;\n}\n\n#rohomhqvpy .gt_center {\n  text-align: center;\n}\n\n#rohomhqvpy .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rohomhqvpy .gt_font_normal {\n  font-weight: normal;\n}\n\n#rohomhqvpy .gt_font_bold {\n  font-weight: bold;\n}\n\n#rohomhqvpy .gt_font_italic {\n  font-style: italic;\n}\n\n#rohomhqvpy .gt_super {\n  font-size: 65%;\n}\n\n#rohomhqvpy .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rohomhqvpy .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rohomhqvpy .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rohomhqvpy .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rohomhqvpy .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rohomhqvpy .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rohomhqvpy .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#rohomhqvpy .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#rohomhqvpy div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"situation\">situation</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"type_I\">type_I</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"type_II\">type_II</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"situation\" class=\"gt_row gt_left\">normal</td>\n<td headers=\"type_I\" class=\"gt_row gt_right\">0.048</td>\n<td headers=\"type_II\" class=\"gt_row gt_right\">0.114</td></tr>\n    <tr><td headers=\"situation\" class=\"gt_row gt_left\">skewed</td>\n<td headers=\"type_I\" class=\"gt_row gt_right\">0.041</td>\n<td headers=\"type_II\" class=\"gt_row gt_right\">0.162</td></tr>\n    <tr><td headers=\"situation\" class=\"gt_row gt_left\">unequal_variance</td>\n<td headers=\"type_I\" class=\"gt_row gt_right\">0.049</td>\n<td headers=\"type_II\" class=\"gt_row gt_right\">0.137</td></tr>\n    <tr><td headers=\"situation\" class=\"gt_row gt_left\">unequal_samples_same_var</td>\n<td headers=\"type_I\" class=\"gt_row gt_right\">0.047</td>\n<td headers=\"type_II\" class=\"gt_row gt_right\">0.163</td></tr>\n    <tr><td headers=\"situation\" class=\"gt_row gt_left\">unequal_samples_diff_var</td>\n<td headers=\"type_I\" class=\"gt_row gt_right\">0.009</td>\n<td headers=\"type_II\" class=\"gt_row gt_right\">0.217</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThis shows that even with our relatively small sample sizes, the t-test is robust to some violations of its assumptions - at least in these very controlled simulations where only one assumption is violated at a time. \nWe have also demonstrated that the diagnostic plots are useful but they are not definitive - sometimes the test performs well even if they look quite questionable.\n\n::: {.callout-bonus #bon-really_break_t_test}\n\nWithout changing the population means, see if you really can break the t-test. This could be by violating multiple assumptions, changing the sample sizes, adding outliers, dragging the data further from normality, or anything else you can think of!\n\nIf you do manage to break it, submit your sample distributions [here]() and we will create a site to showcase your results (anonymously).\n\n:::\n## Review {#sec-summary_0603}\n\n[↑ top](#)\n\n::: {.callout-note #note-summary_0603}\n\n### Summary\n\n\n:::\n\nFor this part of the practical, the main files you have created are:\n\nThese are the files you should select when making your Git commit.\n\n\nRemember to save and commit your work before moving on to Part 4.\n\n::: {.callout-tip}\n## Commit your changes\nRemember to save your progress regularly by committing your changes with Git.\n\n1. Save your changes to the files above in RStudio with the `Save` button.\n2. Render any Quarto documents with the `Render` button.\n3. Open the `Git` tab in RStudio.\n4. Tick the files listed above, don't worry about any others.\n5. Click `Commit` and write a short message in the `Commit message` describing your changes, something like e.g. \"Practical 1 part 1\" is sufficient, then click `Commit`. Close the `Commit` popup.\n\n:::\n\t\n\n",
    "supporting": [
      "06-03_breaking_assumptions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}