{
  "hash": "83cb3bf74d71fd50fd45aa1f0561cc54",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: html\npractical: Practical_4_Statistics\ndoc-id: \"0404\"\nauthor: \"Katy Brown\"\n---\n\n\n\n# Part 4: Linear regression and Chi-Squared {#sec-p3_linear_regression_chisq}\n\n::: {.callout-note .partmenu #parts-0404}\n## Sections\n- @sec-linear_regression\n- @sec-multiple_linear_regression\n- @sec-multicollinearity\n- @sec-chi_squared\n- @sec-summary_0404\n:::\n\n:::{.callout-tip .objectives}\n#### Learning objectives\nBy the end of this part of the practical you will be able to:\n:::\n\n## Linear Regression {#sec-linear_regression}\n\nWe've now used all sorts of linear models, but how about a standard linear regression between two continuous variables? You already have the skills needed to do this - you can fit the model using `lm()` and then view the results using `summary()`, and you basically know how to interpret the results. \n\nAs we discussed in the previous section, for a linear model we should report the following:\n\n* **Coefficient (slope):** `Estimate` – the expected change in the response variable associated with a one-unit increase in that explanatory variable, holding the other explanatory variables constant.\n* **Test statistic:** `t value`\n* **Degrees of freedom:** residual degrees of freedom\n* **p-value:** `Pr(>|t|)`\n* **Proportion of variation explained:** `Multiple R-squared`\n\nFor a linear regression with two continuous variables, we can also report the amount the mean of the response variable changes when the explanatory variable changes by one unit.\n\nLet's use the pollinator data again and look at a straightforward regression question - how is total annual precipitation (column `annual_total_prec`) associated with mean annual temperature (column `annual_mean_temp`)?\n\n### Hypotheses\n\n* Null: There is no association between total annual precipitation and mean annual temperature.\n* Alternative: Total annual precipitation is associated with mean annual temperature.\n\n### Plot\n\nA scatter plot is the most common plot to compare two continuous variables. We can use `geom_smooth(method = \"lm\")` to add a linear model to the plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(site_metadata,\n       aes(x = annual_mean_temp,\n           y = annual_total_prec)) +\n  geom_point() +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](04-04_hypothesis_testing_3_files/figure-html/plot_temp_prec-1.png){width=672}\n:::\n:::\n\n\n## Multiple linear regression {#sec-multiple_linear_regression}\n\nJust as we included multiple explanatory variables in our ANOVA, we can include multiple continuous explanatory variables in a linear regression. This is called multiple linear regression. We can also add interaction terms.\n\nFor example, we could ask if precipitation is associated with temperature, elevation or the interaction between the two, using `annual_total_prec ~ annual_mean_temp * elevation`.\n\nThere is one complication here - by default, a multiple regression containing an interaction will determine the association with each explanatory variable **when the value of the other explanatory variables is zero**. This is not the case for an additive model, where the association with each explanatory variable is estimated while holding the other explanatory variables constant.\n\nSo, in our case, our model `annual_total_prec ~ annual_mean_temp * elevation` will tell us:\n\n* Is precipitation associated with annual mean temperature **when elevation is 0**?\n* Is precipitation associated with elevation **when annual mean temperature is 0**?\n* Does the association between annual mean temperature and precipitation depend on elevation?\n\nThe first two questions are not usually quite what we want to ask. Better questions might be:\n\n* Is precipitation associated with annual mean temperature **at the mean elevation**.\n* Is precipitation associated with elevation **at the mean annual temperature**.\n\nWe can ask this by **centring** our data for elevation and temperature - subtracting our mean value from all observations to create a new set of centred observations with mean zero. The shape and spread of the variables remains the same, but the model is now answering more useful questions.\n\nLet's add these new columns to our data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsite_metadata_cent <- site_metadata |>\n  mutate(\n    annual_mean_temp_cent = annual_mean_temp - mean(annual_mean_temp),\n    elevation_cent = elevation - mean(elevation)\n  )\n```\n:::\n\n\n### Hypotheses\n\nSo, now our hypotheses are:\n\nAnnual mean temperature:\n\n* Null: At the mean elevation, there is no association between annual mean temperature and precipitation.\n* Alternative: At the mean elevation, there is an association between annual mean temperature and precipitation.\n\nElevation:\n\n* Null: At the mean annual temperature, there is no association between elevation and precipitation.\n* Alternative: At the mean annual temperature, there is an association between elevation and precipitation.\n\nInteraction:\n\n* Null: The association between annual mean temperature and precipitation does not depend on elevation.\n* Alternative: The association between annual mean temperature and precipitation depends on elevation.\n\n### Plot\n\nA scatter plot is again a good visualisation here, and we can use the function `facet_wrap()` again to separate the data into two plots, one for annual mean temperature vs annual total precipitation, and one for elevation vs annual total precipitation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract relevant columns and convert to long format\nelev_temp_long <- site_metadata |>\n  select(x1km_square, annual_total_prec,\n         annual_mean_temp, elevation) |>\n  pivot_longer(\n    c(\n      annual_mean_temp,\n      elevation\n    ),\n    names_to = \"variable\",\n    values_to = \"value\"\n  )\n\n# Plot\nggplot(elev_temp_long,\n       aes(x = value,\n           y = annual_total_prec)) +\n  geom_point() +\n  facet_wrap(~variable, scale='free_x') +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](04-04_hypothesis_testing_3_files/figure-html/plot_lm_elev_temp-1.png){width=672}\n:::\n:::\n\n\n### Statistical test\n\nNow we can fit our linear model using these new columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_elev_temp <- lm(annual_total_prec ~ annual_mean_temp_cent * elevation_cent, data = site_metadata_cent)\nsumm_lm_elev_temp <- summary(lm_elev_temp)\nprint(summ_lm_elev_temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = annual_total_prec ~ annual_mean_temp_cent * elevation_cent, \n    data = site_metadata_cent)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-517.10 -186.68  -77.44  189.05  637.89 \n\nCoefficients:\n                                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                          1075.9594    36.3408  29.608  < 2e-16 ***\nannual_mean_temp_cent                 -66.3939    42.4250  -1.565 0.121975    \nelevation_cent                          1.6579     0.4555   3.639 0.000511 ***\nannual_mean_temp_cent:elevation_cent    0.0771     0.1657   0.465 0.643064    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 259.2 on 72 degrees of freedom\nMultiple R-squared:  0.533,\tAdjusted R-squared:  0.5136 \nF-statistic: 27.39 on 3 and 72 DF,  p-value: 6.282e-12\n```\n\n\n:::\n:::\n\n\n### Conclusion\n\n\n\n::: {.highlight-box}\nThere is no evidence of an association between mean annual temperature and total annual precipitation at the mean elevation ($b$ = -66.39, $t$(72) = -1.56, $p$ = 0.122). There is evidence of a positive association between elevation and total annual precipitation at the mean annual temperature ($b$ = 1.66, $t$(72) = 3.64, $p$ = 5.11e-04). There is no evidence of an interaction between mean annual temperature and elevation ($b$ = 0.077, $t$(72) = 0.47, $p$ = 0.643), so there is no evidence that the association between temperature and precipitation changes with elevation. Overall, the model explains 53.3% of the variation in total annual precipitation ($R^2$ = 0.533).\n:::\n\n## Multicollinearity {#sec-multicollinearity}\n\nThis result seems strange at first — precipitation was strongly associated with annual mean temperature when temperature was the only explanatory variable, but there is no longer strong evidence for that association once elevation is included.\n\n**Multicollinearity** occurs when two or more explanatory variables in a multiple regression are strongly associated with each other.\n\nFor example, we are trying to explain variation in precipitation using both temperature and elevation. But if elevation and temperature are closely related - for example, if higher sites tend to be colder - the model is trying to separate the associations with two variables which tend to change together.\n\n* If only temperature is in the model, we are asking - does temperature explain variation in precipitation?\n* If both temperature and elevation are in the model, we are asking - does temperature explain variation in precipitation over and above the variation associated with elevation?\n\nIf temperature and elevation are highly correlated, there may not be much independent information with which to separate their associations with precipitation. Consequently, the estimated individual coefficients can become less precise, their standard errors can become larger, and their p-values can increase.\n\nThis does not necessarily mean that the multiple regression model is worse at explaining precipitation. Rather, multicollinearity makes it more difficult to determine the individual association between each explanatory variable and the response.\n\nLet's check the correlation between the annual mean temperature and elevation. We can calculate the correlation coefficient using the R function `cor`·\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrelation <- site_metadata |>\n  summarise(correlation = cor(annual_mean_temp, elevation))\n\ngt(correlation)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qeayjdrzqo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qeayjdrzqo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qeayjdrzqo thead, #qeayjdrzqo tbody, #qeayjdrzqo tfoot, #qeayjdrzqo tr, #qeayjdrzqo td, #qeayjdrzqo th {\n  border-style: none;\n}\n\n#qeayjdrzqo p {\n  margin: 0;\n  padding: 0;\n}\n\n#qeayjdrzqo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qeayjdrzqo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qeayjdrzqo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qeayjdrzqo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qeayjdrzqo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qeayjdrzqo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qeayjdrzqo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qeayjdrzqo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qeayjdrzqo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qeayjdrzqo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qeayjdrzqo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qeayjdrzqo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qeayjdrzqo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qeayjdrzqo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qeayjdrzqo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qeayjdrzqo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qeayjdrzqo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qeayjdrzqo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qeayjdrzqo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qeayjdrzqo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_left {\n  text-align: left;\n}\n\n#qeayjdrzqo .gt_center {\n  text-align: center;\n}\n\n#qeayjdrzqo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qeayjdrzqo .gt_font_normal {\n  font-weight: normal;\n}\n\n#qeayjdrzqo .gt_font_bold {\n  font-weight: bold;\n}\n\n#qeayjdrzqo .gt_font_italic {\n  font-style: italic;\n}\n\n#qeayjdrzqo .gt_super {\n  font-size: 65%;\n}\n\n#qeayjdrzqo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qeayjdrzqo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qeayjdrzqo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qeayjdrzqo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qeayjdrzqo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qeayjdrzqo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qeayjdrzqo .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qeayjdrzqo .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#qeayjdrzqo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"correlation\">correlation</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"correlation\" class=\"gt_row gt_right\">-0.817405</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nWe can also visualise this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(site_metadata, \n       aes(x = annual_mean_temp, y = elevation)) +\n  geom_point() +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](04-04_hypothesis_testing_3_files/figure-html/plot_corr_mcl-1.png){width=672}\n:::\n:::\n\n\nThese two variables are clearly highly correlated ($r$ = `r round(correlation, 2)), so multicollinearity is a plausible explanation for the much higher p-value for temperature when elevation is included in the model.\n\n::: {.callout-note .bonus collapse=\"true\" #bon-multicollinearity}\n\n### Bonus content: Investigating multicollinearity\n\nWe can investigate the effect of multicollinearity by explicitly controlling the correlation between our explanatory variables.\n\nSince at this point in the practical I think we need a picture of a hedgehog, let's say we want to predict if the weight of a hedgehog in grams is associated with:\n\n1) How much water it drinks per day in millilitres.\n2) How much food it eats per day in grams. \n\n![A hedgehog eating](images/hedgehog.jpg){#fig-hog width=\"50%\"}\n\nLet's say that:\n\n* For each 100 ml of water the hedgehog drinks per day, its weight is **30 g** heavier on average.\n* For each 100 g of food the hedgehog eats per day, its weight is **50 g** heavier on average.\n* The effects are additive with no interaction.\n\n$$\n\\text{weight}_i = 500 + 0.3\\,\\text{water}_i + 0.5\\,\\text{food}_i + \\epsilon_i\n$$\n\nLet's say we have 50 hedgehogs, and hedgehog water intake is a normal distribution with mean 70 ml and standard deviation 40 ml. There is also random noise with a mean of 0g and a standard deviation of 30 g. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_hedgehogs <- 50\nwater <- rnorm(n_hedgehogs, 70, 40)\nnoise <- rnorm(n_hedgehogs, 0, 30)\n```\n:::\n\n\nTo investigate multicollinearity, we will simulate food and water consumption with different strengths of association - i.e. with different values of $R^2$ - between food and water intake.\n\nWe can do this by constructing food consumption with a proportion of variation associated with water consumption and a proportion of random variation. As we increase the extent to which food consumption is associated with water consumption, $R^2$ between the two explanatory variables increases.\n\nImportantly, we **will not change the relationship between food, water and hedgehog weight**. This allows us to investigate what happens to our regression estimates as multicollinearity increases.\n\nFirst, we centre and scale the variation in water consumption so it has a mean of 0 and a standard deviation of 1. We can also generate random noise with a mean of 0 and a standard deviation of 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwater_z <- (water - mean(water)) / sd(water)\nnoise_food <- rnorm(n_hedgehogs, 0, 1)\n```\n:::\n\n\nHere, $R^2$ is the squared correlation between food and water intake, and describes the proportion of variation in food intake associated with variation in water intake.\n\nFor example, to simulate $R^2$ = 0.3, we construct food intake so that 30% of its variance comes from the component associated with water intake and 70% comes from random variation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrsq <- 0.3\n\nfood_var_water <- sqrt(rsq) * water_z\nfood_var_noise <- sqrt(1 - rsq) * noise_food\n\nfood_var_total <- food_var_water + food_var_noise\n```\n:::\n\n\nWe can then scale these standardised values so that food intake has a mean of 100 g per day and a standard deviation of 50 g.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_food <- 100\nfood_sd <- 50\nfood <- mean_food + (food_var_total * food_sd)\n```\n:::\n\n\nThis gives us 50 food data points which have a mean of approx 100g, a standard deviation of approx 50g and an $R^2$ of approx 0.3 with water intake.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(paste(\"mean = \", mean(food)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"mean =  92.0929749689055\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(paste(\"sd = \", sd(food)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"sd =  55.2113355374634\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(paste(\"R2 = \", cor(food, water)^2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"R2 =  0.331159596417852\"\n```\n\n\n:::\n:::\n\n\nNow we can run this analysis with $R^2$ values ranging from 0 to 0.99, with an increment of 0.01.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhog_results <- tibble()\n\nfor (rsq in seq(0, 0.99, 0.01)) {\n  # Calculate the food values based on the water values\n  # plus noise\n  food_var_water <- sqrt(rsq) * water_z\n  food_var_noise <- sqrt(1 - rsq) * noise_food\n  food_var_total <- food_var_water + food_var_noise\n\n  # Scale up food values\n  food <- mean_food + (food_var_total * food_sd)\n\n  # Apply the model to calculate hedgehog weight\n  hogs <- 500 + (water * 0.3) + (food * 0.5) + noise\n\n  # Put the three columns into a data frame\n  hog_df <- tibble(\n    weight = hogs,\n    water = water,\n    food = food\n  )\n\n  # Fit and summarise the linear model\n  lm_hogs_both <- summary(lm(weight ~ water + food, data = hog_df))\n\n  # Store the results of the lm\n  hog_results <- bind_rows(\n    hog_results,\n    tibble(\n      rsq = rsq,\n      observed_rsq = cor(water, food)^2,\n      water_estimate = lm_hogs_both$coefficients[\"water\", \"Estimate\"],\n      water_se = lm_hogs_both$coefficients[\"water\", \"Std. Error\"],\n      water_p = lm_hogs_both$coefficients[\"water\", \"Pr(>|t|)\"],\n      food_estimate = lm_hogs_both$coefficients[\"food\", \"Estimate\"],\n      food_se = lm_hogs_both$coefficients[\"food\", \"Std. Error\"],\n      food_p = lm_hogs_both$coefficients[\"food\", \"Pr(>|t|)\"],\n      model_rsq = lm_hogs_both$r.squared\n    )\n  )\n}\n```\n:::\n\n\nNow we can convert the data frame to long format, to make plotting easier.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhog_results_long <- hog_results |>\n  pivot_longer(\n    cols = c(\n      water_estimate, water_se, water_p,\n      food_estimate, food_se, food_p\n    ),\n    names_to = c(\"predictor\", \"statistic\"),\n    names_sep = \"_\",\n    values_to = \"value\"\n  )\n```\n:::\n\n\nWe can then plot the following at each $R^2$:\n\n* The `estimate` - the estimated slope for each explanatory variable: the expected change in the response variable associated with a one-unit increase in that explanatory variable, holding the other explanatory variables constant.\n* The `p-value`\n* The standard error\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hog_results_long, aes(x = rsq, y = value, color = predictor)) +\n  geom_point() +\n  geom_line() +\n  facet_wrap(~statistic, scale = \"free_y\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](04-04_hypothesis_testing_3_files/figure-html/plot_results_hogs-1.png){width=576}\n:::\n:::\n\n\nIt is very clear from these plots that at high values of \\(R^2\\), the coefficient estimates become less stable and their standard errors increase. As a result, the test statistics tend to become smaller and the p-values larger, making it more difficult to detect the individual associations of food and water intake with hedgehog weight.\n\nThis doesn't mean the model is useless, and we can see this if we plot the model $R^2$ - the total proportion of variance explained by the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hog_results, aes(x = rsq, y = model_rsq)) +\n  geom_point() +\n  geom_line() +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](04-04_hypothesis_testing_3_files/figure-html/plot_r2_hogs-1.png){width=672}\n:::\n:::\n\n\nEven when the explanatory variables are highly correlated, the model as a whole can still explain a large proportion of the variation in hedgehog weight. Multicollinearity mainly makes it difficult to estimate and interpret the individual coefficients reliably.\n\n:::\n\n## Chi-squared {#sec-chi_squared}\n\nChi-squared looks for an association between two categorical variables. Unlike all the other tests we've covered so far, it is not based on a linear model.\n\nFor a chi-squared we typically report:\n* $X^2$ test statistic\n* Degrees of freedom\n* p-value\n\n### Hypotheses\n\nIn our pollinator data set, let's investigate the following hypothesis:\n\n* Alternative: There is an association between land cover (agricultural or semi-natural, all of our sites are in one of these two categories) and UK country (England, Scotland or Wales, this dataset doesn't cover Northern Ireland) amongst the sites in the POMS dataset.\n* Null: There is no association between land cover and UK country amongst the sites in the POMS dataset.\n\n### Plot\n\nFor chi-squared, we need to count the number of observations with each combination of variables. We can do this using the `count()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncountry_habitat_counts <- site_metadata |>\n  count(land_cover, country)\n\ngt(country_habitat_counts)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vvtwvzmeko\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vvtwvzmeko table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vvtwvzmeko thead, #vvtwvzmeko tbody, #vvtwvzmeko tfoot, #vvtwvzmeko tr, #vvtwvzmeko td, #vvtwvzmeko th {\n  border-style: none;\n}\n\n#vvtwvzmeko p {\n  margin: 0;\n  padding: 0;\n}\n\n#vvtwvzmeko .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vvtwvzmeko .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vvtwvzmeko .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vvtwvzmeko .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vvtwvzmeko .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vvtwvzmeko .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vvtwvzmeko .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vvtwvzmeko .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vvtwvzmeko .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vvtwvzmeko .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vvtwvzmeko .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vvtwvzmeko .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vvtwvzmeko .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vvtwvzmeko .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vvtwvzmeko .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vvtwvzmeko .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vvtwvzmeko .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vvtwvzmeko .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vvtwvzmeko .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vvtwvzmeko .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vvtwvzmeko .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vvtwvzmeko .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vvtwvzmeko .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vvtwvzmeko .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vvtwvzmeko .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vvtwvzmeko .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vvtwvzmeko .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vvtwvzmeko .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vvtwvzmeko .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vvtwvzmeko .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vvtwvzmeko .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vvtwvzmeko .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vvtwvzmeko .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vvtwvzmeko .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vvtwvzmeko .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vvtwvzmeko .gt_left {\n  text-align: left;\n}\n\n#vvtwvzmeko .gt_center {\n  text-align: center;\n}\n\n#vvtwvzmeko .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vvtwvzmeko .gt_font_normal {\n  font-weight: normal;\n}\n\n#vvtwvzmeko .gt_font_bold {\n  font-weight: bold;\n}\n\n#vvtwvzmeko .gt_font_italic {\n  font-style: italic;\n}\n\n#vvtwvzmeko .gt_super {\n  font-size: 65%;\n}\n\n#vvtwvzmeko .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vvtwvzmeko .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vvtwvzmeko .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vvtwvzmeko .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vvtwvzmeko .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vvtwvzmeko .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vvtwvzmeko .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vvtwvzmeko .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vvtwvzmeko div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"land_cover\">land_cover</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"country\">country</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"land_cover\" class=\"gt_row gt_left\">agricultural</td>\n<td headers=\"country\" class=\"gt_row gt_left\">England</td>\n<td headers=\"n\" class=\"gt_row gt_right\">30</td></tr>\n    <tr><td headers=\"land_cover\" class=\"gt_row gt_left\">agricultural</td>\n<td headers=\"country\" class=\"gt_row gt_left\">Scotland</td>\n<td headers=\"n\" class=\"gt_row gt_right\">6</td></tr>\n    <tr><td headers=\"land_cover\" class=\"gt_row gt_left\">agricultural</td>\n<td headers=\"country\" class=\"gt_row gt_left\">Wales</td>\n<td headers=\"n\" class=\"gt_row gt_right\">9</td></tr>\n    <tr><td headers=\"land_cover\" class=\"gt_row gt_left\">semi-natural</td>\n<td headers=\"country\" class=\"gt_row gt_left\">England</td>\n<td headers=\"n\" class=\"gt_row gt_right\">6</td></tr>\n    <tr><td headers=\"land_cover\" class=\"gt_row gt_left\">semi-natural</td>\n<td headers=\"country\" class=\"gt_row gt_left\">Scotland</td>\n<td headers=\"n\" class=\"gt_row gt_right\">17</td></tr>\n    <tr><td headers=\"land_cover\" class=\"gt_row gt_left\">semi-natural</td>\n<td headers=\"country\" class=\"gt_row gt_left\">Wales</td>\n<td headers=\"n\" class=\"gt_row gt_right\">8</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nA useful visualisation is a stacked bar chart, where the y axis is count, and each bar represents one categorial variable and has different coloured sections representing the other categorical variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(country_habitat_counts,\n       aes(x = country, y = n, fill=land_cover)) +\n  geom_col()\n```\n\n::: {.cell-output-display}\n![](04-04_hypothesis_testing_3_files/figure-html/bar_chart_country_habitat-1.png){width=672}\n:::\n:::\n\n### Contingency table\n\nThe input for the `chisq.test()` function is a contingency table, showing the number of observations with each combination of categories.\n\n||agricultural|semi-natural|\n|---|---|---|---|---|\n|England|count|count|\n|Scotland|count|count|\n|Wales|count|count|\n\nWe already know how to generate these counts - we have them above - but the `chisq.test()` function is a little picky about the input, so instead we will use another function, `xtabs()`, which is specifically made to use to create contingency tables.\n\n`xtabs()` uses the same formula syntax as many R stats functions, as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncont_table_country_habitat <- xtabs(\n  ~ country + land_cover,\n  data = site_metadata\n)\nprint(cont_table_country_habitat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          land_cover\ncountry    agricultural semi-natural\n  England            30            6\n  Scotland            6           17\n  Wales               9            8\n```\n\n\n:::\n:::\n\n\n### Statistical test\n\nNow we can run the chi-squared test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq_country_habitat <- chisq.test(cont_table_country_habitat)\nprint(chisq_country_habitat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  cont_table_country_habitat\nX-squared = 19.399, df = 2, p-value = 6.131e-05\n```\n\n\n:::\n:::\n\n\nThere was strong evidence of an association between country and habitat type ($\\chi^2$(2) = 19.40, $p$ = 6.13 × 10^-5^).\n\nWith the chi-squared test, we can also see the expected counts for each category - the counts we would expect if the null hypothesis were true.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(chisq_country_habitat$expected)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          land_cover\ncountry    agricultural semi-natural\n  England      21.31579    14.684211\n  Scotland     13.61842     9.381579\n  Wales        10.06579     6.934211\n```\n\n\n:::\n:::\n\n\nThe chi-squared test compares these expected counts with our observed counts. The greater the differences between the observed and expected counts, the greater the evidence against the null hypothesis.\n\n## Review {#sec-summary_0404}\n\n[↑ top](#)\n\n::: {.callout-note #note-summary_0404}\n\n### Summary\n\n\n:::\n\nFor this part of the practical, the main files you have created are:\n\nThese are the files you should select when making your Git commit.\n\n\nRemember to save and commit your work before moving on to Part 5.\n\n::: {.callout-tip}\n## Commit your changes\nRemember to save your progress regularly by committing your changes with Git.\n\n1. Save your changes to the files above in RStudio with the `Save` button.\n2. Render any Quarto documents with the `Render` button.\n3. Open the `Git` tab in RStudio.\n4. Tick the files listed above, don't worry about any others.\n5. Click `Commit` and write a short message in the `Commit message` describing your changes, something like e.g. \"Practical 1 part 1\" is sufficient, then click `Commit`. Close the `Commit` popup.\n\n:::\n\t\n\n",
    "supporting": [
      "04-04_hypothesis_testing_3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}