---
title: "04-04_hypothesis_testing_exercises"
format: html
---

Here is a reminder of some statistical tests and the data types they are appropriate for.

| Response variable | Explanatory variable | Statistical test |
|---|---|---|
| Continuous | Categorical, 2 groups | Two-sample t-test or one-way ANOVA |
| Continuous | Categorical, 3+ groups | One-way ANOVA |
| Continuous | Continuous | Linear regression |
| Continuous | Multiple variables | Multiple linear regression |
| Categorical, 2 outcomes | Continuous and/or categorical variables | Binomial GLM (logistic regression) |
| Count | Continuous and/or categorical variables | Poisson GLM |
| Categorical | Categorical | Chi-squared test |

Now we are ready to answer some questions using hypothesis testing and our data frames.

::: {.callout-exercise #ex-}

In your `pollinators.qmd` Quarto file, using the appropriate statistical test, investigate at least three of the following questions. Try to choose questions requiring different tests.

Where appropriate, show relevant plots to support your conclusions. For this exercise, you can assume that the underlying assumptions of the appropriate model have been met.


