---
format: html
practical: Glossary
doc-id: "Glossary"
page-layout: full
---


```{r libraries_funcs, include=FALSE, message=FALSE}
library(gt)
library(tidyverse)

format_gt_df <- function(df) {

  gt(df) |>
    text_transform(
      locations = cells_body(
        columns = c(Name, Usage)
      ),
      fn = function(x) paste0("<code>", x, "</code>")
    ) |>
    fmt_url(
      columns = Help,
      label = "Help"
    ) |>
    fmt_url(
      columns = Section,
      label = "Section"
    ) |>
    cols_width(
      Name ~ pct(15),
      Package ~ pct(7),
      Section ~ pct(8),
      Description ~ pct(31),
      Usage ~ pct(15),
      Help ~ pct(6)
    ) |>
    tab_options(
      table.width = pct(100),
      container.width = pct(100),
      data_row.padding = px(4),
      column_labels.padding = px(5),
      table.font.size = px(15)
    ) |>
    opt_css(
      "
      .gt_table {
        width: 100% !important;
        table-layout: fixed !important;
      }

      .gt_table td {
        vertical-align: top;
        line-height: 1.2;
        white-space: normal;
        overflow-wrap: break-word;
        word-break: normal;
      }

      .gt_table code {
        white-space: normal;
        overflow-wrap: break-word;
        word-break: normal;
        line-height: 1.1;
      }
      "
    )
}
```

# R Reference

```{r read_function_csv, include=FALSE, message=FALSE}
funcs <- read_csv("R_glossary.csv")
```

## Language and Syntax

```{r language_syntax_glos, echo=FALSE}
subsec <- funcs |>
  filter(Subset == 'Language and syntax') |>
  select(!Subset)
format_gt_df(subsec)
```

## Basic R functions

```{r basic_functions_glos, echo=FALSE}
subsec <- funcs |>
  filter(Subset == 'Basic R functions') |>
  select(!Subset)
format_gt_df(subsec)
```

## Mathematical and summary functions

```{r mathematical_glos, echo=FALSE}
subsec <- funcs |>
  filter(Subset == 'Mathematical and summary functions') |>
  select(!Subset)
format_gt_df(subsec)
```

## Importing and exporting data

```{r import_export_glos, echo=FALSE}
subsec <- funcs |>
  filter(Subset == 'Import and export') |>
  select(!Subset)
format_gt_df(subsec)
```

## Data frames

```{r data_frames_glos, echo=FALSE}
subsec <- funcs |>
  filter(Subset == 'Data manipulation') |>
  select(!Subset)
format_gt_df(subsec)
```

## Plotting

```{r plotting_glos, echo=FALSE}
subsec <- funcs |>
  filter(Subset == 'Plotting') |>
  select(!Subset)
format_gt_df(subsec)
```

## Probability distributions

```{r prob_distributions_glos, echo=FALSE}
subsec <- funcs |>
  filter(Subset == 'Probability distributions') |>
  select(!Subset)
format_gt_df(subsec)
```

## Bioinformatics

```{r bioinformatics_glos, echo=FALSE}
subsec <- funcs |>
  filter(Subset == 'Bioinformatics') |>
  select(!Subset)
format_gt_df(subsec)
```

## Miscellaneous

```{r misc_glos, echo=FALSE}
subsec <- funcs |>
  filter(Subset == 'Miscellaneous') |>
  select(!Subset)
format_gt_df(subsec)
```
