{
  "hash": "15e7850c2217622872def342694c4fe2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"04-01_temp\"\nformat: html\n---\n\n\nIn the **Samples** CSV file - `data/ukpoms_1kmpantrapdata_2017-2021_samples.csv`, each row represents one sample, in which there can be any number of observations, including zero. The data frame contains information about the geographical location, land use and climate at the sample site, the date the sample was taken and the number of observations of various types of insects in that specific sample.\n\nIn the **Insects** CSV file - `data/ukpoms_1kmpantrapdata_2017-2021_insects.csv`, each row represents one  observation of a specific species of hoverfly, bee or wasp pollinator, from a specific sample. \n\n\n\n::: {.callout-exercise #ex_summarise_bees}\nIn your `insects.qmd` Quarto file:\n\n* Read the insect and sample CSV files.\n* Count how many samples and how many observations there are.\n* Count how many unique insect species were observed - the species name is in the `taxon_source` column.\n* Find the insect species which was observed most frequently and how many times it was observed.\n* Find the ID of the sample with the highest total number of observations - this corresponds to how many times the `sample_id` is seen in the Insects data frame.\n* Count how many samples in the Samples table have a `sample_id` not found in the Insects table - these represent samples with no observations. Remember that the operator `%in%` can be used with `filter()` on a data frame column (see @sec-divide) to keep only values found in a vector.  \n\n::: {.callout-note #note-count}\n\nThe data frame function `count()` will count the number of occurrences of each value in a data frame column. Adding the argument `sort = TRUE` sorts the data frame, with the highest number first\n\nFor example, if we wanted to count the number of times each taxonomic **order** of bees and hoverflies - Diptera (flies) or Hymenoptera (bees and wasps) occurs in the Insects data frame, we would do the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\norder_counts <- insects |> count(order, sort=TRUE)\ngt(order_counts)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"mtomqtqdls\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mtomqtqdls table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mtomqtqdls thead, #mtomqtqdls tbody, #mtomqtqdls tfoot, #mtomqtqdls tr, #mtomqtqdls td, #mtomqtqdls th {\n  border-style: none;\n}\n\n#mtomqtqdls p {\n  margin: 0;\n  padding: 0;\n}\n\n#mtomqtqdls .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mtomqtqdls .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mtomqtqdls .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mtomqtqdls .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mtomqtqdls .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mtomqtqdls .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mtomqtqdls .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mtomqtqdls .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mtomqtqdls .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mtomqtqdls .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mtomqtqdls .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mtomqtqdls .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mtomqtqdls .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mtomqtqdls .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mtomqtqdls .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mtomqtqdls .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mtomqtqdls .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mtomqtqdls .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mtomqtqdls .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mtomqtqdls .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mtomqtqdls .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mtomqtqdls .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mtomqtqdls .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mtomqtqdls .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mtomqtqdls .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mtomqtqdls .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mtomqtqdls .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mtomqtqdls .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mtomqtqdls .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mtomqtqdls .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mtomqtqdls .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mtomqtqdls .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mtomqtqdls .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mtomqtqdls .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mtomqtqdls .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mtomqtqdls .gt_left {\n  text-align: left;\n}\n\n#mtomqtqdls .gt_center {\n  text-align: center;\n}\n\n#mtomqtqdls .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mtomqtqdls .gt_font_normal {\n  font-weight: normal;\n}\n\n#mtomqtqdls .gt_font_bold {\n  font-weight: bold;\n}\n\n#mtomqtqdls .gt_font_italic {\n  font-style: italic;\n}\n\n#mtomqtqdls .gt_super {\n  font-size: 65%;\n}\n\n#mtomqtqdls .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mtomqtqdls .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mtomqtqdls .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mtomqtqdls .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mtomqtqdls .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mtomqtqdls .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mtomqtqdls .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mtomqtqdls .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mtomqtqdls div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"order\">order</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"order\" class=\"gt_row gt_left\">Diptera</td>\n<td headers=\"n\" class=\"gt_row gt_right\">8838</td></tr>\n    <tr><td headers=\"order\" class=\"gt_row gt_left\">Hymenoptera</td>\n<td headers=\"n\" class=\"gt_row gt_right\">7330</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n\n\n\n::: {.callout-answer #ex_summarise_bees_ans}\n\n[Read the insect and sample CSV files]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsamples <- read_csv(\"data/ukpoms_1kmpantrapdata_2017-2021_samples.csv\")\ninsects <- read_csv(\"data/ukpoms_1kmpantrapdata_2017-2021_insects.csv\")\n```\n:::\n\n\n[Count how many samples and how many observations there are.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_count <- nrow(samples)\ninsect_count <- sum(pull(insects, count))\n\nprint(paste(\"Samples\", sample_count))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Samples 4186\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(paste(\"Insects\", insect_count))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Insects 16168\"\n```\n\n\n:::\n:::\n\nThere are 4186 samples and 1.6168\\times 10^{4} observations.\n\n[Count how many unique insect species were observed - the species name is in the `taxon_source` column.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique_insects <- insects |> \n  distinct(taxon_source)\n\nn_unique_insects <- nrow(unique_insects)\n\nprint (n_unique_insects)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 312\n```\n\n\n:::\n:::\n\nThere are 312 unique insect species.\n\n[Find the insect species which was observed most frequently and how many times it was observed.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsect_counts <- insects |> \n  count(taxon_source, sort=TRUE)\ngt(head(insect_counts))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hngsspmnyv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hngsspmnyv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hngsspmnyv thead, #hngsspmnyv tbody, #hngsspmnyv tfoot, #hngsspmnyv tr, #hngsspmnyv td, #hngsspmnyv th {\n  border-style: none;\n}\n\n#hngsspmnyv p {\n  margin: 0;\n  padding: 0;\n}\n\n#hngsspmnyv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hngsspmnyv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hngsspmnyv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hngsspmnyv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hngsspmnyv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hngsspmnyv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hngsspmnyv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hngsspmnyv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hngsspmnyv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hngsspmnyv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hngsspmnyv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hngsspmnyv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hngsspmnyv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hngsspmnyv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hngsspmnyv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hngsspmnyv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hngsspmnyv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hngsspmnyv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hngsspmnyv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hngsspmnyv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hngsspmnyv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hngsspmnyv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hngsspmnyv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hngsspmnyv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hngsspmnyv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hngsspmnyv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hngsspmnyv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hngsspmnyv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hngsspmnyv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hngsspmnyv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hngsspmnyv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hngsspmnyv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hngsspmnyv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hngsspmnyv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hngsspmnyv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hngsspmnyv .gt_left {\n  text-align: left;\n}\n\n#hngsspmnyv .gt_center {\n  text-align: center;\n}\n\n#hngsspmnyv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hngsspmnyv .gt_font_normal {\n  font-weight: normal;\n}\n\n#hngsspmnyv .gt_font_bold {\n  font-weight: bold;\n}\n\n#hngsspmnyv .gt_font_italic {\n  font-style: italic;\n}\n\n#hngsspmnyv .gt_super {\n  font-size: 65%;\n}\n\n#hngsspmnyv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hngsspmnyv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hngsspmnyv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hngsspmnyv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hngsspmnyv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hngsspmnyv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hngsspmnyv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hngsspmnyv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hngsspmnyv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"taxon_source\">taxon_source</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"taxon_source\" class=\"gt_row gt_left\">Episyrphus balteatus</td>\n<td headers=\"n\" class=\"gt_row gt_right\">1065</td></tr>\n    <tr><td headers=\"taxon_source\" class=\"gt_row gt_left\">Apis mellifera</td>\n<td headers=\"n\" class=\"gt_row gt_right\">744</td></tr>\n    <tr><td headers=\"taxon_source\" class=\"gt_row gt_left\">Syrphus ribesii</td>\n<td headers=\"n\" class=\"gt_row gt_right\">667</td></tr>\n    <tr><td headers=\"taxon_source\" class=\"gt_row gt_left\">Helophilus pendulus</td>\n<td headers=\"n\" class=\"gt_row gt_right\">626</td></tr>\n    <tr><td headers=\"taxon_source\" class=\"gt_row gt_left\">Bombus lucorum/terrestris/magnus/cryptarum</td>\n<td headers=\"n\" class=\"gt_row gt_right\">525</td></tr>\n    <tr><td headers=\"taxon_source\" class=\"gt_row gt_left\">Melanostoma mellinum</td>\n<td headers=\"n\" class=\"gt_row gt_right\">519</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThe most commonly observed species was Episyrphus balteatus, which was observed 1065 times.\n\n[Find the ID of the sample with the highest total number of observations - this corresponds to how many times the `sample_id` is seen in the Insects data frame.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_counts <- insects |> \n  count(sample_id, sort=TRUE)\ngt(head(sample_counts))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"iphjppnvsr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#iphjppnvsr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#iphjppnvsr thead, #iphjppnvsr tbody, #iphjppnvsr tfoot, #iphjppnvsr tr, #iphjppnvsr td, #iphjppnvsr th {\n  border-style: none;\n}\n\n#iphjppnvsr p {\n  margin: 0;\n  padding: 0;\n}\n\n#iphjppnvsr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#iphjppnvsr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#iphjppnvsr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#iphjppnvsr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#iphjppnvsr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iphjppnvsr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iphjppnvsr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iphjppnvsr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#iphjppnvsr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#iphjppnvsr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#iphjppnvsr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#iphjppnvsr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#iphjppnvsr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#iphjppnvsr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#iphjppnvsr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#iphjppnvsr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#iphjppnvsr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#iphjppnvsr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#iphjppnvsr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iphjppnvsr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#iphjppnvsr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#iphjppnvsr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#iphjppnvsr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iphjppnvsr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#iphjppnvsr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#iphjppnvsr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iphjppnvsr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iphjppnvsr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#iphjppnvsr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iphjppnvsr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#iphjppnvsr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iphjppnvsr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iphjppnvsr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iphjppnvsr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iphjppnvsr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iphjppnvsr .gt_left {\n  text-align: left;\n}\n\n#iphjppnvsr .gt_center {\n  text-align: center;\n}\n\n#iphjppnvsr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#iphjppnvsr .gt_font_normal {\n  font-weight: normal;\n}\n\n#iphjppnvsr .gt_font_bold {\n  font-weight: bold;\n}\n\n#iphjppnvsr .gt_font_italic {\n  font-style: italic;\n}\n\n#iphjppnvsr .gt_super {\n  font-size: 65%;\n}\n\n#iphjppnvsr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#iphjppnvsr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#iphjppnvsr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#iphjppnvsr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#iphjppnvsr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#iphjppnvsr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#iphjppnvsr .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#iphjppnvsr .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#iphjppnvsr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sample_id\">sample_id</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"sample_id\" class=\"gt_row gt_right\">3888496</td>\n<td headers=\"n\" class=\"gt_row gt_right\">108</td></tr>\n    <tr><td headers=\"sample_id\" class=\"gt_row gt_right\">4014266</td>\n<td headers=\"n\" class=\"gt_row gt_right\">85</td></tr>\n    <tr><td headers=\"sample_id\" class=\"gt_row gt_right\">6439061</td>\n<td headers=\"n\" class=\"gt_row gt_right\">85</td></tr>\n    <tr><td headers=\"sample_id\" class=\"gt_row gt_right\">18662551</td>\n<td headers=\"n\" class=\"gt_row gt_right\">76</td></tr>\n    <tr><td headers=\"sample_id\" class=\"gt_row gt_right\">4014364</td>\n<td headers=\"n\" class=\"gt_row gt_right\">73</td></tr>\n    <tr><td headers=\"sample_id\" class=\"gt_row gt_right\">18662589</td>\n<td headers=\"n\" class=\"gt_row gt_right\">69</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\nThe sample with the most observations was 3.888496\\times 10^{6}, with 108 observations.\n\n[Count how many samples in the Samples table have a `sample_id` not found in the Insects table - these represent samples with no observations. Remember that the operator `%in%` can be used with `filter()` on a data frame column (see @sec-divide) to keep only values found in a vector.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsect_sample_ids <- insects |> \n  distinct(sample_id) |>\n  pull(sample_id)\n\nsamples_in_insects <- samples |>\n  filter(sample_id %in% insect_sample_ids)\n\nsamples_not_in_insects <- nrow(samples) - nrow(samples_in_insects)\nprint (samples_not_in_insects)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1174\n```\n\n\n:::\n:::\n\n1174 samples in the Samples table have no observations.\n\n:::\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}