{
  "hash": "7124ee9fe290019f962f92bcda72dc34",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: html\npractical: Practical_4_Statistics\ndoc-id: \"0403\"\nauthor: \"Katy Brown\"\n---\n\n\n\n# Part 3: ANOVA {#sec-p3_ANOVA}\n\n::: {.callout-note .partmenu #parts-0403}\n## Sections\n\n- @sec-one_way_anova\n- @sec-f_dist\n- @sec-multi_way_anova\n- @sec-interactions\n- @sec-summary_0403\n:::\n\n:::{.callout-tip .objectives}\n#### Learning objectives\nBy the end of this part of the practical you will be able to:\n:::\n\nIn the previous section, we used one-way ANOVA to look at the difference between two levels of a single explanatory variable. However, ANOVA can easily be expanded to look at multiple groups and multiple explanatory variables.\n\n## One-way ANOVA with more than two groups {#sec-one_way_anova}\n\nANOVA expands easily to take into account an explanatory variable with more than two levels (i.e. a categorical variable with three or more options).\n\nWe already know about using `response ~ explanatory` as a formula in R to investigate response as a function of explanatory variable. If you are using a data frame as the input to this function and the explanatory variable is categorical, R will automatically treat the different values in the column as different levels of that variable.\n\nOne of the measurements in our pollinator data frame is `mean_insect_mass` - the mean mass in grams of all pollinators collected at that site. \n\nIt seems feasible that this would be affected by the types of pollinators present - some pollinators are much bigger than others. \n\n### Hypothesis\n\nUsing our pollinator data, let's investigate the following hypothesis using a one-way ANOVA.\n\n* Null hypothesis: Sites dominated by different insect families have the same mean mass.\n* Alternative hypothesis: At least one dominant insect family is associated with sites with a different mean mass.\n\nLet's first list all the families which dominate at any site.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique_fams <- site_metadata |> distinct(dominant_family)\nprint(unique_fams)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 1\n  dominant_family\n  <chr>          \n1 Syrphidae      \n2 Halictidae     \n3 Apidae         \n4 Andrenidae     \n```\n\n\n:::\n:::\n\n\nAll sites are dominated by one of these four families.\n\n### Plot\n\nA box plot is a typical way to visualise the type of data which is suitable for ANOVA analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  site_metadata,\n  aes(\n    x = dominant_family, y = mean_insect_mass,\n    fill = dominant_family\n  )\n) +\n  geom_boxplot() +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](04-03_hypothesis_testing_2_files/figure-html/plot_domfam-1.png){width=672}\n:::\n:::\n\n\n### Statistical Test\n\nWe can test the association between mean insect mass and dominant family with a one-way ANOVA, and we define it exactly as before.\n\nHere, we would define the linear model as `lm(mean_insect_mass ~ dominant_family, data=site_metadata)`.\n\nWe could then just look at our linear model directly. It would take one category - in this case Andrenidae, as it is first alphabetically, to be the reference level and compare each of the other levels - Syrphidae, Halictidae and Apidae to Andrenidae. It would not compare e.g. Halictidae to Apidae as neither is the reference.\n\nLet's try it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_mass_domfam <- lm(mean_insect_mass ~ dominant_family, data = site_metadata)\nsummary(lm_mass_domfam)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean_insect_mass ~ dominant_family, data = site_metadata)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-17.5991  -5.3988  -0.5006   3.8201  20.9558 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)  \n(Intercept)                 19.589      8.325   2.353   0.0214 *\ndominant_familyApidae       16.058      8.446   1.901   0.0613 .\ndominant_familyHalictidae   -1.674      8.830  -0.190   0.8502  \ndominant_familySyrphidae     5.571      8.450   0.659   0.5118  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.325 on 72 degrees of freedom\nMultiple R-squared:  0.3801,\tAdjusted R-squared:  0.3543 \nF-statistic: 14.72 on 3 and 72 DF,  p-value: 1.435e-07\n```\n\n\n:::\n:::\n\n\nThis tells us:\n\n* There is no evidence that sites with Apidae as the dominant family differ from those with Andrenidae as their dominant family in mean insect mass.\n* There is no evidence that sites with Halictidae as the dominant family differ from those with Andrenidae as their dominant family in mean insect mass.\n* There is no evidence that sites with Syrphidae as the dominant family differ from those with Andrenidae as their dominant family in mean insect mass.\n\nBut, this probably isn't what we want to know - we still don't know if all four means are equal.\n\nIf we perform an ANOVA on this data, it will compare a model in which sites with all four dominant pollinator families have the same mean insect mass with a model in which the sites with different dominant pollinator families are allowed to have different means. \n\n\n:::{.callout-exercise #ex-anova_domfam}\n\nIn your `pollinators.qmd` markdown file, perform an ANOVA on the linear model defined above, to investigate the hypothesis that at least one dominant insect family is associated with sites with a different mean mass. Draw a conclusion based on the output, including the appropriate statistical evidence to support your conclusion.\n\n:::{.callout-answer collapse=\"true\" #ex-anova_domfam_ans}\n\n### Statistical Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_mass_domfam <- anova(lm_mass_domfam)\nprint(anova_mass_domfam)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: mean_insect_mass\n                Df Sum Sq Mean Sq F value    Pr(>F)    \ndominant_family  3 3060.2  1020.1  14.719 1.435e-07 ***\nResiduals       72 4989.8    69.3                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n### Conclusion\n\n\n\n:::{.highlight-box}\n\nThere is evidence that mean insect mass differs among dominant insect families ($F$(3, 72) = 14.72, $p$ = 0.00000014), $R^2$ = 0.38). Dominant insect family explains approximately 38% of the variation in mean insect mass among sites.\n\n:::\n:::\n:::\n\n## Extension exercise - the F-distribution {#sec-f_dist}\n\n::: {.callout-note .extension #ext-f_distribution}\n\n\nI stated above that *\"The p-value here is obtained from an F distribution specified by two degrees-of-freedom values: the numerator and denominator degrees of freedom. The numerator degrees of freedom are associated with the explanatory variable. The denominator degrees of freedom are the residual degrees of freedom.\"*. In this case, our numerator has three degrees of freedom and our denominator has 72. \n\nIn your `pollinators.qmd` Quarto file:\n\n* Simulate a sample of 1000 observations from F-distribution with 3 numerator degrees of freedom and 72 denominator degrees of freedom. You can draw a random sample from an F-distribution with the function `rf` with the arguments `n` - number of observations, `df1` numerator degrees of freedom and `df2` denominator degrees of freedom.\n* Create a dataframe where this set of observations forms a column.\n* Plot the results using the ggplot layer `geom_density()`.\n* Calculate an approximate p-value using your simulated data — the proportion of simulated F-values which are greater than or equal to the F-statistic calculated from our data (14.72). You can extract the F-statistic from the ANOVA table using `anova_mass_domfam[\"dominant_family\", \"F value\"]`, changing `anova_mass_domfam` to whichever variable name you used.\n* Calculate the exact p-value using the F-distribution cumulative probability function `pf()`. \n\n:::{.callout-answer collapse=\"true\" #ex_f_distribution_ans}\n\n[Simulate a sample of 1000 observations from F-distribution with 3 numerator degrees of freedom and 72 denominator degrees of freedom. You can draw a random sample from an F-distribution with the function `rf` with the arguments `n` - number of observations, `df1` numerator degrees of freedom and `df2` denominator degrees of freedom.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_3_72 <- rf(1000, df1 = 3, df2 = 72)\n```\n:::\n\n\n[Create a dataframe where this set of observations forms a column.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nf_dist <- tibble(simulated = df_3_72)\n```\n:::\n\n\n[Plot the results using the ggplot layer `geom_density()`.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfstat <- anova_mass_domfam[\"dominant_family\", \"F value\"]\n\nggplot(\n  f_dist,\n  aes(x = simulated)\n) +\n  geom_density() +\n  geom_vline(xintercept = fstat, color = \"red\")\n```\n\n::: {.cell-output-display}\n![](04-03_hypothesis_testing_2_files/figure-html/f_dist_ans3-1.png){width=672}\n:::\n:::\n\n\n[Calculate an approximate p-value using your simulated data — the proportion of simulated F-values which are greater than or equal to the F-statistic calculated from our data (14.72).]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_above_sim <- sum(f_dist$simulated >= fstat)\n\np_sim <- p_above_sim / nrow(f_dist)\n\nprint(p_sim)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nAs for the t-test previously, with 1000 simulations and such a low p-value, your value will almost certainly be zero. \n\n[Calculate the exact p-value using the F-distribution cumulative probability function `pf()`.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_below <- pf(fstat, 3, 72)\np_exact <- 1 - p_below\nprint(p_exact)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.434646e-07\n```\n\n\n:::\n:::\n\nThis should be the exact p-value calculated in our ANOVA.\n:::\n:::\n\n\n## Multi-way ANOVA {#sec-multi_way_anova}\n\nANOVA can also be extended to include multiple categorical explanatory variables. This is called multi-way ANOVA (or factorial ANOVA). A model with two categorical explanatory variables is a two-way ANOVA, one with three is a three-way ANOVA, and so on.\n\nWe can add additional explanatory variables using `+` - `response ~ explanatory1 + explanatory2 + explanatory3` etc.\n\nThe ANOVA tests whether each explanatory variable is associated with the response in turn. So, in the case above, explanatory1 would be tested first, followed by whether explanatory2 explains additional variation after explanatory1 has been included, and so forth.\n\n### Hypothesis\n\nUsing our pollinator data, let's investigate the following hypotheses:\n\nDominant insect family:\n\n* Null hypothesis: mean insect mass is the same at sites dominated by different insect families\n* Alternative hypothesis: mean insect mass differs for at least one dominant insect family.\n\nBroad habitat type:\n\n* Null hypothesis: after taking dominant insect family into account, mean insect mass is the same across different broad habitat types.\n* Alternative hypothesis: after taking dominant insect family into account, mean insect mass differs for at least one broad habitat type.\n\n### Plot\n\nA box plot is again a typical visualisation to use here, this time using `facet_wrap()` to separate our different variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Take the relevant columns from the data frame\ndomfam_habitat_sel <- site_metadata |>\n  select(x1km_square, dominant_family, broad_habitat, mean_insect_mass)\n\n# Pivot to long format\ndomfam_habitat_long <- domfam_habitat_sel |>\n  pivot_longer(\n    c(\n      dominant_family,\n      broad_habitat\n    ),\n    names_to = \"variable\",\n    values_to = \"value\"\n  )\n\n# Plot the boxplot\nggplot(\n  domfam_habitat_long,\n  aes(x = value, y = mean_insect_mass, fill = variable)\n) +\n  geom_boxplot() +\n  facet_wrap(~variable, scales = \"free_x\") +\n  theme_bw() +\n  theme(axis.text.x = element_text(angle = 90, hjust = 1)) # rotate x labels so they fit\n```\n\n::: {.cell-output-display}\n![](04-03_hypothesis_testing_2_files/figure-html/plot_domfam_habitat-1.png){width=576}\n:::\n:::\n\n\n::: {.callout-exercise #ex-anova_twoway}\n\nIn your `pollinators.qmd` Quarto file:\n\n* Expand the linear model above to incorporate a second explanatory variable - broad habitat type (from the column `broad_habitat`) as well as `dominant_family`.\n* Run an ANOVA on the model and view the results.\n* Draw a conclusion based on your findings, including the appropriate statistical evidence to support your conclusion.\n\n::: {.callout-answer collapse=\"true\" #ex_anova_twoway_ans}\n\n### Statistical Test\n\nWe define our linear model as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_domfam_habitat_mass <- lm(mean_insect_mass ~ dominant_family + broad_habitat, data = site_metadata)\n```\n:::\n\n\nAnd then run the ANOVA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_domfam_habitat_mass <- anova(lm_domfam_habitat_mass)\nprint(anova_domfam_habitat_mass)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: mean_insect_mass\n                Df Sum Sq Mean Sq F value   Pr(>F)    \ndominant_family  3 3060.2 1020.06 14.6513 1.85e-07 ***\nbroad_habitat    4  255.5   63.87  0.9174    0.459    \nResiduals       68 4734.3   69.62                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\n### Conclusion\n\n::: {.highlight-box}\nThere is evidence that mean insect mass differs among dominant insect families ($F$(3, 68) = 14.65, $p$ = 1.85e-07). After accounting for dominant insect family, there is no evidence that broad habitat type explains additional variation in mean insect mass ($F$(4, 68) = 0.92, $p$ = 0.46).\n:::\n:::\n:::\n\n\n## Interactions {#sec-interactions}\n\nWhen we use `+` to include multiple explanatory variables, we are assuming that their relationships with the response are additive. This means that the relationship between one explanatory variable and the response is the same at every level of the other explanatory variable. So for example, the dominant insect family can be associated with a difference in mean insect mass, and habitat can be associated with a difference, and these differences can be added together.\n\nHowever, sometimes the relationship between one explanatory variable and the response depends on the value of another explanatory variable. This is called an interaction.\n\nWe can add interactions between variables using `*` - `response ~ explanatory1 * explanatory2`. The ANOVA will then test the association between each explanatory variable and the response, as well as whether there is an interaction between them.\n\nFor example, if we set up the model as `mean_insect_mass ~ dominant_family * dominant_flower_order`, we are asking:\n\n* Does mean insect mass vary between sites with different dominant insect families?\n* Does mean insect mass vary between sites with different dominant flower orders, once dominant insect family has been taken into account?\n* Does any difference in mean insect mass among dominant insect families depend on the dominant flower order?\n\nThis final question is the interaction: does the association between one explanatory variable and the response depend on the value of another explanatory variable?\n\n::: {.callout-exercise #ex-simulate_interaction}\n\nLet's simulate a dataset with an interaction, to help illustrate this concept.\n\nIn this study, there are four populations of students and the response variable is the time they took to finish their lunch, in minutes. Response time is drawn from a normal distribution with a standard deviation of 3.\n\nThere are two categorical explanatory variables:\n\n* Did they use a spoon or a fork?\n* Did they eat soup or pasta?\n\nTheir mean finishing times are as follows:\n\n* Spoon + Pasta = 8 minutes\n* Fork + Pasta = 10 minutes\n* Spoon + Soup = 11 minutes\n* Fork + Soup = 25 minutes\n\nThe hypotheses here are:\n\nUtensil:\n\n* Null: There is no association between utensil choice and finishing time.\n* Alternative: Utensil choice is associated with finishing time.\n\nFood:\n\n* Null: There is no association between food choice and finishing time, after taking into account the association with utensil choice.\n* Alternative: Food choice is associated with finishing time, after taking into account the association with utensil choice.\n\nInteraction:\n\n* Null: The association between utensil choice and finishing time does not vary depending on food choice.\n* Alternative: The association between utensil choice and finishing time varies depending on food choice.\n\nIn your `prac4_exercises.qmd` Quarto file:\n\n* Generate four simulated populations, each of 10 students, with response times normally distributed around these means and a standard deviation of 3.\n* Convert each of these into a data frame with the columns `utensil`, `food` and `time`.\n* Convert these to a single data frame using the function `bind_rows()`. You can pass any number of data frames as arguments to this function and it will return a single data frame combining all of the rows (assuming the data frames all have the same columns).\n* Fit a linear model with `time` as the response variable and `utensil`, `food` and their interaction as explanatory variables.\n* Run an ANOVA on the linear model.\n\n:::{.callout-answer #ex_simulate_interaction_ans}\n\n### Data\n\n[Generate four simulated populations, each of 10 students, with response times normally distributed around these means and a standard deviation of 3.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspoon_pasta <- rnorm(10, 8, 3)\nfork_pasta <- rnorm(10, 10, 3)\nspoon_soup <- rnorm(10, 11, 3)\nfork_soup <- rnorm(10, 25, 3)\n```\n:::\n\n\n[Convert each of these into a data frame with the columns `utensil`, `food` and `time`.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_sp <- tibble(\n  utensil = \"Spoon\",\n  food = \"Pasta\",\n  time = spoon_pasta\n)\n\ndf_fp <- tibble(\n  utensil = \"Fork\",\n  food = \"Pasta\",\n  time = fork_pasta\n)\n\ndf_ss <- tibble(\n  utensil = \"Spoon\",\n  food = \"Soup\",\n  time = spoon_soup\n)\n\ndf_fs <- tibble(\n  utensil = \"Fork\",\n  food = \"Soup\",\n  time = fork_soup\n)\n```\n:::\n\n\n[Convert these to a single data frame using the function `bind_rows()`. You can pass any number of data frames as arguments to this function and it will return a single data frame combining all of the rows (assuming the data frames all have the same columns).]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_food <- bind_rows(df_sp, df_fp, df_ss, df_fs)\n```\n:::\n\n\n### Statistical test\n\n[Fit a linear model with `time` as the response variable and `utensil`, `food` and their interaction as explanatory variables.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_lunch <- lm(time ~ utensil * food, data = df_food)\n```\n:::\n\n\n[Run an ANOVA on the linear model.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_lunch <- anova(lm_lunch)\nprint(anova_lunch)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: time\n             Df Sum Sq Mean Sq F value    Pr(>F)    \nutensil       1 580.00  580.00  51.270 2.025e-08 ***\nfood          1 755.45  755.45  66.779 1.018e-09 ***\nutensil:food  1 405.33  405.33  35.830 7.259e-07 ***\nResiduals    36 407.25   11.31                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n:::\n\n### Conclusion\n\n\n\nHere, we need to report the F-statistic, degrees of freedom and p-value for both explanatory variables and for the interaction.\n\n::: {.highlight-box}\nThere is evidence that eating time differs according to the utensil used ($F$(1, 36) = 51.27, $p$ = 2.03e-08) and according to the type of food being eaten ($F$(1, 36) = 66.78, $p$ = 1.02e-09).\n\nThere is also evidence of an interaction between utensil and food ($F$(1, 36) = 35.83, $p$ = 7.26e-07). This means that the difference in eating time between using a fork and a spoon depends on the type of food being eaten.\n:::\n\n::: {.callout-note .bonus #bon-simulate_interaction}\n\n### Bonus Exercise: Removing the interaction\n\nChange the population means so that there is no interaction between food and utensil, but both food and utensil are still associated with eating time, then re-run the ANOVA and re-interpret the results.\n\n::: {.callout-answer collapse=\"true\" #bon-simulate_interaction_ans}\n\nFor example\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate the populations\nspoon_pasta <- rnorm(10, 8, 3)\nfork_pasta <- rnorm(10, 12, 3)\nspoon_soup <- rnorm(10, 14, 3)\nfork_soup <- rnorm(10, 18, 3)\n\n# Make the data frames\ndf_sp <- tibble(\n  utensil = \"Spoon\",\n  food = \"Pasta\",\n  time = spoon_pasta\n)\n\ndf_fp <- tibble(\n  utensil = \"Fork\",\n  food = \"Pasta\",\n  time = fork_pasta\n)\n\ndf_ss <- tibble(\n  utensil = \"Spoon\",\n  food = \"Soup\",\n  time = spoon_soup\n)\n\ndf_fs <- tibble(\n  utensil = \"Fork\",\n  food = \"Soup\",\n  time = fork_soup\n)\n\n# Combine the data frames\ndf_food <- bind_rows(df_sp, df_fp, df_ss, df_fs)\n```\n:::\n\n\n### Statistical Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the linear model\nlm_lunch <- lm(time ~ utensil * food, data = df_food)\n\n# Run the ANOVA\nanova_lunch <- anova(lm_lunch)\nprint(anova_lunch)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: time\n             Df Sum Sq Mean Sq F value    Pr(>F)    \nutensil       1 183.16  183.16 26.1797 1.052e-05 ***\nfood          1 468.43  468.43 66.9523 9.869e-10 ***\nutensil:food  1  38.76   38.76  5.5395   0.02417 *  \nResiduals    36 251.87    7.00                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n### Conclusion\n\n\n\n\n::: {.highlight-box}\nThere is evidence that eating time differs according to the utensil used ($F$(1, 36) = 26.18,\n$p$ = 1.05e-05) and according to the type of food being eaten ($F$(1, 36) = 66.95, $p$ = 9.87e-10).\n\nHowever, there is no evidence of an interaction between utensil and food ($F$(1, 36) = 5.54, $p$ = 0.0242). This means there is no evidence that the difference in eating time between using a fork and a spoon depends on the type of food being eaten.\n:::\n\n:::\n:::\n:::\n\n### Hypotheses\n\nNow, let's try this with our real data. Here, our hypotheses are:\n\nDominant insect family:\n\n* Null: There is no association between mean insect mass and dominant insect family.\n* Alternative: Mean insect mass is associated with dominant insect family.\n\nDominant flower order:\n\n* Null: There is no association between mean insect mass and dominant flower order, once dominant insect family has been taken into account.\n* Alternative: Mean insect mass is associated with dominant flower order, once dominant insect family has been taken into account.\n\nInteraction:\n\n* Null: The association between dominant insect family and mean insect mass does not vary depending on dominant flower order.\n* Alternative: The association between dominant insect family and mean insect mass varies depending on dominant flower order.\n\n::: {.callout-exercise #ex-anova_interaction}\n\nIn your `pollinators.qmd` Quarto file:\n\n* Draw a box plot showing the distribution of mean insect mass by dominant family and dominant flower order. You will need to convert the data to long format and use the `facet_wrap()` function to divide it into two separate plots. For this plot there's no need to worry about the interaction.\n* Fit a linear model to test the association between dominant family, dominant flower order and mean insect mass, including the interaction between dominant family and dominant flower order.\n* Run an ANOVA on this model and view the results.\n* Draw a conclusion based on the results, including the appropriate statistical evidence to support your conclusion.\n\n::: {.callout-answer collapse=\"true\" #ex_anova_twoway_ans}\n\n### Plot\n\n[Draw a box plot showing the distribution of mean insect mass by dominant family and dominant flower order. You will need to convert the data to long format and use the `facet_wrap()` function to divide it into two separate plots. For this plot there's no need to worry about the interaction.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Take the relevant columns from the data frame\nmass_fam_sel <- site_metadata |>\n  select(\n    x1km_square, dominant_family, dominant_flower_order,\n    mean_insect_mass\n  )\n\n# Pivot to long format\nmass_fam_long <- mass_fam_sel |>\n  pivot_longer(\n    c(\n      dominant_family,\n      dominant_flower_order\n    ),\n    names_to = \"variable\",\n    values_to = \"value\"\n  )\n\n# Plot the boxplot\nggplot(\n  mass_fam_long,\n  aes(x = value, y = mean_insect_mass, fill = variable)\n) +\n  geom_boxplot() +\n  facet_wrap(~variable, scales = \"free_x\") +\n  theme_bw() +\n  theme(axis.text.x = element_text(angle = 90, hjust = 1)) # rotate x labels so they fit\n```\n\n::: {.cell-output-display}\n![](04-03_hypothesis_testing_2_files/figure-html/mass_fam_plot-1.png){width=672}\n:::\n:::\n\n\n### Statistical test\n\n[Fit a linear model to test the association between dominant family, dominant flower order and mean insect mass, including the interaction between dominant family and dominant flower order.]{.blue-text}\n\n[Run an ANOVA on this model and view the results.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the model\nmass_fam_flower_lm <- lm(mean_insect_mass ~ dominant_family * dominant_flower_order,\n  data = site_metadata\n)\n# Run the ANOVA\nmass_fam_flower_anova <- anova(mass_fam_flower_lm)\n\nprint(mass_fam_flower_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: mean_insect_mass\n                                      Df  Sum Sq Mean Sq F value    Pr(>F)    \ndominant_family                        3 3060.17 1020.06 16.4326 1.601e-07 ***\ndominant_flower_order                 10 1124.69  112.47  1.8118   0.08323 .  \ndominant_family:dominant_flower_order 13  823.43   63.34  1.0204   0.44778    \nResiduals                             49 3041.69   62.08                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n### Conclusion\n\n\n\n[Draw a conclusion based on the results, including the appropriate statistical evidence to support your conclusion.]{.blue-text}\n\n:::{.highlight-box}\n\nThere is evidence that mean insect mass differs among dominant insect families ($F$(3, 49) = 16.43,\n$p$ = 1.60e-07).\n\nAfter accounting for dominant insect family, there is no evidence that mean insect mass differs among dominant flower orders\n($F$(10, 49) = 1.81, $p$ = 0.0832).\n\nThere is also no evidence of an interaction between dominant insect family and dominant flower order ($F$(13, 49) = 1.02, $p$ = 0.4478). Therefore, there is no evidence that the difference in mean insect mass among dominant insect families depends on the dominant flower order.\n\n:::\n:::\n:::\n\n:::{.callout-exercise #ex_temp_prec}\n\nIn your `pollinators.qmd` Quarto file:\n\n* Fit a linear model to the `site_metadata` data frame with `annual_total_prec` as the response variable and `annual_mean_temp` as the explanatory variable.\n* Use the function `summary()` to view the results.\n* Draw a conclusion based on the results, including the appropriate statistical evidence to support your conclusion.\n\n::: {.callout-answer collapse=\"true\" #ex_temp_prec_ans}\n\n### Statistical test\n\n[Fit a linear model to the `site_metadata` data frame with `annual_total_prec` as the response variable and `annual_mean_temp` as the explanatory variable.]{.blue-text}\n\n[Use the function `summary()` to view the results.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_temp_prec <- lm(annual_total_prec ~ annual_mean_temp, data = site_metadata)\nsumm_lm_temp_prec <- summary(lm_temp_prec)\nprint(summ_lm_temp_prec)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = annual_total_prec ~ annual_mean_temp, data = site_metadata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-526.36 -175.89  -26.99  203.27  589.30 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       2812.95     233.08  12.069  < 2e-16 ***\nannual_mean_temp  -200.20      26.46  -7.567 8.51e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 281 on 74 degrees of freedom\nMultiple R-squared:  0.4362,\tAdjusted R-squared:  0.4286 \nF-statistic: 57.26 on 1 and 74 DF,  p-value: 8.511e-11\n```\n\n\n:::\n:::\n\n\n\n### Conclusion\n\n[Draw a conclusion based on the results, including the appropriate statistical evidence to support your conclusion.]{.blue-text}\n\n::: {.highlight-box}\n\nThere is evidence of a negative association between mean annual temperature and total annual precipitation ($t$(74) = -7.57, $p$ = 8.51e-11). For each 1°C increase in mean annual temperature, the model predicts a decrease in total annual precipitation of approximately 200.2 mm. The model explains 43.62% of the variation in total annual precipitation ($R^2$ = 0.4362).\n\n:::\n:::\n\n## Review {#sec-summary_0403}\n\n[↑ top](#)\n\n::: {.callout-note #note-summary_0403}\n\n### Summary\n\n\n:::\n\nFor this part of the practical, the main files you have created are:\n\nThese are the files you should select when making your Git commit.\n\n\nRemember to save and commit your work before moving on to Part 4.\n\n::: {.callout-tip}\n## Commit your changes\nRemember to save your progress regularly by committing your changes with Git.\n\n1. Save your changes to the files above in RStudio with the `Save` button.\n2. Render any Quarto documents with the `Render` button.\n3. Open the `Git` tab in RStudio.\n4. Tick the files listed above, don't worry about any others.\n5. Click `Commit` and write a short message in the `Commit message` describing your changes, something like e.g. \"Practical 1 part 1\" is sufficient, then click `Commit`. Close the `Commit` popup.\n\n:::\n\t\n\n",
    "supporting": [
      "04-03_hypothesis_testing_2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}