{
  "hash": "47ae94762ae8cb03067ed2c64906e8f0",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: html\npractical: Practical_3_Probability\ndoc-id: \"0307\"\ntoc-depth: 4\n---\n# Probability Problem Sheets\n\nThese are the solutions to the Probability problem sheets you completed earlier in the course, solved using simulation alone.\n\nYou are **not expected to work through all of these problems**, and they have not been assigned to different levels. They are provided as a reference to demonstrate how useful simulation can be for solving probability problems.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(Runuran)\nlibrary(DescTools)\n```\n:::\n\n\n## Problem Sheet 1\nWe will use 10,000 simulations, unless otherwise specified.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_sim <- 10000\n```\n:::\n\n\n### Question 1\n\nIn a natural habitat, grey wolves, foxes and coyotes co-exist. The current population\nis estimated to be 60 foxes, 30 coyotes and 10 wolves. If each animal is equally likely\nto be sighted first, find the probability of:\na. a coyote being sighted first\nb. a wolf being sighted first\nc. a fox being sighted second after either a coyote or a wolf has been sighted and\nthen removed from the habitat, so they can be fitted with a tracking device\n(Consider: what is the impact of the first sighting on what you see next?)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make a population with 60 foxes, 30 coyotes and 10 wolves\nanimals <- c(\n  rep(\"fox\", 60),\n  rep(\"coyote\", 30),\n  rep(\"wolf\", 10)\n)\n\n# Sample 10000 animals, with replacement\nsamps <- sample(\n  x = animals,\n  size = n_sim,\n  replace = TRUE\n)\n```\n:::\n\n\n#### a\nProbability that a coyote is sighted first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count how many samples are coyotes\nn_coy <- sum(samps == \"coyote\")\n\n# What proportion of the total samples is this?\nans <- n_coy / length(samps)\n\nprint(ans)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3078\n```\n\n\n:::\n:::\n\n\nThe probability a coyote is sighted first is 0.3078 \n\n#### b\nProbability that a wolf is sighted first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count how many samples are wolves\nn_wolves <- sum(samps == \"wolf\")\n\n# What proportion of the total samples is this?\nans <- n_wolves / length(samps)\nprint(ans)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0984\n```\n\n\n:::\n:::\n\nThe probability a wolf is sighted first is 0.0984 \n\n#### c\nProbability of a fox being sighted second after either a coyote or a wolf has been sighted and then removed from the habitat, so they can be fitted with a tracking device.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntimes_w_c_first <- 0\ntimes_f_second <- 0\n\nfirst_animal <- c()\nsecond_animal <- c()\nfor (i in seq_len(n_sim)) {\n  # Sample 2 animals from the habitat\n  # and remove each after sampling\n  samps <- sample(\n    x = animals,\n    size = 2,\n    replace = FALSE\n  )\n  # Track who was caught first\n  first_animal <- c(first_animal, samps[1])\n\n  # Track who was caught second\n  second_animal <- c(second_animal, samps[2])\n}\n\n# Vector of all the times wolf or coyote was\n# first\nw_c_first <- first_animal %in% c(\"wolf\", \"coyote\")\n\n# Vector of all the times fox was second\nfox_second <- second_animal == \"fox\"\n\n# Count how many times a wolf or coyote was\n# first\nw_c_first_count <- sum(w_c_first)\n\n# Count how many times a wolf or coyote was\n# first and a fox was second\nw_c_first_and_fox_second_count <- sum(w_c_first & fox_second)\n\n# Calculate the proportion of the times that\n# a wolf or coyote was first that a fox was\n# also second\nans <- w_c_first_and_fox_second_count / w_c_first_count\nprint(ans)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6082062\n```\n\n\n:::\n:::\n\nThe probability of a fox being sighted second after either a coyote or a wolf has been sighted and\nthen removed from the habitat 0.6082 \n\n\n### Question 2\nA transmitter emits the signals “0” or “1” in the ratio 1:2. Two independent receivers,\nlabelled R1 and R2 are set up. If, unknown to the users, receiver R1 is incorrect in 2%\nof the cases and receiver R2 is incorrect in 3% of the cases, find\n\na. the probability that R1 reports that the transmitted signal is “0”\nb. the probability that R2 reports that the transmitted signal is “1”\nc. following an incoming signal there is some confusion, because R1 reports\nsignal “0” and R2 reports signal “1”. Which of the two receivers is most likely\nto be correct?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run the transmitter 10,000 times, with a 2/3 probability of success\n# where success == 1\ntransmitter <- rbinom(n = n_sim, size = 1, prob = 2 / 3)\n\n# Run R1 10,000 times, with a 98% probability of success\n# 1 - correct\n# 0 - incorrect\nR1_correct <- rbinom(n = n_sim, size = 1, prob = 0.98)\n\n# Run R2 10,000 times, with a 97% probability of success\n# 1 - correct\n# 0 - incorrect\nR2_correct <- rbinom(n = n_sim, size = 1, prob = 0.97)\n```\n:::\n\n\n#### a\n\nThe probability that R1 reports that the transmitted signal is “0”\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# R1 reports 0 when either the signal is 0\n# and it is correct or the signal is 1\n# and it is incorrect\nzero_and_correct <- transmitter == 0 & R1_correct == 1\none_and_incorrect <- transmitter == 1 & R1_correct == 0\n\n# Find times when either of these are true\n# | = OR\nR1_output_of_zero <- zero_and_correct | one_and_incorrect\n\n# Count how many times either were true\ncount_R1_output_of_zero <- sum(R1_output_of_zero)\n\n# Convert to a proportion\nans_a <- count_R1_output_of_zero / n_sim\nprint(ans_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3455\n```\n\n\n:::\n:::\n\nThe probability that R1 reports that the transmitted signal is “0” is 0.3455\n\n#### b\n\nThe probability that R2 reports that the transmitted signal is “1”\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# R2 reports 1 when either the signal is 1\n# and it is correct or the signal is 0\n# and it is incorrect\none_and_correct <- transmitter == 1 & R2_correct == 1\nzero_and_incorrect <- transmitter == 0 & R2_correct == 0\n\n# Find times when either of these are true\nR2_output_of_one <- one_and_correct | zero_and_incorrect\n\n# Count how many times either were true\ncount_R2_output_of_one <- sum(R2_output_of_one)\nans_b <- count_R2_output_of_one / n_sim\n\nprint(ans_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6538\n```\n\n\n:::\n:::\n\nThe probability that R2 reports that the transmitted signal is “1” is 0.6538\n\n#### c\n\nc. following an incoming signal there is some confusion, because R1 reports signal “0” and R2 reports signal “1”. Which of the two receivers is most likely to be correct?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find when R1 reports 0 and R2 reports 1\nR1_0_R2_1 <- (R1_output_of_zero == 1) & (R2_output_of_one == 1)\n\n# Count how many of these times R1 reports 0 and is correct\nR1_reports_zero_correctly <- sum(R1_correct == 1 & R1_0_R2_1 == 1)\n\n# Count how many of these times R1 reports 0 and is correct\nR2_reports_one_correctly <- sum(R2_correct == 1 & R1_0_R2_1 == 1)\n\n# Calculate the proportion of times R1 is correct\nR1_correct_prop <- R1_reports_zero_correctly / sum(R1_0_R2_1 == 1)\nR2_correct_prop <- R2_reports_one_correctly / sum(R1_0_R2_1 == 1)\n\n\nprint(paste(\"R1 = \", R1_correct_prop))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"R1 =  0.373913043478261\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(paste(\"R2 = \", R2_correct_prop))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"R2 =  0.626086956521739\"\n```\n\n\n:::\n:::\n\n\nGiven that R1 has reported 0 and R2 has reported 1, R2 is more likely to be correct, with a probability of 0.6261, compared to 0.3739 for R1.\n\n### Question 3\n\n::: {.callout-important #note-choose}\nParts 3a and 3c here cannot be reliably answered using simulation, so they are omitted here.\n:::\n\nOf a batch of 22 imported oak saplings, 12 are healthy and 10 have hidden oak\nprocessionary moth eggs. A tree health officer is aware that there may be an\nissue and chooses 5 trees at random to inspect in detail. \n\nb. What is the probability that a sample of five trees, chosen at random from the\nbatch of 22 imported trees, consists of three healthy and two infested trees?\n\nd. What is the probability that a sample of five, chosen at random from the batch\nconsists only of healthy trees?\n\n#### b\n\nWhat is the probability that a sample of five trees, chosen at random from the\nbatch of 22 imported trees, consists of three healthy and two infested trees?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make a batch of 12 healthy and 10 infested trees\nhealthy <- rep(\"healthy\", 12)\neggs <- rep(\"eggs\", 10)\ncombined <- c(healthy, eggs)\n\n# Sample 5 trees 10,000 times and track how many are\n# healthy each time.\nhealthy_counts <- c()\nfor (i in seq_len(n_sim)) {\n  samp <- sample(x = combined, size = 5, replace = FALSE)\n  n_healthy <- sum(samp == \"healthy\")\n  healthy_counts <- c(healthy_counts, n_healthy)\n}\n# Count how many times 3 were healthy\ntotal_three_healthy <- sum(healthy_counts == 3)\n\n# Divide by the number of simulations\nprop <- total_three_healthy / n_sim\nprint(prop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3734\n```\n\n\n:::\n:::\n\n\nThere is a probability of 0.3734 that 3 trees are healthy and two are infested.\n\n#### d\nWhat is the probability the sample of five, chosen at random from the batch consists only of healthy trees?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use the sample from part b - 5 trees sampled 10,000\n# times, tracked how many are healthy each time.\n\n# Count how many times 5 were healthy\ntotal_five_healthy <- sum(healthy_counts == 5)\n\n# Divide by the number of simulations\nprop <- total_five_healthy / n_sim\nprint(prop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0298\n```\n\n\n:::\n:::\n\nThere is a probability of 0.0298 that all 5 trees are healthy.\n\n### Question 4\n\nA spam filter on a mail server scrutinises messages for the appearance of key words\nthat make it likely that the message is spam.\n\nThe filter works as follows:\n• it is assumed that evidence for spam is that the subject message of the email\ncontains the sentence “check this out”.\n\nAccording to some historical data we know that:\n• 40% of emails are spam\n• 1% of spam emails have “check this out” in the subject line\n• 0.4% of non-spam emails have “check this out” in the subject line.\nFind the probability that an email is spam given that it has the phrase “check this\nout” in the subject\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate 100,000 emails with a 40% chance of being spam\n# 1 = spam\n# 0 = not spam\nis_spam <- rbinom(100000, size = 1, prob = 0.4)\n\n# Count how many of these are and are not spam\nn_spam <- sum(is_spam == 1)\nn_not_spam <- 100000 - n_spam\n\n# For the results which are spam, simulate a 1% chance\n# of saying CTO\nis_cto_spam <- rbinom(n_spam, size = 1, prob = 0.01)\n\n# For the results which are not spam, simulate a 0.4% chance\n# of saying CTO\nis_cto_not_spam <- rbinom(n_not_spam, size = 1, prob = 0.004)\n\n# Calculate the total number of simulations that are CTO\ncto <- sum(is_cto_spam, is_cto_not_spam)\n\n# Calculate the proportion of CTO simulations which are spam\nprob_spam_cto <- sum(is_cto_spam) / cto\n\nprint(prob_spam_cto)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6441176\n```\n\n\n:::\n:::\n\nThe probability that an email is spam given that it has the phrase “check this out” in the subject is 0.6441\n\nNote that I used a higher number of simulations here because so few emails have \"check this out\" overall.\n\n### Question 5\n\nThe number of particles emitted from a radioactive substance follows a Poisson distribution with parameter λ=4 particles per minute. Find the probability that:\n\na. three particles are emitted in one minute\nb. at least one particle is emitted in a minute\nc. three particles are emitted in 2 minutes\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate a Poisson distributed data set with a lambda of 4\nparticles_per_min <- rpois(n_sim, 4)\n```\n:::\n\n\n#### a\nFind the probability that three particles are emitted in one minute\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# How many of the simulated data points have a count of exactly 3\nans_a <- sum(particles_per_min == 3) / n_sim\nprint(ans_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1877\n```\n\n\n:::\n:::\n\n\nThe probability that 3 particles are emitted in one minute is 0.1877.\n\n#### b\n\nFind the probability that at least one particle is emitted in a minute\n\n::: {.cell}\n\n```{.r .cell-code}\n# How many of the simulated data points have a count of at least 1\nans_b <- sum(particles_per_min >= 1) / n_sim\nprint(ans_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9801\n```\n\n\n:::\n:::\n\n\nThe probability that at least one particle is emitted in a minute is 0.9801.\n\n#### c\n\nFind the probability that 3 particles are emitted in 2 minutes\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate a Poisson distributed data set with a lambda of 8\nparticles_per_2min <- rpois(n_sim, 8)\n# How many of the simulated data points have a count of exactly 3\nans_c <- sum(particles_per_2min == 3) / n_sim\nprint(ans_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0272\n```\n\n\n:::\n:::\n\n\nThe probability that 3 particles are emitted in 2 minutes is 0.0272.\n\n### Question 6\n\na. The survival rate of a specific disease is forty percent. In a certain day eight\npatients are admitted into hospital with that disease. What are the chances\nthat three will survive?\n\nb. A new drug is discovered that can cure the disease but can only be\nadministered in a way that has a success rate of reaching the affected area of\n0.6. There usually are four doses of the drug administered. Find the chances\nof:\n  i. three doses successfully administered\n  ii. no doses successfully administered\n  iii. at least one dose successfully administered\n  iv. at most two doses successfully administered\n\n#### a\nThe survival rate of a specific disease is forty percent. In a certain day eight patients are admitted into hospital with that disease. What are the chances that three will survive?\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sample 8 individuals from a binomial distribution\n# 10,000 times with a 40% probability of survival\nsurvival <- rbinom(n_sim, 8, 0.4)\n\n# Calculate the number of simulated values which are\n# equal to 3, convert to a proportion of 10,000\nn_three <- sum(survival == 3)\nprop_three <- n_three / n_sim\n\nprint(prop_three)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.283\n```\n\n\n:::\n:::\n\n\nThe probability that three will survive is 0.283.\n\nA new drug is discovered that can cure the disease but can only be administered in a way that has a success rate of reaching the affected area of 0.6.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate giving four doses of the drug 10,000\n# times with a 0.6 probability of success\nsuccess <- rbinom(n_sim, 4, 0.6)\n```\n:::\n\n\n##### i\nThree doses successfully administered\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of times there were exactly 3 successes\nans_i <- sum(success == 3) / n_sim\nprint(ans_i)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3394\n```\n\n\n:::\n:::\n\nThe probability that three doses were successfully administered is 0.3394\n\n##### ii\nNo doses successfully administered\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of times there were exactly 0 successes\nans_ii <- sum(success == 0) / n_sim\nprint(ans_ii)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0253\n```\n\n\n:::\n:::\n\nThe probability that no doses were successfully administered is 0.0253\n\n##### iii\nAt least one dose successfully administered\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of times at least one success (i.e. not zero successes)\nans_iii <- sum(success != 0) / n_sim\nprint(ans_iii)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9747\n```\n\n\n:::\n:::\n\nThe probability that at least one dose was successfully administered is 0.9747\n\n##### iv\nAt most two doses successfully administered\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of times 2 or less successes\nans_iv <- sum(success <= 2) / n_sim\nprint(ans_iv)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5284\n```\n\n\n:::\n:::\n\nThe probability that at most two doses were successfully administered is 0.5284\n\n### Question 7\n\nA scientist randomly selects dolphins until she finds one that has been tagged with a\ntracking device, so that she can collect the data on the pod’s movements. The\nprobability that she finds the dolphin with the tracking device is 0.2.\n\na. What is the probability that the scientist must select exactly 4 dolphins before\nshe finds one with a tracking device?\n\nb. What is the probability that she must select more than 6 dolphins before she\nfinds one with a tracking device?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate a geometric distribution with 10,000 data points, with a\n# 20% probability of success in each trial.\ndolphins <- rgeom(n_sim, 0.2)\n```\n:::\n\n\n#### a\nWhat is the probability that the scientist must select exactly 4 dolphins before she finds one with a tracking device?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Probability there are 3 failures before the first success\nans_a <- sum(dolphins == 3) / n_sim\nprint(ans_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.101\n```\n\n\n:::\n:::\n\n\nThere is a 0.101 probability that she must select exactly 4 dolphins to find one with a tracking device.\n\n#### b\nb. What is the probability that she must select more than 6 dolphins before she finds one with a tracking device?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Probability there are at least 6 failures before the first success\nans_b <- sum(dolphins >= 6) / n_sim\nprint(ans_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2626\n```\n\n\n:::\n:::\n\n\nThere is a 0.2626 probability that she will have to select more than 6 dolphins before finding one with a tracking device.\n\n### Question 8\n\nThe number of results we get per minute from a simple computational model is a Poisson random variable with mean 3.\n\na. Find the probability that no results come in a given 1 minute period.\n\nb. Find the probability that at least two results will come in a given two minute period.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate a Poisson distribution with lambda 3\nresults_per_min <- rpois(n_sim, 3)\n```\n:::\n\n\n#### a\nFind the probability that no results come in a given 1 minute period.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Probability of a count of exactly 0\nans_a <- sum(results_per_min == 0) / n_sim\nprint(ans_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0499\n```\n\n\n:::\n:::\n\nThe probability no results come in a given 1 minute period is 0.0499.\n\n#### b\nThe probability that at least two results will come in a given two minute period.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate a Poisson distribution with lambda 6\nresults_per_2min <- rpois(n_sim, 6)\n# Probability of a count of at least 2\nans_b <- sum(results_per_2min >= 2) / n_sim\nprint(ans_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9827\n```\n\n\n:::\n:::\n\nThe probability at least two results will come in a given 2 minute period is 0.9827.\n\n## Problem Sheet 2\n\n### Question 1\n\nOn average, a certain spectrophotometer part lasts 10 years. The length of time that the\npart lasts is exponentially distributed.\na) What is the probability that the spectrophotometer part lasts more than 7 years?\nb) On the average, how long would 5 of these parts last if they were used one after\nanother?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Rate per year if it lasts 10 years on average\nrate <- 1 / 10\n\n# Simulate an exponential distribution with this\n# rate and 10,000 observations\ndistri <- rexp(n_sim, rate = rate)\n```\n:::\n\n\n#### a\nWhat is the probability that the spectrophotometer part lasts more than 7 years?\n\n::: {.cell}\n\n```{.r .cell-code}\n# Proportion of intervals > 7\nans_a <- sum(distri > 7) / n_sim\nprint(ans_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4923\n```\n\n\n:::\n:::\n\nThere is an 0.4923 probability the part lasts more than 7 years.\n\n#### b\nOn the average, how long would 5 of these parts last if they were used one after another?\n\n::: {.cell}\n\n```{.r .cell-code}\n# Average time based on simulation\naverage_time <- mean(distri)\n\n# Multiply by 5\ntotal_time <- average_time * 5\n\nprint(total_time)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 49.85984\n```\n\n\n:::\n:::\n\nOn average, 5 parts would last 49.8598 years.\n\n### Question 2\n\nA drug is produced in a chamber with temperature X, where X is a random variable that follows a normal distribution with μ = 21°C and σ = 5°C. If X<25°C, the production cost per unit is £20, whereas if X≥25°C the production cost per unit is £30. Find the expected production cost per unit for this drug.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate a normal distribution where μ = 21°C and σ = 5°C\ndrug_dist <- rnorm(n_sim, 21, 5)\n\n# Count how many times X is < 25\ncold <- sum(drug_dist < 25)\n\n# Count how many times X is >= 25\nhot <- sum(drug_dist >= 25)\n\n# Calculate the total cost for cold production\ncold_cost <- cold * 20\n\n# Calculate the total cost for hot production\nhot_cost <- hot * 30\n\n# Calculate the total cost for all production\ntotal_cost <- cold_cost + hot_cost\n\n# Convert to a proportion of the number of units\nans_2 <- total_cost / n_sim\n\nprint(ans_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22.073\n```\n\n\n:::\n:::\n\nThe expected production cost per unit for this drug is £22.07 per unit.\n\n### Question 3\n\nA box contains 3 green and 5 red balls. If we pick balls and then replace them, find:\na) The probability that the third time we pick a ball, we get a red ball for the second time.\nb) The probability that the 4th time we pick a ball, a red ball appears for the first time\nc) The expected number of times we pick a ball until we get a red ball for the second time.\n\n\n#### a\nThe probability that the third time we pick a ball, we get a red ball for the second time.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Draw two balls 10,000 times and count how many\n# are red\nfirst_two <- rbinom(n_sim, size = 2, prob = 5 / 8)\n\n# Draw one ball 10,000 times and count how many\n# are red\nthird <- rbinom(n_sim, size = 1, prob = 5 / 8)\n\n# How many times is either ball 1 or ball 2 red\n# but not both and ball 3 is red\ncount <- sum(first_two == 1 & third == 1)\n\n# As a proportion\nprop <- count / n_sim\n\nprint(prop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2981\n```\n\n\n:::\n:::\n\nThe probability that the third time we pick a ball, we get a red ball for the second time is 0.2981.\n\n#### b\nThe probability that the 4th time we pick a ball, a red ball appears for the first time\n\n::: {.cell}\n\n```{.r .cell-code}\n# Draw three balls 10,000 times and count how many\n# are red\nfirst_three <- rbinom(n_sim, size = 3, prob = 5 / 8)\n\n# Draw one ball 10,000 times and count how many\n# are red\nfourth <- rbinom(n_sim, size = 1, prob = 5 / 8)\n\n# How many times are none of the first three balls\n# red but ball 4 is red\ncount <- sum(first_three == 0 & fourth == 1)\n\n# As a proportion\nprop <- count / n_sim\n\nprint(prop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0326\n```\n\n\n:::\n:::\n\nThe probability that the 4th time we pick a ball, a red ball appears for the first time is 0.0326.\n\n#### c\nThe expected number of times we pick a ball until we get a red ball for the second time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate the number of green balls picked before the first red\n# twice\nball_1 <- rgeom(n_sim, 5 / 8)\nball_2 <- rgeom(n_sim, 5 / 8)\n\n# Add them together - add two for the two red balls then picked\ncombined_balls <- ball_1 + ball_2 + 2\n\n# The mean of these values is the expectation\nexpected <- mean(combined_balls)\n\nprint(expected)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.1949\n```\n\n\n:::\n:::\n\nThe expected number of times we pick a ball until we get a red ball for the second time is 3.1949.\n\n\n### Question 4\nFor a group of 100 students, find:\na) The expected number of days of the year that are birthdays of exactly 3 people.\nb) The expected number of distinct birthdays\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob_bday <- 1 / 365\n\nbdays_per_day <- rbinom(1000000, 100, prob_bday)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob_3_bdays <- sum(bdays_per_day == 3) / 1000000\n\nn_days <- 365 * prob_3_bdays\n\nprint(n_days)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9052\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop_distinct <- sum(bdays_per_day != 0) / 1000000\nn_distinct <- 365 * prop_distinct\n\nprint(n_distinct)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 87.45291\n```\n\n\n:::\n:::\n\n\n### Question 5\n\n::: {.callout-note #note-non_standard_dist}\nAnswering this question using simulation depends on the bonus material in @sec-p6_non_standard.\n:::\n\nA continuous random variable X has the following probability density function:\n$$\nf(x) =\n\\begin{cases}\n\\displaystyle\\frac{4x(9-x^2)}{81}, & \\text{if } 0 \\leq x \\leq 3 \\\\[6pt]\n0, & \\text{otherwise}\n\\end{cases}\n$$\n\na. Verify that f(x) is a valid probability density function.\nb. Find (a) the mean of f(x), (b) the mode of f(x) and (c) the median of f(x)\n\n\n#### a\n\nVerify that f(x) is a valid probability density function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the area under the curve\narea <- integrate(\n  function(x) {\n    ((4 * x) * (9 - x^2)) / 81\n  },\n  lower = 0,\n  upper = 3\n)\nprint(area)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1 with absolute error < 1.1e-14\n```\n\n\n:::\n:::\n\nThe function is non-negative over its specified range and the area under the curve is 1 so the PDF is valid.\n\n#### b\n\nFind (a) the mean of f(x), (b) the mode of f(x) and (c) the median of f(x)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make a random number generator using this function\nrand_gen <- pinv.new(\n  pdf = function(x) {\n    ((4 * x) * (9 - x^2)) / 81\n  },\n  lb = 0,\n  ub = 3\n)\n\n# Generate 10,000 random points\nsimu <- ur(rand_gen, n_sim)\n\n# Calculate the mean and median of the points\nmean_simu <- mean(simu)\nmedian_simu <- median(simu)\n\n# Mean\nprint(mean_simu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.599747\n```\n\n\n:::\n\n```{.r .cell-code}\n# Median\nprint(median_simu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.622944\n```\n\n\n:::\n:::\n\nThe simulated mean is 1.5997.\n\nThe simulated median is 1.6229.\n\nThe mode is trickier, as R doesn't by default calculate the mode for continuous data. It's easiest to do this visually based on a histogram.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert to a data frame\nsimu_df <- tibble(simulated_data = simu)\n\n# Plot a histogram\nggplot(simu_df, aes(x = simulated_data)) +\n  geom_histogram(bins = 50)\n```\n\n::: {.cell-output-display}\n![](03-07_bonus_practice_questions_files/figure-html/mode_cont-1.png){width=672}\n:::\n:::\n\nThe peak is apparent on this plot at about 1.7.\n\n### Question 6\n\n::: {.callout-note #note-non_standard_dist2}\nAnswering this question using simulation depends on the bonus material in @sec-p6_non_standard.\n:::\n\n### a\nLet X be a continuous random variable with probability density function:\n\n$$\nf(x) =\n\\begin{cases}\n4x^3, & \\text{if } 0 < x \\leq 1 \\\\\n0, & \\text{otherwise}\n\\end{cases}\n$$\n\nFind\n\n$$\nP\\left(X \\leq \\frac{2}{3} \\mid X > \\frac{1}{3}\\right).\n$$\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a random number generator for this distribution\nrand_gen <- pinv.new(\n  pdf = function(x) {\n    4 * x^3\n  },\n  lb = 0,\n  ub = 1\n)\n\n# Generate 10,000 random points\nsimu <- ur(rand_gen, n_sim)\n\n# Convert to a data frame\nrand_df <- tibble(points = simu)\n\n# Extract the points where x > 1/3\n# within this interval\nrand_df_2_3 <- rand_df |>\n  filter(\n    points <= (2 / 3),\n    points > 1 / 3\n  )\n\n# Extract the points where x > 1/3\nrand_df_1_3 <- rand_df |>\n  filter(points > (1 / 3))\n\n# Calculate the proportion of points within the interval\nprop_between <-\n  nrow(rand_df_2_3) / nrow(rand_df_1_3)\n\nprint(prop_between)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1794198\n```\n\n\n:::\n:::\n\n\n### b\n\nLet \\(X\\) be a continuous random variable with probability density function:\n\n$$\nf(x) =\n\\begin{cases}\nx^2\\left(2x+\\frac{3}{2}\\right), & \\text{if } 0 < x \\leq 1 \\\\\n0, & \\text{otherwise}\n\\end{cases}\n$$\n\nIf\n\n$$\nY = \\frac{2}{X} + 3,\n$$\n\nfind\n\n$$\n\\operatorname{Var}(Y).\n$$\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a random number generator for this function\nrand_gen <- pinv.new(\n  pdf = function(x) {\n    x^2 * (2 * x + (3 / 2))\n  },\n  lb = 0,\n  ub = 1\n)\n\n# Generate 100,000 random points\n# This one isn't very stable so use a bigger number\nsimu <- ur(rand_gen, 100000)\n\n# Calculate the Y value for each point and store it.\nsimu_y <- c()\nfor (sim_x in simu) {\n  y <- (2 / sim_x) + 3\n  simu_y <- c(simu_y, y)\n}\n\n# Find the variance of Y\nvar_y <- var(simu_y)\n\nprint(var_y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.731309\n```\n\n\n:::\n:::\n\nThe variance of Y is 1.7313.\n\nThe simulated estimate of the variance may differ noticeably from the exact answer of approximately 1.97, because values of X close to zero produce very large values of Y, making the sample variance relatively unstable.\n\n### Question 7\n\nA polar bear is hunting for food. From its current position, there are three different\nroutes. The first one brings it back to the same point after 1 hours of walking. The\nsecond route brings it back to the same point after 6 hours of walking. The last route\nleads to the food source after 2 hours of walking. Assuming that the probability the\nbear chooses route 1 is 0.25, route 2 is 0.25 and route 3 is 0.5, what is the expected\ntime it will take for the bear gets some food?\n\n::: {.callout-note #note-while_loops}\n\nThis solution uses conditional statements **if** and **else**, along with a  **while** loop - a loop which runs over and over again until something becomes true. We have not covered these programming techniques in the practicals.\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Length of each route\nroute1 <- 1\nroute2 <- 6\nroute3 <- 2\n\n# Probability of each route\nprob1 <- 0.25\nprob2 <- 0.25\nprob3 <- 0.5\n\n# Currently, the bear has no food\nfood <- FALSE\n\n# Vector to track the time taken in each simulation\ntotal_times <- c()\n\nfor (i in seq_len(n_sim)) {\n  total_time <- 0\n  food <- FALSE\n  # Keep running these steps until he finds food\n  while (!food) {\n    # Randomly, based on the probabilities above, choose a route\n    which_route <- sample(seq_len(3), 1, prob = c(prob1, prob2, prob3))\n\n    # If it is route 1, add 1 hour to the total time\n    if (which_route == 1) {\n      total_time <- total_time + route1\n    }\n    # If it is route 2, add 6 hours to the total time\n    else if (which_route == 2) {\n      total_time <- total_time + route2\n    }\n    # If it is route 3, add 2 hours to the total time\n    # then stop the loop because he has found food.\n    else if (which_route == 3) {\n      total_time <- total_time + route3\n      food <- TRUE\n    }\n  }\n  # Store the total time taken\n  total_times <- c(total_times, total_time)\n}\n# Calculate the mean of the time taken over the 10,000 simulations\nmean_total <- mean(total_times)\nprint(mean_total)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.5001\n```\n\n\n:::\n:::\n\nThe mean time for the polar bear to find food is 5.5001.\n",
    "supporting": [
      "03-07_bonus_practice_questions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}