{
  "hash": "7e9ee102f743b460e4b1215c7491ee61",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: html\npractical: Practical_3_Probability\ndoc-id: \"0305\"\n---\n\n\n\n# Part 5: Conditional Probability and Bayes' Theorem {#sec-bayes}\n\n:::{.callout-tip .objectives}\n#### Learning objectives\n\nBy the end of this part of the practical you will be able to:\n\n- Calculate conditional probabilities from observed data in R.\n- Calculate and interpret the sensitivity and specificity of a biological marker in R.\n- Use simulation to investigate conditional probability and Bayes' theorem.\n- Use simulation to estimate the probability of an outcome given observed evidence.\n- Explain how the prevalence of an outcome affects the interpretation of a marker or test result.\n\n:::\n\n## UK cervical screening data\n\nIn the UK, cervical screening is routinely offered to any individual with a cervix aged 25 to 64. This screening tests for high risk strains of human papillomavirus (HPV). Members of this group of viruses can damage cells in the cervix and cause cervical cancer. Where tests are positive for high risk HPV (hrHPV), the samples are further tested for abnormal cells and, if abnormal cells are found, additional tests for pre-cancerous cells and cervical cancer are performed.\n\nTherefore, testing for hrHPV can be considered to be a marker for abnormal cervical cells, and therefore for pre-cancerous conditions of the cervix and cervical cancer.\n\nThe following data are from [this publication](https://doi.org/10.1038/sj.bjc.6603210), published in 2006 in the British Journal of Cancer (note that this is before routine vaccination against HPV was introduced in the UK. In this study 24,510 people in the UK were screened for hrHPV and cytology was performed in all cases to detect abnormal cells. In this practical we will consider 21,843 of these people - excluding people who had borderline or mild abnormal cytology.\n\nOf these 21,843, 12.1% of people tested positive for hrHPV. 2.1% of people had moderately or severely abnormal cytology, the remainder were normal.\n\nThe number of people with and without hrHPV and with and without abnormal cytology are provided in CSV format in `data/cm_all_ages.csv`. \n\n:::{.callout-exercise #ex-confusion_matrix_all_ages}\nIn your `hpv.qmd` Quarto file, read `data/cm_all_ages.csv` into a data frame and view the contents with `gt()`.\n\nFor this first part of the exercise you do not need to use simulation, you can directly calculate the values from the data frame.\n\nCalculate:\n* The proportion of people with hrHPV who have abnormal cells.\n* The proportion without hrHPV who have abnormal cells.\n* The proportion of people with abnormal cells who have hrHPV - the sensitivity of hrHPV as a marker.\n* The proportion of people who have normal cells and don't have hrHPV - the specificity of hrHPV as a marker.\n\n:::{.callout-answer collapse=\"true\" #ex-confusion_matrix_all_ages_ans}\n\n[In your `hpv.qmd` Quarto file, read `data/cm_all_ages.csv` into a data frame and view the contents with `gt()`.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhpv_df <- read_csv(\"data/cm_all_ages.csv\")\ngt(hpv_df)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qeayjdrzqo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qeayjdrzqo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qeayjdrzqo thead, #qeayjdrzqo tbody, #qeayjdrzqo tfoot, #qeayjdrzqo tr, #qeayjdrzqo td, #qeayjdrzqo th {\n  border-style: none;\n}\n\n#qeayjdrzqo p {\n  margin: 0;\n  padding: 0;\n}\n\n#qeayjdrzqo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qeayjdrzqo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qeayjdrzqo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qeayjdrzqo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qeayjdrzqo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qeayjdrzqo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qeayjdrzqo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qeayjdrzqo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qeayjdrzqo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qeayjdrzqo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qeayjdrzqo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qeayjdrzqo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qeayjdrzqo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qeayjdrzqo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qeayjdrzqo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qeayjdrzqo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qeayjdrzqo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qeayjdrzqo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qeayjdrzqo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qeayjdrzqo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_left {\n  text-align: left;\n}\n\n#qeayjdrzqo .gt_center {\n  text-align: center;\n}\n\n#qeayjdrzqo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qeayjdrzqo .gt_font_normal {\n  font-weight: normal;\n}\n\n#qeayjdrzqo .gt_font_bold {\n  font-weight: bold;\n}\n\n#qeayjdrzqo .gt_font_italic {\n  font-style: italic;\n}\n\n#qeayjdrzqo .gt_super {\n  font-size: 65%;\n}\n\n#qeayjdrzqo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qeayjdrzqo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qeayjdrzqo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qeayjdrzqo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qeayjdrzqo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qeayjdrzqo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qeayjdrzqo .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qeayjdrzqo .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#qeayjdrzqo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Cytology\">Cytology</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"HPV_Status\">HPV_Status</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"N_individuals\">N_individuals</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Cytology\" class=\"gt_row gt_left\">Normal</td>\n<td headers=\"HPV_Status\" class=\"gt_row gt_left\">HPV+</td>\n<td headers=\"N_individuals\" class=\"gt_row gt_right\">2226</td></tr>\n    <tr><td headers=\"Cytology\" class=\"gt_row gt_left\">Abnormal</td>\n<td headers=\"HPV_Status\" class=\"gt_row gt_left\">HPV+</td>\n<td headers=\"N_individuals\" class=\"gt_row gt_right\">417</td></tr>\n    <tr><td headers=\"Cytology\" class=\"gt_row gt_left\">Normal</td>\n<td headers=\"HPV_Status\" class=\"gt_row gt_left\">HPV-</td>\n<td headers=\"N_individuals\" class=\"gt_row gt_right\">19154</td></tr>\n    <tr><td headers=\"Cytology\" class=\"gt_row gt_left\">Abnormal</td>\n<td headers=\"HPV_Status\" class=\"gt_row gt_left\">HPV-</td>\n<td headers=\"N_individuals\" class=\"gt_row gt_right\">46</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nExtract the true positives, true negatives, false positives, false negatives:\n\n* True positives - have HPV and have abnormal cells\n* True negatives - don't have HPV and have normal cells\n* False positives - have HPV and have normal cells\n* False negatives - don't have HPV and have abnormal cells\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntp <- hpv_df |>\n  filter(HPV_Status == \"HPV+\", Cytology == \"Abnormal\") |>\n  pull(N_individuals)\ntn <- hpv_df |>\n  filter(HPV_Status == \"HPV-\", Cytology == \"Normal\") |>\n  pull(N_individuals)\nfp <- hpv_df |>\n  filter(HPV_Status == \"HPV+\", Cytology == \"Normal\") |>\n  pull(N_individuals)\nfn <- hpv_df |>\n  filter(HPV_Status == \"HPV-\", Cytology == \"Abnormal\") |>\n  pull(N_individuals)\n```\n:::\n\n\n[Calculate the proportion of people with hrHPV who have abnormal cells.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count how many people have hrHPV - positives\nhpv_count <- tp + fp\n\n# Calculate the proportion of people with hrHPV who\n# also have abnormal cells - true positives / positives\nprop_abnormal_given_hpv <- tp / hpv_count\nprint(prop_abnormal_given_hpv)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1577753\n```\n\n\n:::\n:::\n\n15.78% of people with hrHPV have abnormal cells.\n\n[Calculate the proportion of people without hrHPV who have abnormal cells.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count how many people don't have hrHPV - negatives\nhpv_m_count <- tn + fn\n\n# Calculate the proportion of people who don't have hrHPV who\n# do have abnormal cells - false_negatives / negatives\nprop_abnormal_given_no_hpv <- fn / hpv_m_count\nprint(prop_abnormal_given_no_hpv)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.002395833\n```\n\n\n:::\n:::\n\n0.24% of people without hrHPV have abnormal cells.\n\n\n[Calculate the proportion of people with abnormal cells who have hrHPV - the sensitivity of the hrHPV as a marker.]{.blue-text}\n\n$$\n\\text{Sensitivity} =\n\\frac{\\text{True positives}}\n{\\text{True positives} + \\text{False negatives}}\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count how many people have abnormal cells -\n# true positives and false negatives\nab_count <- tp + fn\n\n# Calculate the proportion of people who have\n# abnormal cells who also have hpv\nprop_hpv_given_abnormal <- tp / ab_count\nprint(prop_hpv_given_abnormal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9006479\n```\n\n\n:::\n:::\n\n\nThe sensitivity of HPV status as a test for abnormal cells is 90.06%.\n\n[Calculate the proportion of people who have normal cells and don't have hrHPV - the specificity of hrHPV as a marker.]{.blue-text}\n\n$$\n\\text{Specificity} =\n\\frac{\\text{True negatives}}\n{\\text{True negatives} + \\text{False positives}}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count how many people have normal cells -\n# true negatives and false positives\nn_count <- tn + fp\n\n# Calculate the proportion of people who have\n# normal cells who don't have hpv\nprop_no_hpv_given_normal <- tn / n_count\nprint(prop_no_hpv_given_normal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.895884\n```\n\n\n:::\n:::\n\n\nThe specificity of HPV status as a test for abnormal cells is 89.59%.\n\n:::\n:::\n\nSo far, we've calculated proportions using the whole sample of 21,843 individuals. However, the prevalence of moderate/severe abnormal cytology varies considerably with age.\n\nIn this sample the authors described:\n\n* **5.08%** prevalence of moderate/severe abnormal cytology in individuals aged 20-29\n* **1.81%** prevalence of moderate/severe abnormal cytology in individuals aged 30-49\n* **0.47%** prevalence of moderate/severe abnormal cytology individuals aged 50-64\n\n:::{.callout-exercise #ex-simulation_by_age}\n\nIn your `HPV.qmd` Quarto file:\n\n* For each of these age groups, simulate a sample of 10,000 individuals with the appropriate prevalence of moderate/severe cytology.\n\n* For the individuals in your simulation with and without moderate/severe cytology, simulate the presence of HPV based on the frequencies calculated in exercise 1.\n\n* In each iteration, store the number of people with HPV, the number of people with abnormal cells and the number of people with abnormal cells and HPV in a data frame.\n\n* Use your simulated data to estimate the probability that an individual in each group with hrHPV has moderate-or-worse abnormal cytology. \n\n* Use your simulated data to estimate the probability that an individual in each group with moderate-or-worse abnormal cytology has hrHPV.\n\n* Why does the probability that an individual in each group with hrHPV has moderate-or-worse abnormal cytology differ so much, even though the sensitivity and specificity of hrHPV as a marker were kept constant? \n\n\n::: {.callout-answer collapse=\"true\" #ex-simulation_by_age_ans}\n\n[For each of these age groups, simulate a sample of 10,000 individuals with the appropriate prevalence of moderate/severe cytology.]{.blue-text}\n\n[For the individuals in your simulation with and without moderate/severe cytology, simulate the presence of HPV based on the frequencies calculated in exercise 1.]{.blue-text}\n\n[In each iteration, store the number of people with HPV, the number of people with abnormal cells and the number of people with abnormal cells and HPV in a data frame.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprevs <- c(0.0508, 0.0181, 0.0047)\n\nn_sim <- 10000\nresults <- tibble()\n\nfor (prop_abnormal in prevs) {\n  # Simulate a population of people with normal and\n  # abnormal cells at the population rate\n  # 1 = abnormal\n  # 0 = normal\n  cyt_statuses <- rbinom(n_sim, 1, prop_abnormal)\n\n  # Count how many people have abnormal cells\n  n_abnormal <- sum(cyt_statuses == 1)\n  n_normal <- sum(cyt_statuses == 0)\n\n  # For the people with abnormal cells, simulate HPV\n  # presence based on the proportion of people with HPV\n  # given abnormal cells calculated in ex1.\n\n  hpv_statuses_abnormal <- rbinom(\n    n_abnormal, 1,\n    prop_hpv_given_abnormal\n  )\n\n  # For the people with normal cells, simulate HPV\n  # presence\n\n  # Calculate the proportion of people with HPV given\n  # normal cells\n  prop_hpv_given_normal <- 1 - prop_no_hpv_given_normal\n\n  hpv_statuses_normal <- rbinom(\n    n_normal, 1,\n    prop_hpv_given_normal\n  )\n\n  # How many people have HPV\n  n_hpv <- sum(hpv_statuses_normal == 1) + sum(hpv_statuses_abnormal == 1)\n\n  # How many people have HPV and abnormal cells - true positives\n  n_hpv_abnormal <- sum(hpv_statuses_abnormal == 1)\n\n  # Generate a row for the data frame with these results\n  current <- tibble(\n    Prevalence = prop_abnormal,\n    N_Abnormal = n_abnormal,\n    N_HPV = n_hpv,\n    N_TP = n_hpv_abnormal\n  )\n\n  # Add this result to the data frame\n  results <- results |> bind_rows(current)\n}\n\n# Add a column to the data frame with the age ranges\n# .before = 1 - put it before the first column\n\nresults <- results |> mutate(age_group = c(\n  \"20-29\",\n  \"30-49\",\n  \"50-64\"\n), .before = 1)\n```\n:::\n\n\n[Use your simulated data to estimate the probability that an individual in each group with hrHPV has moderate-or-worse abnormal cytology.]{.blue-text}\n\n[Use your simulated data to estimate the probability that an individual in each group with moderate-or-worse abnormal cytology has hrHPV.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the proportion of people with abnormal cells given that\n# they have HPV and the proportion of people with HPV given that they\n# have abnormal cells, add these to the data frame.\n\nresults <- results |> mutate(\n  Abnormal_given_hrHPV = N_TP / N_HPV,\n  hrHPV_given_Abnormal = N_TP / N_Abnormal\n)\n\ngt(results)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"zukwurjmgy\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zukwurjmgy table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zukwurjmgy thead, #zukwurjmgy tbody, #zukwurjmgy tfoot, #zukwurjmgy tr, #zukwurjmgy td, #zukwurjmgy th {\n  border-style: none;\n}\n\n#zukwurjmgy p {\n  margin: 0;\n  padding: 0;\n}\n\n#zukwurjmgy .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zukwurjmgy .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zukwurjmgy .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zukwurjmgy .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zukwurjmgy .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zukwurjmgy .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zukwurjmgy .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zukwurjmgy .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zukwurjmgy .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zukwurjmgy .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zukwurjmgy .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zukwurjmgy .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zukwurjmgy .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zukwurjmgy .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zukwurjmgy .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zukwurjmgy .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zukwurjmgy .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zukwurjmgy .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zukwurjmgy .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zukwurjmgy .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zukwurjmgy .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zukwurjmgy .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zukwurjmgy .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zukwurjmgy .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zukwurjmgy .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zukwurjmgy .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zukwurjmgy .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zukwurjmgy .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zukwurjmgy .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zukwurjmgy .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zukwurjmgy .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zukwurjmgy .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zukwurjmgy .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zukwurjmgy .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zukwurjmgy .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zukwurjmgy .gt_left {\n  text-align: left;\n}\n\n#zukwurjmgy .gt_center {\n  text-align: center;\n}\n\n#zukwurjmgy .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zukwurjmgy .gt_font_normal {\n  font-weight: normal;\n}\n\n#zukwurjmgy .gt_font_bold {\n  font-weight: bold;\n}\n\n#zukwurjmgy .gt_font_italic {\n  font-style: italic;\n}\n\n#zukwurjmgy .gt_super {\n  font-size: 65%;\n}\n\n#zukwurjmgy .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zukwurjmgy .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zukwurjmgy .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zukwurjmgy .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zukwurjmgy .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zukwurjmgy .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zukwurjmgy .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zukwurjmgy .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zukwurjmgy div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"age_group\">age_group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Prevalence\">Prevalence</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"N_Abnormal\">N_Abnormal</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"N_HPV\">N_HPV</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"N_TP\">N_TP</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Abnormal_given_hrHPV\">Abnormal_given_hrHPV</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"hrHPV_given_Abnormal\">hrHPV_given_Abnormal</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"age_group\" class=\"gt_row gt_right\">20-29</td>\n<td headers=\"Prevalence\" class=\"gt_row gt_right\">0.0508</td>\n<td headers=\"N_Abnormal\" class=\"gt_row gt_right\">501</td>\n<td headers=\"N_HPV\" class=\"gt_row gt_right\">1404</td>\n<td headers=\"N_TP\" class=\"gt_row gt_right\">448</td>\n<td headers=\"Abnormal_given_hrHPV\" class=\"gt_row gt_right\">0.31908832</td>\n<td headers=\"hrHPV_given_Abnormal\" class=\"gt_row gt_right\">0.8942116</td></tr>\n    <tr><td headers=\"age_group\" class=\"gt_row gt_right\">30-49</td>\n<td headers=\"Prevalence\" class=\"gt_row gt_right\">0.0181</td>\n<td headers=\"N_Abnormal\" class=\"gt_row gt_right\">183</td>\n<td headers=\"N_HPV\" class=\"gt_row gt_right\">1249</td>\n<td headers=\"N_TP\" class=\"gt_row gt_right\">150</td>\n<td headers=\"Abnormal_given_hrHPV\" class=\"gt_row gt_right\">0.12009608</td>\n<td headers=\"hrHPV_given_Abnormal\" class=\"gt_row gt_right\">0.8196721</td></tr>\n    <tr><td headers=\"age_group\" class=\"gt_row gt_right\">50-64</td>\n<td headers=\"Prevalence\" class=\"gt_row gt_right\">0.0047</td>\n<td headers=\"N_Abnormal\" class=\"gt_row gt_right\">50</td>\n<td headers=\"N_HPV\" class=\"gt_row gt_right\">1132</td>\n<td headers=\"N_TP\" class=\"gt_row gt_right\">42</td>\n<td headers=\"Abnormal_given_hrHPV\" class=\"gt_row gt_right\">0.03710247</td>\n<td headers=\"hrHPV_given_Abnormal\" class=\"gt_row gt_right\">0.8400000</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n* 31.91% of people aged 20-29 with HPV have abnormal cells.\n* 12.01% of people aged 30-49 with HPV have abnormal cells.\n* 3.71% of people aged 50-64 with HPV have abnormal cells.\n\n* 89.42% of people aged 20-29 with abnormal cells have HPV.\n* 81.97% of people aged 30-49 with abnormal cells have HPV.\n* 84% of people aged 50-64 with abnormal cells have HPV.\n\n[Why does the probability that an individual in each group with hrHPV has moderate-or-worse abnormal cytology differ so much, even though the sensitivity and specificity of hrHPV as a marker were kept constant?]{.blue-text}\n\nBecause the prevalence of abnormal cells changes so much between the groups. The sensitivity of the test tells us the probability the person will test positive if they have the disease and the specificity tells us the probability they will test negative if they don't have the disease. The ratio of people who do and don't have the disease differs between the three samples.\n\n:::\n:::\n\n::: {.callout-note .extension #ex-cc}\n\n### Extension exercise: Cervical cancer\n\nWe can extend this simulation to consider cervical cancer as an outcome, rather than just abnormal cells.\n\nBased on [this paper](https://doi.org/10.1111/cyt.12259) published in Cytopathology in 2016 and also based on UK individuals, the positive predictive value of moderate or severely abnormal cells for cervical cancer is:\n\n* **1.5%** for people aged 20-29\n* **3.4%** for people aged 30-49\n* **5.1%** for people aged 50-64\n\n(Note that these are estimates, as this paper uses slightly different age ranges)\n\nThis means that, based on this sample, for example, 1.5% of people aged 20-29 with at least moderately abnormal cells will then be diagnosed with cervical cancer. In this study no-one of any age with normal cells was diagnosed with cervical cancer.\n\nExtend your simulation to calculate the probability that a 24 year old who is HPV positive and has a cervix would be diagnosed with cervical cancer on further testing (assuming prevalence is constant across the 20-29 age group).\n\n::: {.callout-answer collapse=\"true\" #ex-cc_ans}\n\n::: {.cell}\n\n```{.r .cell-code}\nresults_cc <- tibble()\nprop_cc_given_abnormal <- 0.015\nprop_abnormal <- 0.0508\n\n# Simulate a population of people with normal and\n# abnormal cells at the population rate for age 20-29\n# 1 = abnormal\n# 0 = normal\ncyt_statuses <- rbinom(n_sim, 1, prop_abnormal)\n\n# Count how many people have abnormal cells\nn_abnormal <- sum(cyt_statuses == 1)\nn_normal <- sum(cyt_statuses == 0)\n  \n# For the people with abnormal cells, simulate HPV\n# presence based on the proportion of people with HPV\n# given abnormal cells calculated in ex1.\nhpv_statuses_abnormal <- rbinom(\n  n_abnormal, 1,\n  prop_hpv_given_abnormal\n)\n\n# For the people with normal cells, simulate HPV\n# presence based on the proportion of people with HPV\n# given abnormal cells calculated in ex1.\nhpv_statuses_normal <- rbinom(\n  n_normal, 1,\n  prop_hpv_given_normal\n)\n\n# Only the abnormal cells people can have HPV in this example\n# For the people with abnormal cells, simulate cervical\n# cancer with a prevalence of 0.015\ncc_statuses_abnormal <- rbinom(\n  n_abnormal, 1,\n  prop_cc_given_abnormal\n)\n# How many people have HPV\nn_hpv <- sum(hpv_statuses_abnormal == 1) + sum(hpv_statuses_normal == 1)\n\n# How many people have HPV and cervical cancer\nn_hpv_cc <- sum(cc_statuses_abnormal == 1 & hpv_statuses_abnormal == 1)\n\n# What proportion of people with HPV have cervical cancer\nprop_cc <- n_hpv_cc / n_hpv\n\nprint(prop_cc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.001385042\n```\n\n\n:::\n:::\n\nUnder this simplified model, we estimate that 0.14% of HPV-positive individuals aged 20–29 would be diagnosed with cervical cancer.\n\n:::{.callout-note #note-cc}\n\nThis is a simplified model designed to explore conditional probability and should not be interpreted as a model of an individual's clinical risk.\n\n:::\n:::\n\nFor this part of the practical, the main files you have edited are:\n\n* `hpv.qmd`\n\nThese are the files you should select when making your Git commit.\n\n::: {.callout-tip}\n## Commit your changes\nRemember to save your progress regularly by committing your changes with Git.\n\n1. Save your changes to the files above in RStudio with the `Save` button.\n2. Render any Quarto documents with the `Render` button.\n3. Open the `Git` tab in RStudio.\n4. Tick the files listed above, don't worry about any others.\n5. Click `Commit` and write a short message in the `Commit message` describing your changes, something like e.g. \"Practical 1 part 1\" is sufficient, then click `Commit`. Close the `Commit` popup.\n\n:::\n\t\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}