{
  "hash": "b6c13f3955c2bb02b3f512e7a9fe403a",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: html\npractical: Practical_3_Probability\ndoc-id: \"0306\"\n---\n\n\n# Part 5 - Bonus: Sampling from a user-defined probability distribution {#sec-non_standard}\n\n**This whole page is bonus content**\n\n::: {.callout-note .partmenu #parts-0303}\n\n## Sections\n- @sec-user_defined\n\n:::\n\n:::{.callout-tip .objectives #objectives-0303}\n\n## Learning Objectives\n\nBy the end of this section, you will be able to:\n\n* Plot a user-defined PDF.\n* Check a probability function is valid using `integrate()`\n* Simulate data based on a user defined PDF.\n\n:::\n\n## Sampling from a user defined probability distribution {#sec-user_defined}\n\nEarlier, we used functions such as `rbinom()`, `rpois()` and `rnorm()` to simulate data from named probability distributions. However, sometimes we may want to simulate from a probability distribution for which R does not provide a built-in random-sampling function, or from a PDF that we have defined ourselves.\n\nIn R, it is possible to simulate data from a user-defined probability distribution using the package `Runuran`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(Runuran)\n```\n:::\n\n\nFor example, cats like to sit on keyboards, particularly if they are currently being used. Let's say a researcher has developed a probability density function describing the position at which a cat's centre of mass occurs along a 40-cm keyboard, measured as distance in cm from the left edge.\n\n$$\nf(x) =\n\\begin{cases}\n\\frac{3x(40-x)}{32000}, & 0 \\leq x \\leq 40 \\\\\n0, & \\text{otherwise}\n\\end{cases}\n$$\n\n![Example data point](images/keyboard_cat.png){#fig-keyboard_cat width=\"50%\"}\n\nLet's plot just the function.\n\nHere, instead of giving the argument `fun` our function name, we directly give it our cat PDF.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  stat_function(\n    fun = function(x) {\n      3 * x * (40 - x) / 32000\n    },\n    xlim = c(0, 40)\n  ) +\n  xlab(\"Distance from Left Edge\") +\n  ylab(\"Density\")\n```\n\n::: {.cell-output-display}\n![](03-06_bonus_non_standard_distributions_files/figure-html/plot_cat_pdf-1.png){width=672}\n:::\n:::\n\n\nAs expected, cats like to sit in the middle where they can obscure the most keys and, ideally, block the view of the screen.\n\nFor a function to be a valid PDF, its total area must equal 1. We can check this in R using `integrate()`. `integrate()` takes 3 arguments - the PDF, `lower` - the lower bound - and `upper` - the upper bound.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat_int <- integrate(function(x) {\n  3 * x * (40 - x) / 32000\n}, lower = 0, upper = 40)\nprint(cat_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1 with absolute error < 1.1e-14\n```\n\n\n:::\n:::\n\n\nThe total area under this curve is 1 - so the function is valid.\n\nUsing our probability density function, let's simulate the positions of 10,000 cats, then estimate the probability that the centre of the cat is within the central 10 cm of the keyboard.\n\nFirst, we use the function `pinv.new()` to create a **random number generator** which can sample values from a continuous distribution described by a user-defined PDF.\n\nThe arguments are:\n* `pdf` - the PDF\n* `lb` - the lower bound, in our case 0\n* `ub` - the upper bound, in our case 40\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat_gen <- pinv.new(\n  pdf = function(x) {\n    3 * x * (40 - x) / 32000\n  },\n  lb = 0,\n  ub = 40\n)\n```\n:::\n\n\nNow, to simulate data from this distribution, we use the function `ur()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat_positions <- ur(cat_gen,\n  n = 10000\n)\n```\n:::\n\n\nLet's plot our cats. First, we need to put the data in a data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat_df <- tibble(Position = cat_positions)\nggplot(cat_df, aes(x = Position)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 50) +\n  stat_function(\n    fun = function(x) {\n      3 * x * (40 - x) / 32000\n    }\n  )\n```\n\n::: {.cell-output-display}\n![](03-06_bonus_non_standard_distributions_files/figure-html/plot_more_cats-1.png){width=672}\n:::\n:::\n\n\nFinally, let's estimate the probability that a cat will sit within the central 10 cm of the keyboard. The middle 10 cm lies between 15 cm and 25 cm from the left edge.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmiddle_only <- cat_df |> filter(\n  Position >= 15,\n  Position <= 25\n)\nprop_middle <- nrow(middle_only) / nrow(cat_df)\nprint(prop_middle)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3628\n```\n\n\n:::\n:::\n\n\nBased on our simulation, cats will sit in the middle 10 cm of the keyboard approximately 36.28% of the time.\n\n::: {.callout-exercise #ex-cats}\n\nSome cat parents like to, for their own amusement, pile objects onto their sleeping cat, a game known as [cat buckaroo](https://knowyourmeme.com/memes/cat-buckaroo).\n\n![Example data point](images/jethro1.jpeg){#fig-cataroo width=\"50%\"}\n\nCats will tolerate this to a certain extent but, at some point, will get up and shake the objects off. The weight of objects the cat will tolerate varies considerably between cats.\n\nCats appear to fall into two broad groups: those that almost immediately object to this game, and those that will tolerate a substantial pile before taking action. A researcher proposes the following probability density function for the total weight of objects a sleeping cat will tolerate before shaking them off.\n\n\n$$\nf(x) =\n\\begin{cases}\n\\frac{1-\\cos\\left(\\frac{4\\pi x}{1000}\\right)}{1000},\n& 0 \\leq x \\leq 1000 \\\\\n0, & \\text{otherwise}\n\\end{cases}\n$$\n\n::: {.callout-note #note-cos_pi}\n\nTo use pi in R, you can just type pi.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(pi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.141593\n```\n\n\n:::\n:::\n\nTo calculate a cosine you can use the function `cos()` with one argument, the number for which you want to calculate the cosine.\n\n:::\n\nIn your `distributions.qmd` Quarto file:\n\n* Plot this function.\n* Check it is a valid PDF.\n* Create a **random number generator** which can sample values from the distribution described by this PDF.\n* Simulate 10,000 values.\n* A cat has already tolerated 500 g of objects. Estimate the probability that it will tolerate the addition of a 75 g Yoda figurine without shaking everything off.\n\n![Example data point](images/jethro2.jpeg){#fig-cataroo width=\"50%\"}\n\n::: {.callout-answer collapse=\"true\" #ex-cats_ans}\n\n[Plot this function.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  stat_function(\n    fun = function(x) {\n      (1 - cos(4 * pi * x / 1000)) / 1000\n    },\n    xlim = c(0, 1000)\n  ) +\n  xlab(\"Weight of objects\") +\n  ylab(\"Density\")\n```\n\n::: {.cell-output-display}\n![](03-06_bonus_non_standard_distributions_files/figure-html/cats_ans1-1.png){width=672}\n:::\n:::\n\n\n[Check it is a valid PDF.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncataroo_int <- integrate(\n  function(x) {\n    (1 - cos(4 * pi * x / 1000)) / 1000\n  },\n  lower = 0,\n  upper = 1000\n)\nprint(cataroo_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1 with absolute error < 7.3e-10\n```\n\n\n:::\n:::\n\nThe area under the curve is 1 so this is a valid PDF.\n\n[Create a **random number generator** which can sample values from the distribution described by this PDF.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncataroo_gen <- pinv.new(\n  pdf = function(x) {\n    (1 - cos(4 * pi * x / 1000)) / 1000\n  },\n  lb = 0,\n  ub = 1000\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[UNU.RAN - warning] NaN occured: tail probability gives NaN --> assume 0.\n[UNU.RAN - warning] NaN occured: tail probability gives NaN --> assume 0.\n```\n\n\n:::\n:::\n\n\n[Simulate 10,000 values.]{.blue-text}\n\n::: {.cell}\n\n```{.r .cell-code}\ncat_tolerance <- ur(cataroo_gen,\n  n = 10000\n)\n```\n:::\n\n\n[A cat has already tolerated 500 g of objects. Estimate the probability that it will tolerate the addition of a 75 g Yoda figurine without shaking everything off.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat_tolerance_df <- tibble(Tolerance = cat_tolerance)\n\n# Find all the cats who tolerated at least 500g\nover_500 <- cat_tolerance_df |> filter(Tolerance >= 500)\n\n# Find all the cats who tolerated at least 575g\nover_575 <- cat_tolerance_df |> filter(Tolerance >= 575)\n\n# Calculate the proportion of cats who tolerated at least 500g who will tolerate at least 575g.\nprop <- nrow(over_575) / nrow(over_500)\n\nprint(prop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9782\n```\n\n\n:::\n:::\n\n\n![Example data point](images/jethro3.jpeg){#fig-cataroo width=\"50%\"}\n\nIf a cat has tolerated the addition of 500g of objects, there is an estimated 97.82% probability they will tolerate an additional 75g Yoda figurine.\n\n![Example data point](images/jethro4.jpeg){#fig-cataroo width=\"50%\"}\n:::\n:::\n",
    "supporting": [
      "03-06_bonus_non_standard_distributions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}