---
title: "Plan and Learning Objectives"
format: html
practical: Practical_1_Introduction_to_R
doc-id: "0100"
author: "Katy Brown"
---

```{r setup, include=FALSE}
library(tidyverse)
```

# Practical 1 - Using R and RStudio

::: {.callout-tip .partmenu #parts-0100}

## Practical 1 - Using R and RStudio

### @sec-p1_r_and_rstudio

#### Sections

- @sec-open_r
- @sec-r_language
- @sec-coding_in_the_console
- @sec-rstudio_interface
- @sec-console_scripts
- @sec-summary_0101

#### Learning Objectives

By the end of this part of the practical you should be able to:

- Explain what R is and why it is useful for biological data analysis.
- Use some features of the RStudio interface.
- Use the R console and R scripts to run R code.

### @sec-p2_quarto

#### Sections

- @sec-quarto
- @sec-creating_quarto
- @sec-formatting_quarto
- @sec-analysis_in_quarto
- @sec-documenting_and_formatting_your_code
- @sec-summary_0102

#### Learning Objectives

By the end of this part of the practical you should be able to:

- Use Quarto documents to run R code.
- Create a simple reproducible analysis using Quarto.
- Understand the benefits of writing clear, well-formatted and documented R code.

### @sec-p3_functions_and_variables

#### Sections

- @sec-functions
- @sec-arguments
- @sec-variables
- @sec-variable_types
- @sec-r_quirks [(Bonus)]{.bonus-text}
- @sec-summary_0103

#### Learning Objectives

By the end of this part of the practical you should be able to:

- Explain what a function is and use some simple functions.
- Explain how and why we provide arguments to functions.
- Explain the concept of a variable and use variables in your code.
- Recognise and use common types of variable, including numeric, character and logical variables.

### @sec-p4_vectors_data_frames_plots

#### Sections

- @sec-packages
- @sec-vectors
- @sec-vectorisation [(Extension)]{.extension-text}
- @sec-data_frames
- @sec-csv
- @sec-api [(Bonus)]{.bonus-text}
- @sec-plots
- @sec-additional_plot_styling [(Extension)]{.extension-text}

#### Learning Objectives

By the end of this part of the practical you should be able to:

- Install and load a package in R.
- Create and use vectors in R.
- Access individual elements of a vector using an index.
- Create and view a simple data frame.
- Recognise and read data stored in CSV format.
- Create a simple line plot in R using ggplot2.
:::