{
  "hash": "d2a9389a9ce130cbe0adbf4197424e49",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: html\npractical: Practical_4_Statistics\ndoc-id: \"0407\"\nauthor: \"Katy Brown\"\n---\n\n\n\n# Part 7: Estimators and Bootstrapping\n\n## Estimators {#sec-estimators}\n\nAn estimator is a statistic calculated from a sample that we use to estimate an unknown characteristic of the wider population. Different estimators can be used to estimate the same population parameter, and they may differ in how accurately and consistently they do so.\n\nFor example, let's concentrate on a single aspect of the data for now - the species richness, measured as the number of unique species.\n\nAcross the whole dataset, we can find the number of unique species using our `insect_counts` data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_unique_species <- insect_counts |>\n  distinct(species) |>\n  nrow()\nprint(n_unique_species)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 239\n```\n\n\n:::\n:::\n\nThere are 239 unique species.\n\nThe data we have here are themselves only a sample of the real population. For this exercise, however, we will pretend that the complete dataset is our population. This allows us to repeatedly sample from a known pseudo-population and observe how our estimators behave across different samples.\n\nLet's say we wanted to estimate the total species richness across the full data set based on 20 sites and we have three possible estimators:\n\n* Observed richness - total number of unique species across 20 sites\n* Scaled observed richness - total number of unique species across 20 sites * (total number of sites / 20)\n* The Chao1 richness estimator, which uses the number of rare species in the sample to estimate how many species may have gone undetected.\n\nFirst let's take a sample of 20 random sites.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrandom_sites <- site_metadata |>\n  distinct(x1km_square) |>\n  slice_sample(n = 20) |>\n  pull(x1km_square)\n```\n:::\n\n\nNow we can extract these rows from our insect counts data frame. For this part of the practical, we're not interested in insects with a count of 0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsect_sample <- insect_counts |>\n  filter(\n    x1km_square %in% random_sites,\n    n_observed != 0\n  )\n\ngt(head(insect_sample))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ntakldeufx\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ntakldeufx table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ntakldeufx thead, #ntakldeufx tbody, #ntakldeufx tfoot, #ntakldeufx tr, #ntakldeufx td, #ntakldeufx th {\n  border-style: none;\n}\n\n#ntakldeufx p {\n  margin: 0;\n  padding: 0;\n}\n\n#ntakldeufx .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ntakldeufx .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ntakldeufx .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ntakldeufx .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ntakldeufx .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ntakldeufx .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ntakldeufx .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ntakldeufx .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ntakldeufx .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ntakldeufx .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ntakldeufx .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ntakldeufx .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ntakldeufx .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ntakldeufx .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ntakldeufx .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ntakldeufx .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ntakldeufx .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ntakldeufx .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ntakldeufx .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ntakldeufx .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ntakldeufx .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ntakldeufx .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ntakldeufx .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ntakldeufx .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ntakldeufx .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ntakldeufx .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ntakldeufx .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ntakldeufx .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ntakldeufx .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ntakldeufx .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ntakldeufx .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ntakldeufx .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ntakldeufx .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ntakldeufx .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ntakldeufx .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ntakldeufx .gt_left {\n  text-align: left;\n}\n\n#ntakldeufx .gt_center {\n  text-align: center;\n}\n\n#ntakldeufx .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ntakldeufx .gt_font_normal {\n  font-weight: normal;\n}\n\n#ntakldeufx .gt_font_bold {\n  font-weight: bold;\n}\n\n#ntakldeufx .gt_font_italic {\n  font-style: italic;\n}\n\n#ntakldeufx .gt_super {\n  font-size: 65%;\n}\n\n#ntakldeufx .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ntakldeufx .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ntakldeufx .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ntakldeufx .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ntakldeufx .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ntakldeufx .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ntakldeufx .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ntakldeufx .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ntakldeufx div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"x1km_square\">x1km_square</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"species\">species</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_observed\">n_observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"genus\">genus</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC2313</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Lejogaster metallina</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">1</td>\n<td headers=\"genus\" class=\"gt_row gt_left\">Lejogaster</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC2313</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Melanogaster hirtella</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">5</td>\n<td headers=\"genus\" class=\"gt_row gt_left\">Melanogaster</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC2313</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Melanostoma mellinum</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">2</td>\n<td headers=\"genus\" class=\"gt_row gt_left\">Melanostoma</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC2313</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Platycheirus albimanus</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">1</td>\n<td headers=\"genus\" class=\"gt_row gt_left\">Platycheirus</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC2313</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Sericomyia lappona</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">1</td>\n<td headers=\"genus\" class=\"gt_row gt_left\">Sericomyia</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC2313</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Sericomyia silentis</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">1</td>\n<td headers=\"genus\" class=\"gt_row gt_left\">Sericomyia</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n#### Observed richness\n\nThe observed richness is just the total number of unique species observed across all sites.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_rich <- insect_sample |>\n  distinct(species) |>\n  pull(species)\nn_obs_rich <- length(obs_rich)\nprint(n_obs_rich)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 166\n```\n\n\n:::\n:::\n\nThe  observed richness estimator for this sample is 166.\n\n#### Scaled observed richness\n\nThe scaled observed richness is the total number of unique species observed across all sites, multiplied by \n(total number of sites / number of sites in sample).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_sites_sample <- 20\nsite_count <- nrow(site_metadata)\nscaled_obs_rich <- n_obs_rich * (site_count / n_sites_sample)\nprint(scaled_obs_rich)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 630.8\n```\n\n\n:::\n:::\n\nThe scaled observed richness estimator for this sample is 631.\n\n#### Chao1 estimator\n\nThe Chao1 estimator estimates unseen species based on the number of species represented only once or twice in your sample.\n\n$$\n\\hat{S}_{Chao1} = S_{obs} + \\frac{f_1^2}{2f_2}\n$$\n\nwhere:\n\n- $S_{obs}$ is the number of species observed in the sample.\n- $f_1$ is the number of species observed exactly once (singletons).\n- $f_2$ is the number of species observed exactly twice (doubletons).\n\n::: {.callout-note #note-chao}\nYou do not need to remember this - it is just an example of an estimator. \n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_per_insect <- insect_sample |>\n  group_by(species) |>\n  summarise(n_total = sum(n_observed))\n\nonce <- obs_per_insect |> filter(n_total == 1)\ntwice <- obs_per_insect |> filter(n_total == 2)\n\nn_once <- nrow(once)\nn_twice <- nrow(twice)\n\nchao <- n_obs_rich + ((n_once^2) / (2 * n_twice))\nprint(chao)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 206.5\n```\n\n\n:::\n:::\n\nThe chao1 estimator for this sample is 206.\n\nNone of these did a particularly good job of finding our real value of 239.\n\nHowever, you can't measure how good an estimator is based on a single sample. Let's try simulation and generate multiple samples.\n\nRemember (from the lectures): An unbiased estimator gives the correct value on average across repeated samples. The efficiency of an estimator is determined by its variance: estimators with lower variance give more consistent estimates. Mean square error (MSE) combines bias and variance and measures how far, overall, estimates tend to be from the true value.\n\n::: {.callout-exercise #ex-simulate_estimators}\n\nUsing a for loop, with 10,000 iterations (this might take a minute or two to run).\n\n* Take a sample of 20 sites, then extract the insect counts for these sites from the data frame.\n* Calculate observed richness, scaled observed richness and chao1 for each sample.\n* Store the results for each estimator in a separate vector.\n* Combine these into a data frame.\n* For each estimator:\n  * Calculate the bias, as the difference between the mean value across samples and the real value from our pseudo population.\n  * Calculate the variance.\n  * Calculate the mean square error.\n* Which estimator would you use, if any?\n\n::: {.callout-answer collapse=\"true\" #ex-simulate_estimators_ans}\n\n[Take a sample of 20 sites, then extract the insect counts for these sites from the data frame.]{.blue-text}\n\n[Calculate observed richness, scaled observed richness and chao1 for each sample.]{.blue-text}\n\n[Store the results for each estimator in a separate vector.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_rich_vec <- c()\nscaled_obs_rich_vec <- c()\nchao_vec <- c()\n\n# Loop for 10,000 iterations\nfor (i in seq_len(10000)) {\n  # Sample 20 sites\n  random_sites <- site_metadata |>\n    distinct(x1km_square) |>\n    slice_sample(n = 20) |>\n    pull(x1km_square)\n\n  # Extract the insect counts for these sites\n  insect_sample <- insect_counts |>\n    filter(\n      x1km_square %in% random_sites,\n      n_observed != 0\n    )\n\n  # Calculate observed richness\n  obs_rich <- insect_sample |>\n    distinct(species) |>\n    pull(species)\n  n_obs_rich <- length(obs_rich)\n  # Store\n  obs_rich_vec <- c(obs_rich_vec, n_obs_rich)\n\n  # Calculate the scaled observed richness\n  scaled_obs_rich <- n_obs_rich * (site_count / 20)\n  # Store\n  scaled_obs_rich_vec <- c(scaled_obs_rich_vec, scaled_obs_rich)\n\n  # Calculate Chao1\n  obs_per_insect <- insect_sample |>\n    group_by(species) |>\n    summarise(n_total = sum(n_observed))\n\n  once <- obs_per_insect |> filter(n_total == 1)\n  twice <- obs_per_insect |> filter(n_total == 2)\n\n  n_once <- nrow(once)\n  n_twice <- nrow(twice)\n\n  chao <- n_obs_rich + ((n_once^2) / (2 * n_twice))\n  # Store\n  chao_vec <- c(chao_vec, chao)\n}\n```\n:::\n\n\n[Combine these into a data frame.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimator_df <- tibble(\n  Observed = obs_rich_vec,\n  Scaled_Observed = scaled_obs_rich_vec,\n  Chao1 = chao_vec)\n```\n:::\n\n\n\n\n[For each estimator:]{.blue-text}\n\n[Calculate the bias]{.blue-text}\n\n[Calculate the efficiency]{.blue-text}\n\n[Calculate the mean square error.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimator_summary <- estimator_df |>\n  summarise(\n    Bias_Observed = mean(Observed) - n_unique_species,\n    Bias_Scaled_Observed = mean(Scaled_Observed) - n_unique_species,\n    Bias_Chao1 = mean(Chao1) - n_unique_species,\n    Eff_Observed = var(Observed),\n    Eff_Scaled_Observed = var(Scaled_Observed),\n    Eff_Chao1 = var(Chao1),\n    MSE_Observed = mean((Observed - n_unique_species)^2),\n    MSE_Scaled_Observed =mean((Scaled_Observed - n_unique_species)^2),\n    MSE_Chao1 = mean((Chao1 - n_unique_species)^2)\n  )\ngt(estimator_summary)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"olwmzwwdbj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#olwmzwwdbj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#olwmzwwdbj thead, #olwmzwwdbj tbody, #olwmzwwdbj tfoot, #olwmzwwdbj tr, #olwmzwwdbj td, #olwmzwwdbj th {\n  border-style: none;\n}\n\n#olwmzwwdbj p {\n  margin: 0;\n  padding: 0;\n}\n\n#olwmzwwdbj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#olwmzwwdbj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#olwmzwwdbj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#olwmzwwdbj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#olwmzwwdbj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#olwmzwwdbj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#olwmzwwdbj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#olwmzwwdbj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#olwmzwwdbj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#olwmzwwdbj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#olwmzwwdbj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#olwmzwwdbj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#olwmzwwdbj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#olwmzwwdbj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#olwmzwwdbj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#olwmzwwdbj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#olwmzwwdbj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#olwmzwwdbj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#olwmzwwdbj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#olwmzwwdbj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#olwmzwwdbj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#olwmzwwdbj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#olwmzwwdbj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#olwmzwwdbj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#olwmzwwdbj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#olwmzwwdbj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#olwmzwwdbj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#olwmzwwdbj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#olwmzwwdbj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#olwmzwwdbj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#olwmzwwdbj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#olwmzwwdbj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#olwmzwwdbj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#olwmzwwdbj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#olwmzwwdbj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#olwmzwwdbj .gt_left {\n  text-align: left;\n}\n\n#olwmzwwdbj .gt_center {\n  text-align: center;\n}\n\n#olwmzwwdbj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#olwmzwwdbj .gt_font_normal {\n  font-weight: normal;\n}\n\n#olwmzwwdbj .gt_font_bold {\n  font-weight: bold;\n}\n\n#olwmzwwdbj .gt_font_italic {\n  font-style: italic;\n}\n\n#olwmzwwdbj .gt_super {\n  font-size: 65%;\n}\n\n#olwmzwwdbj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#olwmzwwdbj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#olwmzwwdbj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#olwmzwwdbj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#olwmzwwdbj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#olwmzwwdbj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#olwmzwwdbj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#olwmzwwdbj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#olwmzwwdbj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Bias_Observed\">Bias_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Bias_Scaled_Observed\">Bias_Scaled_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Bias_Chao1\">Bias_Chao1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Eff_Observed\">Eff_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Eff_Scaled_Observed\">Eff_Scaled_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Eff_Chao1\">Eff_Chao1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MSE_Observed\">MSE_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MSE_Scaled_Observed\">MSE_Scaled_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MSE_Chao1\">MSE_Chao1</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Bias_Observed\" class=\"gt_row gt_right\">-70.7319</td>\n<td headers=\"Bias_Scaled_Observed\" class=\"gt_row gt_right\">400.4188</td>\n<td headers=\"Bias_Chao1\" class=\"gt_row gt_right\">-33.38669</td>\n<td headers=\"Eff_Observed\" class=\"gt_row gt_right\">57.8032</td>\n<td headers=\"Eff_Scaled_Observed\" class=\"gt_row gt_right\">834.6782</td>\n<td headers=\"Eff_Chao1\" class=\"gt_row gt_right\">278.429</td>\n<td headers=\"MSE_Observed\" class=\"gt_row gt_right\">5060.799</td>\n<td headers=\"MSE_Scaled_Observed\" class=\"gt_row gt_right\">161169.8</td>\n<td headers=\"MSE_Chao1\" class=\"gt_row gt_right\">1393.072</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n[Which estimator would you use, if any?]{.blue-text}\n\nOf the three, the Chao1 estimator has the lowest mean square error, however it is still has a negative bias and a low efficiency.\n\n:::\n:::\n\nPlotting our simulated estimators also provides a lot of information.\n\nWe can combine all three estimators into a single plot, first we need to convert the data from wide to long format (see @sec-long_wide).\n\nThe function `everything()` tells R to pivot all of the columns in the table. A new column, `estimator` will be created to specify if each row is an observed, scaled observed or chao1 estimator.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimator_long <- estimator_df |>\n  pivot_longer(\n    everything(),\n    names_to = \"estimator\",\n    values_to = \"estimate\"\n  )\n\ngt(head(estimator_long))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"uleqidkfmj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#uleqidkfmj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uleqidkfmj thead, #uleqidkfmj tbody, #uleqidkfmj tfoot, #uleqidkfmj tr, #uleqidkfmj td, #uleqidkfmj th {\n  border-style: none;\n}\n\n#uleqidkfmj p {\n  margin: 0;\n  padding: 0;\n}\n\n#uleqidkfmj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uleqidkfmj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uleqidkfmj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uleqidkfmj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uleqidkfmj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uleqidkfmj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uleqidkfmj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uleqidkfmj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uleqidkfmj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uleqidkfmj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uleqidkfmj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uleqidkfmj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uleqidkfmj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uleqidkfmj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uleqidkfmj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uleqidkfmj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uleqidkfmj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uleqidkfmj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uleqidkfmj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uleqidkfmj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uleqidkfmj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uleqidkfmj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uleqidkfmj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uleqidkfmj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uleqidkfmj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uleqidkfmj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uleqidkfmj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uleqidkfmj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uleqidkfmj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uleqidkfmj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uleqidkfmj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uleqidkfmj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uleqidkfmj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uleqidkfmj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uleqidkfmj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uleqidkfmj .gt_left {\n  text-align: left;\n}\n\n#uleqidkfmj .gt_center {\n  text-align: center;\n}\n\n#uleqidkfmj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uleqidkfmj .gt_font_normal {\n  font-weight: normal;\n}\n\n#uleqidkfmj .gt_font_bold {\n  font-weight: bold;\n}\n\n#uleqidkfmj .gt_font_italic {\n  font-style: italic;\n}\n\n#uleqidkfmj .gt_super {\n  font-size: 65%;\n}\n\n#uleqidkfmj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uleqidkfmj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uleqidkfmj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uleqidkfmj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uleqidkfmj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uleqidkfmj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uleqidkfmj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#uleqidkfmj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#uleqidkfmj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimator\">estimator</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimator\" class=\"gt_row gt_left\">Observed</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">163.0000</td></tr>\n    <tr><td headers=\"estimator\" class=\"gt_row gt_left\">Scaled_Observed</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">619.4000</td></tr>\n    <tr><td headers=\"estimator\" class=\"gt_row gt_left\">Chao1</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">195.4000</td></tr>\n    <tr><td headers=\"estimator\" class=\"gt_row gt_left\">Observed</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">173.0000</td></tr>\n    <tr><td headers=\"estimator\" class=\"gt_row gt_left\">Scaled_Observed</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">657.4000</td></tr>\n    <tr><td headers=\"estimator\" class=\"gt_row gt_left\">Chao1</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">199.3269</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nNow, let's plot the values of each estimator as histograms. \n\nThe function `facet_wrap()` splits the data from a single data frame into multiple plots, based on the values in a categorical column. The first argument should be the variable you would like to facet by, preceded by a `~` symbol. The argument `scales = \"free\"` means that each plot can have a different scale bar - by default they are all the same.\n\nThe function `geom_vline()` adds a vertical line at a specific point, specified by the argument `xintercept`. In this case, the line is at our pseudo-population total species richness.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(estimator_long, aes(x = estimate)) +\n  geom_histogram(bins=50) +\n  facet_wrap(~ estimator, scales = \"free\") +\n  geom_vline(xintercept = n_unique_species, color='red')\n```\n\n::: {.cell-output-display}\n![](04-07_estimators_and_bootstrapping_files/figure-html/plot_simulated_estimators-1.png){width=672}\n:::\n:::\n\nHere it is clear again that none of these are great estimators, but that Chao1 is probably the best. \n\n:::{.callout-note .extension #ext_estimators_more_samples}\n\nSometimes an estimator is bad because the sample size is too small, sometimes it's just bad. Let's try taking 50 sites per sample, instead of 20.\n\nThe code below is identical to the above except for samples of 50 sites.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_rich_vec_50 <- c()\nscaled_obs_rich_vec_50 <- c()\nchao_vec_50 <- c()\n\n# Loop for 10,000 iterations\nfor (i in seq_len(10000)) {\n  # Sample 50 sites\n  random_sites <- site_metadata |>\n    distinct(x1km_square) |>\n    slice_sample(n = 50) |>\n    pull(x1km_square)\n\n  # Extract the insect counts for these sites\n  insect_sample <- insect_counts |>\n    filter(\n      x1km_square %in% random_sites,\n      n_observed != 0\n    )\n\n  # Calculate observed richness\n  obs_rich <- insect_sample |>\n    distinct(species) |>\n    pull(species)\n  n_obs_rich <- length(obs_rich)\n  # Store\n  obs_rich_vec_50 <- c(obs_rich_vec_50, n_obs_rich)\n\n  # Calculate the scaled observed richness\n  scaled_obs_rich <- n_obs_rich * (site_count / 50)\n  # Store\n  scaled_obs_rich_vec_50 <- c(scaled_obs_rich_vec_50, scaled_obs_rich)\n\n  # Calculate Chao1\n  obs_per_insect <- insect_sample |>\n    group_by(species) |>\n    summarise(n_total = sum(n_observed))\n\n  once <- obs_per_insect |> filter(n_total == 1)\n  twice <- obs_per_insect |> filter(n_total == 2)\n\n  n_once <- nrow(once)\n  n_twice <- nrow(twice)\n\n  chao <- n_obs_rich + ((n_once^2) / (2 * n_twice))\n  # Store\n  chao_vec_50 <- c(chao_vec_50, chao)\n}\n\nestimator_df_50 <- tibble(\n  Observed = obs_rich_vec_50,\n  Scaled_Observed = scaled_obs_rich_vec_50,\n  Chao1 = chao_vec_50)\n```\n:::\n\n\n\n\nNow we can look at the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimator_summary_50 <- estimator_df_50 |>\n  summarise(\n    Bias_Observed = mean(Observed) - n_unique_species,\n    Bias_Scaled_Observed = mean(Scaled_Observed) - n_unique_species,\n    Bias_Chao1 = mean(Chao1) - n_unique_species,\n    Eff_Observed = var(Observed),\n    Eff_Scaled_Observed = var(Scaled_Observed),\n    Eff_Chao1 = var(Chao1),\n    MSE_Observed = mean((Observed - n_unique_species)^2),\n    MSE_Scaled_Observed =mean((Scaled_Observed - n_unique_species)^2),\n    MSE_Chao1 = mean((Chao1 - n_unique_species)^2)\n  )\ngt(estimator_summary_50)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qyubcotyhl\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qyubcotyhl table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qyubcotyhl thead, #qyubcotyhl tbody, #qyubcotyhl tfoot, #qyubcotyhl tr, #qyubcotyhl td, #qyubcotyhl th {\n  border-style: none;\n}\n\n#qyubcotyhl p {\n  margin: 0;\n  padding: 0;\n}\n\n#qyubcotyhl .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qyubcotyhl .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qyubcotyhl .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qyubcotyhl .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qyubcotyhl .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qyubcotyhl .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qyubcotyhl .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qyubcotyhl .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qyubcotyhl .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qyubcotyhl .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qyubcotyhl .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qyubcotyhl .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qyubcotyhl .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qyubcotyhl .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qyubcotyhl .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qyubcotyhl .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qyubcotyhl .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qyubcotyhl .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qyubcotyhl .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qyubcotyhl .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qyubcotyhl .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qyubcotyhl .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qyubcotyhl .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qyubcotyhl .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qyubcotyhl .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qyubcotyhl .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qyubcotyhl .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qyubcotyhl .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qyubcotyhl .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qyubcotyhl .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qyubcotyhl .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qyubcotyhl .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qyubcotyhl .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qyubcotyhl .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qyubcotyhl .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qyubcotyhl .gt_left {\n  text-align: left;\n}\n\n#qyubcotyhl .gt_center {\n  text-align: center;\n}\n\n#qyubcotyhl .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qyubcotyhl .gt_font_normal {\n  font-weight: normal;\n}\n\n#qyubcotyhl .gt_font_bold {\n  font-weight: bold;\n}\n\n#qyubcotyhl .gt_font_italic {\n  font-style: italic;\n}\n\n#qyubcotyhl .gt_super {\n  font-size: 65%;\n}\n\n#qyubcotyhl .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qyubcotyhl .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qyubcotyhl .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qyubcotyhl .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qyubcotyhl .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qyubcotyhl .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qyubcotyhl .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qyubcotyhl .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#qyubcotyhl div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Bias_Observed\">Bias_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Bias_Scaled_Observed\">Bias_Scaled_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Bias_Chao1\">Bias_Chao1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Eff_Observed\">Eff_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Eff_Scaled_Observed\">Eff_Scaled_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Eff_Chao1\">Eff_Chao1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MSE_Observed\">MSE_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MSE_Scaled_Observed\">MSE_Scaled_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MSE_Chao1\">MSE_Chao1</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Bias_Observed\" class=\"gt_row gt_right\">-22.6048</td>\n<td headers=\"Bias_Scaled_Observed\" class=\"gt_row gt_right\">89.9207</td>\n<td headers=\"Bias_Chao1\" class=\"gt_row gt_right\">11.66395</td>\n<td headers=\"Eff_Observed\" class=\"gt_row gt_right\">21.62138</td>\n<td headers=\"Eff_Scaled_Observed\" class=\"gt_row gt_right\">49.95403</td>\n<td headers=\"Eff_Chao1\" class=\"gt_row gt_right\">149.1186</td>\n<td headers=\"MSE_Observed\" class=\"gt_row gt_right\">532.5962</td>\n<td headers=\"MSE_Scaled_Observed\" class=\"gt_row gt_right\">8135.682</td>\n<td headers=\"MSE_Chao1\" class=\"gt_row gt_right\">285.1515</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThese are still not great, but they have improved quite a lot. Chao1 still looks best.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimator_long_50 <- estimator_df_50 |>\n  pivot_longer(\n    everything(),\n    names_to = \"estimator\",\n    values_to = \"estimate\"\n  )\n\nggplot(estimator_long_50, aes(x = estimate)) +\n  geom_histogram(bins=50) +\n  geom_vline(xintercept = n_unique_species, color='red') +\n  facet_wrap(~ estimator, scales = \"free\")\n```\n\n::: {.cell-output-display}\n![](04-07_estimators_and_bootstrapping_files/figure-html/simulate_estimators_sample_50_ggplot-1.png){width=672}\n:::\n:::\n\nChao1 actually looks pretty good here - it is generating an approximately unbiased estimate of the pseudo-population, although it has a higher variance, and therefore lower efficiency, than either other estimator. \n:::\n\n## Bootstrapping {#sec-bootstrapping}\n\nIn the example above, we treated our full dataset as a pseudo-population from which our sample was taken. However, in most experiments we will only have our sample and not have the opportunity to re-sample from the population.\n\nIn these cases, we can use an approach called **bootstrapping** to assess the reliability of our estimator. We repeatedly re-sample, with replacement, from our observed dataset and re-calculate the estimator for each sample. The resulting bootstrap distribution approximates the sampling distribution of our estimator and allows us to quantify its uncertainty.\n\nFor the **invertebrates** dataset, we have 85 observations in total, let's say we want to know how accurately we can measure the **median** iron concentration for the population based on these observations.\n\n::: {.callout-exercise #ex-bootstrap_invert}\nIn your `invertebrates.qmd` Quarto file:\n\n* Read the invertebrate dataset (if you haven't already).\n* Plot the distribution of the iron concentration (the FE column) as a histogram.\n* Calculate the median iron concentration in the sample.\n* Take 1000 samples of 85 observations (the same as the number in the original sample) of iron concentration from the same data frame, with replacement, and calculate the median of each.\n  You can sample a data frame using the `slice_sample()` function with the following arguments:\n    * `data` - the data frame.\n    * `n` - the number of rows to sample, in this case 85.\n    * `replace` - TRUE or FALSE, should the sample be with or without replacement.\n* Put these values into a data frame.\n* Plot the sampling distribution of the median.\n* Calculate a 95% confidence interval for the median.\n  You can extract quantiles from the data using the function `quantile()`, with the following arguments:\n  * `x` - the data from which you want to find the quantile.\n  * `probs` - a vector of the percentiles you want to find, in this case `c(0.025, 0.975)`.\n\n::: {.callout-answer collapse=\"true\" #ex-bootstrap_invert_ans}\n\n[Read the invertebrate dataset (if you haven't already).]{.blue-text}\n\n::: {.cell}\n\n```{.r .cell-code}\ninverts <- read_csv(\"data/marine_invertebrates.csv\")\n```\n:::\n\n\n[Plot the distribution of the iron concentration (the FE column) as a histogram.]{.blue-text}\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(inverts,\n       aes(x = FE)) +\n  geom_histogram(bins=15) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](04-07_estimators_and_bootstrapping_files/figure-html/bootstrap_invert_ans2-1.png){width=672}\n:::\n:::\n\n\n[Calculate the median iron concentration in the sample.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedi <- median(pull(inverts, FE))\nprint (medi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.15\n```\n\n\n:::\n:::\n\nThe sample median is 2.15.\n\n[Take 1000 samples of 85 observations (the same as the number in the original sample) of iron concentration from the same data frame, with replacement, and calculate the median of each.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeds <- c()\nfor (i in seq_len(1000)){\n  samp <- slice_sample(inverts, n = 85, replace=TRUE)\n  samp_median <- median(pull(samp, FE))\n  meds <- c(meds, samp_median)\n}\n```\n:::\n\n\n[Put these values into a data frame]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_meds <- tibble(median = meds)\n```\n:::\n\n\n[Plot the sampling distribution of the median.]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df_meds,\n       aes(x = median)) +\n  geom_histogram(bins = 15) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](04-07_estimators_and_bootstrapping_files/figure-html/bootstrap_invert_ans6-1.png){width=672}\n:::\n:::\n\n\n[Calculate a 95% confidence interval for the median.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquans <- quantile(meds, probs = c(0.025, 0.975))\nprint (quans)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5%    97.5% \n1.412850 3.641571 \n```\n\n\n:::\n:::\n\n:::\n:::\n\nBased on this analysis, there is a fairly wide confidence interval around the median, in this case it is between 1.41 and `r(round(quans[2], 2))`. This gives a range of plausible values for the population median, based on our sample.\n\nNormally, this would be our end point, but, in this case, we do have a better estimate of the population median. In this dataset, relatively few (85) organisms had data for all our traits of interest, but 917 had data for at least iron concentration. This data is provided as `data/inverts_iron.csv`. This data will not provide a population median, but it can give us a more estimate of the population median than our 85 organism sample.\n\n::: {.callout-exercise #ex-bootstrap_invert_full}\nIn your `invertebrates.qmd` Quarto file:\n\n* Read the iron dataset `data/inverts_iron.csv`.\n* Calculate the median of the `FE` column\n* Is this value within your confidence interval?\n\n::: {.callout-answer collapse=\"true\" #ex-bootstrap_invert_full_ans}\n\n[Read the iron dataset `data/inverts_iron.csv`.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\niron_full <- read_csv(\"data/inverts_iron.csv\")\n```\n:::\n\n\n[Calculate the median of the `FE` column]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmed_iron <- median(pull(iron_full, FE))\nprint (med_iron)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.75\n```\n\n\n:::\n:::\n\n[Is this value within your confidence interval?]{.blue-text}\n\nThe median is 2.75, which is within my bootstrapped confidence interval.\n\nThe technical definition of a confidence interval in this context is: if we repeatedly collected samples and constructed 95% confidence intervals using this method, approximately 95% of those intervals would contain the true population value.\n\nLet's check.\n\nHere, our simulated data represents the time interval between someone deciding to do an unappealing task and them actually starting to do it. It is gamma distributed with a shape parameter of 2 and a scale parameter of 10 and therefore a population mean of 10 minutes. We are interested in finding the 75th percentile - the time by which 75% of people will have started the task, or equivalently, the minimum procrastination time for the slowest 25% of the population.\n\nThe true population value for the 75th percentile is 26.9263453, calculated as `qgamma(0.75, shape = 2, scale = 10)`.\n\n![Procrastination (https://xkcd.com/1906)](images/xkcd.png){#fig-bob width=\"25%\"}\n\n::: {.callout-exercise #ex-bootstrap_ci}\n\nTake a sample of 200 individuals from the population 100 times, then, within that sample, use bootstrapping with 100 replicates to calculate a 95% confidence interval for the **75th percentile** of the data. Record whether or not the confidence interval contains the true population value of 26.9263453.\nAcross the 100 samples, calculate the proportion of bootstrap confidence intervals which contain the true population value.\n\n::: {.callout-answer collapse=\"true\" #ex-bootstrap_ci_ans}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the population 0.75 quantile\npop <- qgamma(0.75, shape = 2, scale = 10)\n\n# Make a vector to store the results\nresults <- c()\n# Repeat 100 times\nfor (i in seq_len(100)){\n  # Sample 200 individuals\n  samp <- rgamma(200, shape = 2, scale = 10)\n  # Put the results into a data frame\n  samp_df <- tibble(time = samp)\n  # Make a vector to store the quantiles\n  quans <- c()\n  # Repeat 100 times\n  for (j in seq_len(100)){\n    # Sample 200 individuals with replacement\n    bootstrap <- slice_sample(samp_df, n = 200, replace = TRUE)\n    # Calculate the 0.75 quantile\n    quan75 <- quantile(pull(bootstrap, time), 0.75)\n    # Store the result\n    quans <- c(quans, quan75)\n  }\n  # Find the confidence interval\n  ci <- quantile(quans, c(0.025, 0.975))\n  # Check if the population value is in the CI\n  has_pop <- between(pop, ci[1], ci[2])\n  # Append to the results vector\n  results <- c(results, has_pop)\n}\n# Calculate the percentage\nperc <- sum(results) / 100\nprint (perc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9\n```\n\n\n:::\n:::\n\nThe bootstrapped confidence interval for the estimator contains the population value 90% of the time.\n:::\n:::\n## Review {#sec-summary_0407}\n\n[↑ top](#)\n\n::: {.callout-note #note-summary_0407}\n\n### Summary\n\n\n:::\n\nFor this part of the practical, the main files you have edited are:\n\n\nThese are the files you should select when making your Git commit.\n\n::: {.callout-tip}\n## Commit your changes\nRemember to save your progress regularly by committing your changes with Git.\n\n1. Save your changes to the files above in RStudio with the `Save` button.\n2. Render any Quarto documents with the `Render` button.\n3. Open the `Git` tab in RStudio.\n4. Tick the files listed above, don't worry about any others.\n5. Click `Commit` and write a short message in the `Commit message` describing your changes, something like e.g. \"Practical 1 part 1\" is sufficient, then click `Commit`. Close the `Commit` popup.\n\n:::\n\t\n\n\n::: {.callout-tip}\n## Push your changes\n\nNow you are at the end of the practical, commit your changes with Git and push them to GitHub.\n\n1. Click `Push` in the Git panel to save the changes to GitHub.\n2. Enter your UserName and your Personal Access Token. If you don't have your token or it doesn't work, visit [this page](https://github.com/settings/personal-access-tokens) while logged into your GitHub account, click on the {{< meta course-title >}} token and choose `Regenerate token`.\n3. Visit your GitHub account and check that your changes are there.\n:::\n\t\n\n\n",
    "supporting": [
      "04-07_estimators_and_bootstrapping_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}