---
format: html
practical: Practical_6_Programming_and_Further_Statistics
doc-id: "0604"
author: "Katy Brown"
---
# Part 4: Power Analysis {#sec-p4_power_analysis}

::: {.callout-note .partmenu #parts-0604}
## Sections

:::

:::{.callout-tip .objectives #objectives-0604}

#### Learning objectives
By the end of this part of the practical you will have:

:::
```{r libraries0604}
library(tidyverse)
library(gt)
library(effectsize)
library(pwr)
library(patchwork)
```



```{r}
by_indiv <- read_csv("data/by_individual.csv")

by_indiv <- by_indiv |>
  filter(Cancer_Category %in% c(
    "digestive",
    "respiratory",
    "brain",
    "breast",
    "gynaecological",
    "urinary"
  ))
```

```{r}
by_indiv_grouped <- by_indiv |>
  group_by(Cancer_Category)

by_indiv_sum <- by_indiv_grouped |>
  summarise(
    n_individuals = n(),
    mean_age = mean(Age),
    median_age = median(Age),
    sd_age = sd(Age)
  )
```

```{r}
ggplot(
  data = by_indiv,
  aes(x = Age, fill = Cancer_Category)
) +
  geom_density(show.legend = FALSE) +
  facet_wrap(~Cancer_Category)
```

```{r}
dig_res <- by_indiv |>
  filter(Cancer_Category %in% c("digestive", "respiratory"))
```

```{r}
  n1 <- by_indiv_sum |>
    filter(Cancer_Category == "digestive") |>
    pull(n_individuals)
  n2 <- by_indiv_sum |>
    filter(Cancer_Category == "respiratory") |>
    pull(n_individuals)
  s1 <- by_indiv_sum |>
    filter(Cancer_Category == "digestive") |>
    pull(sd_age)
  s2 <- by_indiv_sum |>
    filter(Cancer_Category == "respiratory") |>
    pull(sd_age)
```

```{r}
pooled_sd <- function(n1, n2, s1, s2) {
  pooled_sd <- sqrt(
    ((n1 - 1) * s1^2 + (n2 - 1) * s2^2) /
      (n1 + n2 - 2)
  )
  return (pooled_sd)
}
pooled <- pooled_sd(n1, n2, s1, s2)
```


```{r}
effect_size_sd <- cohens_d(
  Age ~ Cancer_Category,
  data = dig_res
)

effect_size_years <- effect_size_sd$Cohens_d * pooled
```

```{r}
digestive_mean <- by_indiv_sum |>
  filter(Cancer_Category == "digestive") |>
  pull(mean_age)

respiratory_mean <- by_indiv_sum |>
  filter(Cancer_Category == "respiratory") |>
  pull(mean_age)

observed_effect_size <- digestive_mean - respiratory_mean
```

```{r}
minimum_effect <- pwr.t2n.test(
  n1 = n1,
  n2 = n2,
  sig.level = 0.05,
  power = 0.80,
  alternative = "two.sided"
)
minimum_effect_years <- minimum_effect$d * pooled_sd(n1, n2, s1, s2)

ttest_age_dr <- t.test(Age ~ Cancer_Category, dig_res)
```

```{r}
sample_sizes <- seq(10, 1000, 10)

pvals <- c()
oes <- c()
des <- c()
for (ss in sample_sizes){
  sample_df <- dig_res |>
    group_by(Cancer_Category) |>
    slice_sample(n = ss, replace=FALSE)

  summary_sample <- sample_df |>
    summarise(
      n_individuals = n(),
      mean_age = mean(Age),
      median_age = median(Age),
      sd_age = sd(Age)
    )
  n1 <- summary_sample |>
    filter(Cancer_Category == "digestive") |>
    pull(n_individuals)
  n2 <- summary_sample |>
    filter(Cancer_Category == "respiratory") |>
    pull(n_individuals)
  s1 <- summary_sample |>
    filter(Cancer_Category == "digestive") |>
    pull(sd_age)
  s2 <- summary_sample |>
    filter(Cancer_Category == "respiratory") |>
    pull(sd_age)

  psd <- pooled_sd(n1, n2, s1, s2)
  
  digestive_mean <- summary_sample |>
    filter(Cancer_Category == "digestive") |>
    pull(mean_age)
  
  respiratory_mean <- summary_sample |>
    filter(Cancer_Category == "respiratory") |>
    pull(mean_age)

  observed_effect_size_years <- abs(digestive_mean - respiratory_mean)
  
  detectable_effect_size <- pwr.t2n.test(
    n1 = n1,
    n2 = n2,
    sig.level = 0.05,
    power = 0.80,
    alternative = "two.sided"
  )
  detectable_effect_size_years <- detectable_effect_size$d * psd

  ttest_result <- t.test(
    Age ~ Cancer_Category,
    sample_df
  )
  pvals <- c(pvals, ttest_result$p.value)
  oes <- c(oes, observed_effect_size_years)
  des <- c(des, detectable_effect_size_years)
}
```

```{r}
ss_results <- tibble(sample_size=sample_sizes,
                     observed_effect_size=oes,
                     detectable_effect_size=des)

ss_piv <- ss_results |>
  pivot_longer(
    cols = c(observed_effect_size, detectable_effect_size),
    names_to = "metric",
  )
```

```{r}
p1 <- ggplot(ss_piv,
       aes(x = sample_size,
           y = value,
           color=metric)) +
  geom_line()

ss_pval <- tibble(sample_size=sample_sizes,
                  pvalue=pvals)

p2 <- ggplot(ss_pval,
       aes(x = sample_size,
           y = pvalue)) +
  geom_line() +
  geom_hline(yintercept=0.05,
             linetype='dashed')

p1 / p2
```


## Review {#sec-summary_0604}

[↑ top](#)

::: {.callout-note #note-summary_0604}

### Summary

You have:

:::

For this part of the practical, the main files you have edited are:


These are the files you should select when making your Git commit.

{{< include ../includes/git_commit.qmd >}}

{{< include ../includes/git_push.qmd >}}
