{
  "hash": "29c6b00a6b25f2164434c70bf2cb9362",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: html\npractical: Practical_4_Statistics\ndoc-id: \"0402\"\n---\n\n\n\n# Part 2: Hypothesis Testing \n\n## Examining data\n\nNow we can start to test some hypotheses based on this dataset.\n\nFor now, let's concentrate on a single species, the \"bronze furrow bee\" *Halictus tumulorum*. This is a relatively common bee species in the UK. It is a species of sweat bee, named because they are often attracted to sweat (although the UK ones usually aren't).\n\n![*Halictus tumulorum*](images/bee.jpg){#fig-bee width=\"50%\"}\n\nWe can plot the distribution of this bee on a map, using the methods we learned in @sec-p3_visualisation.\n\nFirst, let's filter our insect counts data frame to keep only the observations for this species.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspp_counts <- insect_counts |>\n  filter(species == \"Halictus tumulorum\")\ngt(head(spp_counts))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"zhtkbxklcg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zhtkbxklcg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zhtkbxklcg thead, #zhtkbxklcg tbody, #zhtkbxklcg tfoot, #zhtkbxklcg tr, #zhtkbxklcg td, #zhtkbxklcg th {\n  border-style: none;\n}\n\n#zhtkbxklcg p {\n  margin: 0;\n  padding: 0;\n}\n\n#zhtkbxklcg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zhtkbxklcg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zhtkbxklcg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zhtkbxklcg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zhtkbxklcg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zhtkbxklcg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zhtkbxklcg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zhtkbxklcg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zhtkbxklcg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zhtkbxklcg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zhtkbxklcg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zhtkbxklcg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zhtkbxklcg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zhtkbxklcg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zhtkbxklcg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zhtkbxklcg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zhtkbxklcg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zhtkbxklcg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zhtkbxklcg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zhtkbxklcg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zhtkbxklcg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zhtkbxklcg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zhtkbxklcg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zhtkbxklcg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zhtkbxklcg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zhtkbxklcg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zhtkbxklcg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zhtkbxklcg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zhtkbxklcg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zhtkbxklcg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zhtkbxklcg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zhtkbxklcg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zhtkbxklcg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zhtkbxklcg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zhtkbxklcg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zhtkbxklcg .gt_left {\n  text-align: left;\n}\n\n#zhtkbxklcg .gt_center {\n  text-align: center;\n}\n\n#zhtkbxklcg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zhtkbxklcg .gt_font_normal {\n  font-weight: normal;\n}\n\n#zhtkbxklcg .gt_font_bold {\n  font-weight: bold;\n}\n\n#zhtkbxklcg .gt_font_italic {\n  font-style: italic;\n}\n\n#zhtkbxklcg .gt_super {\n  font-size: 65%;\n}\n\n#zhtkbxklcg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zhtkbxklcg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zhtkbxklcg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zhtkbxklcg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zhtkbxklcg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zhtkbxklcg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zhtkbxklcg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zhtkbxklcg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zhtkbxklcg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"x1km_square\">x1km_square</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"species\">species</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_observed\">n_observed</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC0429</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Halictus tumulorum</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC2313</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Halictus tumulorum</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC5762</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Halictus tumulorum</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC7158</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Halictus tumulorum</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NJ0327</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Halictus tumulorum</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NJ6415</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Halictus tumulorum</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">0</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nWe can create a boolean (see @sec-variable_types) column showing if *H. tumulorum* is detected or undetected at each site using `mutate()` based on the `n_observed` column - if `n_observed` is > 0, this species was detected.\n\nWe also need to join with the site metadata table to get the additional info about the sampling sites.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspp_presence <- spp_counts |>\n  mutate(detected = n_observed > 0) |>\n  left_join(site_metadata)\n\ngt(head(spp_presence))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"tyxbnpephs\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tyxbnpephs table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tyxbnpephs thead, #tyxbnpephs tbody, #tyxbnpephs tfoot, #tyxbnpephs tr, #tyxbnpephs td, #tyxbnpephs th {\n  border-style: none;\n}\n\n#tyxbnpephs p {\n  margin: 0;\n  padding: 0;\n}\n\n#tyxbnpephs .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tyxbnpephs .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tyxbnpephs .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tyxbnpephs .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tyxbnpephs .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tyxbnpephs .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tyxbnpephs .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tyxbnpephs .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tyxbnpephs .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tyxbnpephs .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tyxbnpephs .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tyxbnpephs .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tyxbnpephs .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tyxbnpephs .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tyxbnpephs .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tyxbnpephs .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tyxbnpephs .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tyxbnpephs .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tyxbnpephs .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tyxbnpephs .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tyxbnpephs .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tyxbnpephs .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tyxbnpephs .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tyxbnpephs .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tyxbnpephs .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tyxbnpephs .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tyxbnpephs .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tyxbnpephs .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tyxbnpephs .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tyxbnpephs .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tyxbnpephs .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tyxbnpephs .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tyxbnpephs .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tyxbnpephs .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tyxbnpephs .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tyxbnpephs .gt_left {\n  text-align: left;\n}\n\n#tyxbnpephs .gt_center {\n  text-align: center;\n}\n\n#tyxbnpephs .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tyxbnpephs .gt_font_normal {\n  font-weight: normal;\n}\n\n#tyxbnpephs .gt_font_bold {\n  font-weight: bold;\n}\n\n#tyxbnpephs .gt_font_italic {\n  font-style: italic;\n}\n\n#tyxbnpephs .gt_super {\n  font-size: 65%;\n}\n\n#tyxbnpephs .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tyxbnpephs .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tyxbnpephs .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tyxbnpephs .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tyxbnpephs .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tyxbnpephs .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tyxbnpephs .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#tyxbnpephs .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#tyxbnpephs div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"x1km_square\">x1km_square</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"species\">species</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_observed\">n_observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"detected\">detected</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"country\">country</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"longitude\">longitude</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"latitude\">latitude</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"habitat\">habitat</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"land_cover\">land_cover</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dominant_species\">dominant_species</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dominant_family\">dominant_family</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"annual_mean_temp\">annual_mean_temp</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"max_temp_warmest_month\">max_temp_warmest_month</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"min_temp_coldest_month\">min_temp_coldest_month</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"temp_annual_range\">temp_annual_range</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"annual_total_prec\">annual_total_prec</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"total_prec_wettest_month\">total_prec_wettest_month</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"total_prec_driest_month\">total_prec_driest_month</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_months_at_least_15C\">n_months_at_least_15C</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"elevation\">elevation</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC0429</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Halictus tumulorum</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">0</td>\n<td headers=\"detected\" class=\"gt_row gt_center\">FALSE</td>\n<td headers=\"country\" class=\"gt_row gt_left\">Scotland</td>\n<td headers=\"longitude\" class=\"gt_row gt_right\">-5.329446</td>\n<td headers=\"latitude\" class=\"gt_row gt_right\">58.21076</td>\n<td headers=\"habitat\" class=\"gt_row gt_left\">H23 - Wet and dry heathland/ dry heather moorland</td>\n<td headers=\"land_cover\" class=\"gt_row gt_left\">semi-natural</td>\n<td headers=\"dominant_species\" class=\"gt_row gt_left\">Melanogaster hirtella</td>\n<td headers=\"dominant_family\" class=\"gt_row gt_left\">Syrphidae</td>\n<td headers=\"annual_mean_temp\" class=\"gt_row gt_right\">8.159880</td>\n<td headers=\"max_temp_warmest_month\" class=\"gt_row gt_right\">15.94227</td>\n<td headers=\"min_temp_coldest_month\" class=\"gt_row gt_right\">1.368041</td>\n<td headers=\"temp_annual_range\" class=\"gt_row gt_right\">14.57423</td>\n<td headers=\"annual_total_prec\" class=\"gt_row gt_right\">1595</td>\n<td headers=\"total_prec_wettest_month\" class=\"gt_row gt_right\">192</td>\n<td headers=\"total_prec_driest_month\" class=\"gt_row gt_right\">73</td>\n<td headers=\"n_months_at_least_15C\" class=\"gt_row gt_right\">0</td>\n<td headers=\"elevation\" class=\"gt_row gt_right\">78</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC2313</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Halictus tumulorum</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">0</td>\n<td headers=\"detected\" class=\"gt_row gt_center\">FALSE</td>\n<td headers=\"country\" class=\"gt_row gt_left\">Scotland</td>\n<td headers=\"longitude\" class=\"gt_row gt_right\">-4.994481</td>\n<td headers=\"latitude\" class=\"gt_row gt_right\">58.07527</td>\n<td headers=\"habitat\" class=\"gt_row gt_left\">H23 - Wet and dry heathland/ dry heather moorland</td>\n<td headers=\"land_cover\" class=\"gt_row gt_left\">semi-natural</td>\n<td headers=\"dominant_species\" class=\"gt_row gt_left\">Melanogaster hirtella</td>\n<td headers=\"dominant_family\" class=\"gt_row gt_left\">Syrphidae</td>\n<td headers=\"annual_mean_temp\" class=\"gt_row gt_right\">6.794854</td>\n<td headers=\"max_temp_warmest_month\" class=\"gt_row gt_right\">15.76625</td>\n<td headers=\"min_temp_coldest_month\" class=\"gt_row gt_right\">-0.876000</td>\n<td headers=\"temp_annual_range\" class=\"gt_row gt_right\">16.64225</td>\n<td headers=\"annual_total_prec\" class=\"gt_row gt_right\">2016</td>\n<td headers=\"total_prec_wettest_month\" class=\"gt_row gt_right\">233</td>\n<td headers=\"total_prec_driest_month\" class=\"gt_row gt_right\">100</td>\n<td headers=\"n_months_at_least_15C\" class=\"gt_row gt_right\">0</td>\n<td headers=\"elevation\" class=\"gt_row gt_right\">309</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC5762</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Halictus tumulorum</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">0</td>\n<td headers=\"detected\" class=\"gt_row gt_center\">FALSE</td>\n<td headers=\"country\" class=\"gt_row gt_left\">Scotland</td>\n<td headers=\"longitude\" class=\"gt_row gt_right\">-4.448844</td>\n<td headers=\"latitude\" class=\"gt_row gt_right\">58.52721</td>\n<td headers=\"habitat\" class=\"gt_row gt_left\">H23 - Wet and dry heathland/ dry heather moorland</td>\n<td headers=\"land_cover\" class=\"gt_row gt_left\">semi-natural</td>\n<td headers=\"dominant_species\" class=\"gt_row gt_left\">Bombus jonellus</td>\n<td headers=\"dominant_family\" class=\"gt_row gt_left\">Syrphidae</td>\n<td headers=\"annual_mean_temp\" class=\"gt_row gt_right\">7.828012</td>\n<td headers=\"max_temp_warmest_month\" class=\"gt_row gt_right\">15.79010</td>\n<td headers=\"min_temp_coldest_month\" class=\"gt_row gt_right\">1.140594</td>\n<td headers=\"temp_annual_range\" class=\"gt_row gt_right\">14.64951</td>\n<td headers=\"annual_total_prec\" class=\"gt_row gt_right\">1254</td>\n<td headers=\"total_prec_wettest_month\" class=\"gt_row gt_right\">147</td>\n<td headers=\"total_prec_driest_month\" class=\"gt_row gt_right\">65</td>\n<td headers=\"n_months_at_least_15C\" class=\"gt_row gt_right\">0</td>\n<td headers=\"elevation\" class=\"gt_row gt_right\">86</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC7158</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Halictus tumulorum</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">0</td>\n<td headers=\"detected\" class=\"gt_row gt_center\">FALSE</td>\n<td headers=\"country\" class=\"gt_row gt_left\">Scotland</td>\n<td headers=\"longitude\" class=\"gt_row gt_right\">-4.206385</td>\n<td headers=\"latitude\" class=\"gt_row gt_right\">58.49567</td>\n<td headers=\"habitat\" class=\"gt_row gt_left\">H20 - Bracken dominated glades or hillsides</td>\n<td headers=\"land_cover\" class=\"gt_row gt_left\">semi-natural</td>\n<td headers=\"dominant_species\" class=\"gt_row gt_left\">Lasioglossum fratellum</td>\n<td headers=\"dominant_family\" class=\"gt_row gt_left\">Halictidae</td>\n<td headers=\"annual_mean_temp\" class=\"gt_row gt_right\">7.458521</td>\n<td headers=\"max_temp_warmest_month\" class=\"gt_row gt_right\">15.89600</td>\n<td headers=\"min_temp_coldest_month\" class=\"gt_row gt_right\">0.400750</td>\n<td headers=\"temp_annual_range\" class=\"gt_row gt_right\">15.49525</td>\n<td headers=\"annual_total_prec\" class=\"gt_row gt_right\">1280</td>\n<td headers=\"total_prec_wettest_month\" class=\"gt_row gt_right\">146</td>\n<td headers=\"total_prec_driest_month\" class=\"gt_row gt_right\">70</td>\n<td headers=\"n_months_at_least_15C\" class=\"gt_row gt_right\">0</td>\n<td headers=\"elevation\" class=\"gt_row gt_right\">146</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NJ0327</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Halictus tumulorum</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">0</td>\n<td headers=\"detected\" class=\"gt_row gt_center\">FALSE</td>\n<td headers=\"country\" class=\"gt_row gt_left\">Scotland</td>\n<td headers=\"longitude\" class=\"gt_row gt_right\">-3.604334</td>\n<td headers=\"latitude\" class=\"gt_row gt_right\">57.32778</td>\n<td headers=\"habitat\" class=\"gt_row gt_left\">H27 - Mature coniferous woodland</td>\n<td headers=\"land_cover\" class=\"gt_row gt_left\">semi-natural</td>\n<td headers=\"dominant_species\" class=\"gt_row gt_left\">Sericomyia silentis</td>\n<td headers=\"dominant_family\" class=\"gt_row gt_left\">Apidae</td>\n<td headers=\"annual_mean_temp\" class=\"gt_row gt_right\">6.451479</td>\n<td headers=\"max_temp_warmest_month\" class=\"gt_row gt_right\">17.11475</td>\n<td headers=\"min_temp_coldest_month\" class=\"gt_row gt_right\">-1.765750</td>\n<td headers=\"temp_annual_range\" class=\"gt_row gt_right\">18.88050</td>\n<td headers=\"annual_total_prec\" class=\"gt_row gt_right\">1008</td>\n<td headers=\"total_prec_wettest_month\" class=\"gt_row gt_right\">120</td>\n<td headers=\"total_prec_driest_month\" class=\"gt_row gt_right\">59</td>\n<td headers=\"n_months_at_least_15C\" class=\"gt_row gt_right\">0</td>\n<td headers=\"elevation\" class=\"gt_row gt_right\">376</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NJ6415</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Halictus tumulorum</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">0</td>\n<td headers=\"detected\" class=\"gt_row gt_center\">FALSE</td>\n<td headers=\"country\" class=\"gt_row gt_left\">Scotland</td>\n<td headers=\"longitude\" class=\"gt_row gt_right\">-2.589628</td>\n<td headers=\"latitude\" class=\"gt_row gt_right\">57.22883</td>\n<td headers=\"habitat\" class=\"gt_row gt_left\">H23 - Wet and dry heathland/ dry heather moorland</td>\n<td headers=\"land_cover\" class=\"gt_row gt_left\">semi-natural</td>\n<td headers=\"dominant_species\" class=\"gt_row gt_left\">Bombus lucorum</td>\n<td headers=\"dominant_family\" class=\"gt_row gt_left\">Apidae</td>\n<td headers=\"annual_mean_temp\" class=\"gt_row gt_right\">7.405677</td>\n<td headers=\"max_temp_warmest_month\" class=\"gt_row gt_right\">17.86550</td>\n<td headers=\"min_temp_coldest_month\" class=\"gt_row gt_right\">-0.746000</td>\n<td headers=\"temp_annual_range\" class=\"gt_row gt_right\">18.61150</td>\n<td headers=\"annual_total_prec\" class=\"gt_row gt_right\">804</td>\n<td headers=\"total_prec_wettest_month\" class=\"gt_row gt_right\">85</td>\n<td headers=\"total_prec_driest_month\" class=\"gt_row gt_right\">54</td>\n<td headers=\"n_months_at_least_15C\" class=\"gt_row gt_right\">0</td>\n<td headers=\"elevation\" class=\"gt_row gt_right\">207</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nNow let's draw our map. We want a scatter plot (`geom_point()`) with longitude on the x axis and latitude on the y axis. We can colour the dots based on whether *H. tumulorum* is present or absent.\n\nWe can use the function `annotation_borders()` with the argument `regions = \"UK\"` to generate a UK map. [Remember](@sec-adding_map_features) that `coord_quickmap()` adjusts the axis co-ordinates so the map doesn't appear skewed. `theme_bw()` is optional - it's just aesthetics, making the background white instead of grey.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspp_map <- ggplot(spp_presence, aes(\n  x = longitude, y = latitude,\n  color = detected\n)) +\n  geom_point() +\n  annotation_borders(regions = \"UK\", linewidth = 0.2) +\n  coord_quickmap() +\n  theme_bw()\n\nspp_map\n```\n\n::: {.cell-output-display}\n![](04-02_hypothesis_testing_files/figure-html/map_spp-1.png){width=672}\n:::\n:::\n\n\nThese bees seem to favour the south-east of the UK - possibly to avoid the coldest regions?\n\nWe have a column in our site metadata data frame which can help us establish if this is true - the `min_temp_coldest_month` column. This is a BIOCLIM climate variable describing the lowest temperature in the coldest month in the map square and is the mean from 1970-2000. Technically, the lowest tempeature in the coldest month might not be the overall lowest temperature, however, for brevity from here forward we will refer to this just as **minimum temperature** (rather than mean lowest temperature in coldest month).\n\nWe can compare this minimum temperature for the sites where the bees are present and absent using a box plot.\n\n:::{.callout-exercise #ex-boxplot_bees}\nIn your `pollinators.qmd` Quarto document, plot a box plot showing the value of `min_temp_coldest_month` in your `spp_presence` data frame for the regions with and without these bees (i.e. based on the `detected` column).\n\nThe R function `geom_boxplot()` draws a box plot. The `aes` function for this type of plot requires a categorical x variable and a continuous y variable as arguments - so you would use the argument `x = detected` and `y = min_temp_coldest_month`. \n\n:::{.callout-answer collapse=\"true\" #ex-boxplot_bees_ans}\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  spp_presence,\n  aes(x = detected, y = min_temp_coldest_month, fill = detected)\n) +\n  geom_boxplot() +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](04-02_hypothesis_testing_files/figure-html/boxplot_spp-1.png){width=672}\n:::\n:::\n\n:::\n:::\n\nBased on this box plot, perhaps these bees don't like the cold.\n\nLet's summarise our data frame, for convenience later. We can calculate the number of observations, mean, standard deviation and variance for `min_temp_coldest_month` for each sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspp_summary <- spp_presence |>\n  group_by(detected) |>\n  summarise(\n    count = n(),\n    mean = mean(min_temp_coldest_month),\n    var = var(min_temp_coldest_month),\n    sd = sd(min_temp_coldest_month)\n  )\n\npresent <- spp_summary |> filter(detected == TRUE)\nabsent <- spp_summary |> filter(detected == FALSE)\ngt(spp_summary)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"iaondzizhb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#iaondzizhb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#iaondzizhb thead, #iaondzizhb tbody, #iaondzizhb tfoot, #iaondzizhb tr, #iaondzizhb td, #iaondzizhb th {\n  border-style: none;\n}\n\n#iaondzizhb p {\n  margin: 0;\n  padding: 0;\n}\n\n#iaondzizhb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#iaondzizhb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#iaondzizhb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#iaondzizhb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#iaondzizhb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iaondzizhb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iaondzizhb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iaondzizhb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#iaondzizhb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#iaondzizhb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#iaondzizhb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#iaondzizhb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#iaondzizhb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#iaondzizhb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#iaondzizhb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#iaondzizhb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#iaondzizhb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#iaondzizhb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#iaondzizhb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iaondzizhb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#iaondzizhb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#iaondzizhb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#iaondzizhb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iaondzizhb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#iaondzizhb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#iaondzizhb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iaondzizhb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iaondzizhb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#iaondzizhb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iaondzizhb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#iaondzizhb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iaondzizhb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iaondzizhb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iaondzizhb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iaondzizhb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iaondzizhb .gt_left {\n  text-align: left;\n}\n\n#iaondzizhb .gt_center {\n  text-align: center;\n}\n\n#iaondzizhb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#iaondzizhb .gt_font_normal {\n  font-weight: normal;\n}\n\n#iaondzizhb .gt_font_bold {\n  font-weight: bold;\n}\n\n#iaondzizhb .gt_font_italic {\n  font-style: italic;\n}\n\n#iaondzizhb .gt_super {\n  font-size: 65%;\n}\n\n#iaondzizhb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#iaondzizhb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#iaondzizhb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#iaondzizhb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#iaondzizhb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#iaondzizhb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#iaondzizhb .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#iaondzizhb .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#iaondzizhb div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"detected\">detected</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"count\">count</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean\">mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"var\">var</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd\">sd</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"detected\" class=\"gt_row gt_center\">FALSE</td>\n<td headers=\"count\" class=\"gt_row gt_right\">37</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">0.1128519</td>\n<td headers=\"var\" class=\"gt_row gt_right\">1.1675485</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">1.0805316</td></tr>\n    <tr><td headers=\"detected\" class=\"gt_row gt_center\">TRUE</td>\n<td headers=\"count\" class=\"gt_row gt_right\">39</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">1.3747955</td>\n<td headers=\"var\" class=\"gt_row gt_right\">0.6898238</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">0.8305563</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Choosing a test\n\nNow we have a hypothesis to investigate:\n\n* Alternative hypothesis: Minimum temperature is different at sites where *H. tumulorum* is present than at sites where it is absent.\n* Null hypothesis: Mean minimum temperature is the same at sites where *H. tumulorum* is present and absent.\n\n:::{.callout-important #note-harking}\nWe developed our hypothesis that *H. tumulorum* prefers sites with a higher minimum temperature after looking at these data, and we're about to use the same data to test that hypothesis. This is sometimes called **HARKing** — Hypothesizing After the Results are Known.\n\nIdeally, we would now test our hypothesis using a new dataset. However, given the limitations of this practical, we will instead look for evidence of an association in this dataset.\n:::\n\nWe have a **continuous response variable** and a **categorical explanatory variable** - maybe we can use a t-test.\n\nIf the following assumptions are true, we can use a two-sample, two-sided, unpaired t-test:\n\n* The values of this measurement in each of the two groups should be drawn from approximately normal distributions with approximately equal variance.\n* The observations should be independent of one another. \n\nIn our dataset, each observation represents a different 1-km sampling square. We will assume that observations from different squares are sufficiently independent for this analysis.\n\nWe can check the other two assumptions directly.\n\n::: {.callout-exercise #ex-poms_distributions}\n\nIn your `pollinators.qmd` Quarto file:\n\n* Plot a histogram of the distribution of `min_temp_coldest_month` for the sites with and without *H. tumulorum*. Use the function `facet_wrap()` to separate the sites where `detected` is TRUE versus FALSE.\n\n::: {.callout-answer #ex-poms_distributions_ans}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(spp_presence, aes(x = min_temp_coldest_month, fill = detected)) +\n  geom_histogram(bins = 10) +\n  ggtitle(\"Temperature\") +\n  facet_wrap(~detected, scales = \"free\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](04-02_hypothesis_testing_files/figure-html/poms_distributions_ans-1.png){width=672}\n:::\n:::\n\n:::\n:::\n\nThese are clearly not perfectly normally distributed but, given that we only have a sample size of 39 for \"present\" sites and  37 for \"absent\" sites, it is difficult to tell if they are drawn from a normal distribution. \n\nLater, we will learn different ways to check for normality but for now, given that they do look reasonably symmetrical, unimodal and without extreme outliers, we will treat the normality assumption as reasonable for this analysis.\n\nWe have our variances already in the summary table above: 0.6898 for present and 1.1675 for absent. Although the variances are not identical, they are similar. There is no strict threshold for deciding whether variances are sufficiently similar. As a rough rule of thumb for this practical, we will consider a ratio of the largest to smallest variance below 2 to indicate reasonably similar variances, particularly when group sizes are similar.\n\nOur group sizes are 39 and 37 and our ratio is 1.6925 - so we can proceed with our t-test.\n\n::: {.callout-note .extension #ext-sim_norm_poms}\n\n### Extension: Plotting similar data\n\nFor fun (maybe not everyone's kind of fun), let's try simulating data drawn from a normal distribution with 39 samples, 12 times, with the same mean and standard deviation as our \"present\" data, and see how it looks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find the relevant statistics - number of samples, mean and sd\nn_samples <- pull(present, count)\nmean_detected <- pull(present, mean)\nsd_detected <- pull(present, sd)\n\n# Create a data frame to store the results\ndf_norm <- tibble()\n\n# Repeat 12 times\nfor (i in seq_len(12)) {\n  # Generate a random sample\n  norm <- rnorm(\n    n_samples,\n    mean = mean_detected,\n    sd = sd_detected\n  )\n  # Put it into a data frame row\n  this_sim <- tibble(\n    simulation = i,\n    temp = norm\n  )\n  # Add the row to the results data frame\n  df_norm <- bind_rows(df_norm, this_sim)\n}\n\n# Plot the results\nggplot(df_norm, aes(x = temp)) +\n  geom_histogram(bins = 10) +\n  facet_wrap(~simulation)\n```\n\n::: {.cell-output-display}\n![](04-02_hypothesis_testing_files/figure-html/sim_norm_poms-1.png){width=672}\n:::\n:::\n\n\nSome of these look pretty similar to our data - we at least can't say that our data is definitely not drawn from a normal distribution, based on this analysis.\n\n:::\n\n## Running statistical tests in R\n\nIn R statistical functions, `~` is used to specify a formula describing the relationship between variables.\n\nThe basic structure is `response ~ explanatory`, which you can read as \"response as a function of explanatory variable\".\n\nIn our example above, the response variable is minimum temperature and the explanatory variable is presence or absence of *H. tumulorum* bees. \n\n:::{.callout-note #note-explanatory}\n\n\"Explanatory\" here means the variable we're using to explain/describe variation in the response statistically, not necessarily a biological cause - we're not claiming that the bees are affecting the temperature.\n\n:::\n\nTo run a t-test in R, the function is `t.test()`. \n\nThe first argument is our formula - `response ~ explanatory`, or in this case, `min_temp_coldest_month ~ detected`.\nWe need two additional arguments:\n* `data = spp_presence` - this is the data frame containing the data.\n* `var.equal = TRUE` - run a standard t-test, the default in R is to assume unequal variance and run a Welch's t-test.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspp_ttest <- t.test(min_temp_coldest_month ~ detected,\n  data = spp_presence,\n  var.equal = TRUE\n)\nprint(spp_ttest)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  min_temp_coldest_month by detected\nt = -5.7259, df = 74, p-value = 2.073e-07\nalternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0\n95 percent confidence interval:\n -1.7010818 -0.8228055\nsample estimates:\nmean in group FALSE  mean in group TRUE \n          0.1128519           1.3747955 \n```\n\n\n:::\n:::\n\n\nHere we have a p-value of 2.07e-07, meaning we can reject our null hypothesis. There is evidence that mean minimum temperature is different at sites where *H. tumulorum* is present than at sites where it is absent. This doesn't mean that our alternative hypothesis is definitely true for the population, but based on this sample the evidence supports it.\n\n### Confidence intervals\n\nIt is also worth looking at our **confidence interval** here.\n\nLower: -1.7011\n\nUpper: -0.8228\n\nA 95% confidence interval means that if we repeatedly sampled from the population and calculated a 95% confidence interval in the same way each time, 95% of those intervals would contain the true population value. In this case, the true population value is the true difference between the mean minimum annual temperature at sites where *H. tumulorum* is present and at sites where it is absent.\n\nFor a two-sided test at the 5% significance level, if the 95% confidence interval for the difference between the means does not contain zero, we can reject the null hypothesis that the mean difference is zero. Here, our confidence interval does not contain zero, which agrees with the conclusion based on the p-value.\n\n::: {.callout-exercise #ex-cis}\n\n*\"A 95% confidence interval means that if we repeatedly sampled from the population and calculated a 95% confidence interval in the same way each time, 95% of those intervals would contain the true population value. In this case, the true population value is the true difference between the mean minimum annual temperature at sites where H. tumulorum is present and at sites where it is absent.\"*\n\nLet's check using simulation. If we simulate samples from populations with known means, we know the \"true\" difference between means of the source populations.\n\nIn your `pollinators.qmd` Quarto file:\n\n* 1,000 times:\n  * Simulate two samples drawn from a normal distribution:\n      * one with the same mean, standard deviation and sample size as the sites with *H. tumulorum*\n      * one with the same mean, standard deviation and sample size as the sites without *H. tumulorum*. \n  * Put the data for the two samples into a data frame in long format as follows:\n\n  \n\n\n  ::: {.cell}\n  \n  ```{.r .cell-code}\n  # Let's assume your vectors are in variables named s1 and s2\n  # rep is used to add the sample names to the data frame\n  # by repeating \"sample_1\" and then \"sample_2\".\n  \n  df <- tibble(\n  sample = c(\n    rep(\"sample_1\", length(s1)),\n    rep(\"sample_2\", length(s2))\n  ),\n  min_temp_coldest_month = c(s1, s2)\n  )\n  ```\n  :::\n\n  * For each pair of simulated samples, use a t-test to calculate the difference between the sample means and its 95% confidence interval.\n  * Extract the confidence interval\n\n  \n\n\n  ::: {.cell}\n  \n  ```{.r .cell-code}\n  # If the result of your t-test is stored as ttest_res\n  ci_lower <- ttest_res$conf.int[1]\n  ci_upper <- ttest_res$conf.int[2]\n  ```\n  :::\n\n\n  * Record whether the confidence interval contains the **true difference** between the two population means. Because we specified the means of our simulated populations ourselves, we know what this value is: 1.2619\n  \n  :::{.callout-note}\n  The function <code>between([value]{.red-text}, [lower]{.orange-text}, [upper]{.blue-text})</code> will tell you if <code>[value]{.red-text}</code> is between <code>[lower]{.orange-text}</code> and <code>[upper]{.blue-text}</code>.\n  :::\n  \n  * Store TRUE or FALSE in a vector depending on the result.\n* Calculate the percentage of the 1,000 confidence intervals that contain the true difference.\n\n:::{.callout-answer collapse=\"true\" #ex-cis_ans}\n\n[1,000 times:]{.blue-text}\n\n* [Simulate two samples drawn from a normal distribution:]{.blue-text}\n    * [one with the same mean, standard deviation and sample size as the sites with *H. tumulorum*]{.blue-text}\n    * [one with the same mean, standard deviation and sample size as the sites without *H. tumulorum*.]{.blue-text}\n* [Put the data for the two samples into a data frame in long format.]{.blue-text}\n* [For each pair of simulated samples, use a t-test to calculate the difference between the sample means and its 95% confidence interval.]{.blue-text}\n* [Extract the confidence interval.]{.blue-text}\n* [Determine whether the confidence interval contains the **true difference** between the two population means.]{.blue-text}\n* [Store TRUE or FALSE in a vector depending on the result.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find the real difference for comparison\ntrue_diff <- pull(present, mean) - pull(absent, mean)\n\n# Vector to store the results\nres_vec <- c()\n\nfor (i in seq_len(1000)) {\n  # Simulate the two samples\n  sample_present <- rnorm(pull(present, count), mean = pull(present, mean), sd = pull(present, sd))\n  sample_absent <- rnorm(pull(absent, count), mean = pull(absent, mean), sd = pull(absent, sd))\n\n  # Put the results into a data frame\n  df <- tibble(\n    sample = c(\n      rep(\"sample_1\", length(sample_present)),\n      rep(\"sample_2\", length(sample_absent))\n    ),\n    min_temp_coldest_month = c(sample_present, sample_absent)\n  )\n\n  # Run the t-test\n  ttest_res <- t.test(min_temp_coldest_month ~ sample,\n    data = df,\n    var.equal = TRUE\n  )\n\n  # Extract the confidence interval\n  ci_lower <- ttest_res$conf.int[1]\n  ci_upper <- ttest_res$conf.int[2]\n\n  # Check if the result is in the confidence interval or not\n  res_in_ci <- between(true_diff, ci_lower, ci_upper)\n\n  # Store the result\n  res_vec <- c(res_vec, res_in_ci)\n}\n```\n:::\n\n\n[Calculate the percentage of the 1,000 confidence intervals that contain the true difference.]{.blue-text}\n\n::: {.cell}\n\n```{.r .cell-code}\nperc <- (sum(res_vec) / length(res_vec)) * 100\nprint(perc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 95.6\n```\n\n\n:::\n:::\n\n\nIn this simulation, the confidence interval included the true difference 95.6% of the time - very similar to our expectation.\n\n:::\n:::\n\n## Linear models\n\nThe comparison we have just made can also be represented using a linear model.\n\nAs you know, a simple linear model can be written as:\n\n$$\ny = \\beta_0 + \\beta_1 x + \\epsilon\n$$\nwhere:\n\n- $y$ is the response variable - minimum temperature\n- $x$ is the explanatory variable - *H. tumulorum* present or absent.\n- $\\beta_0$ is the intercept\n- $\\beta_1$ is the coefficient (or slope)\n- $\\epsilon$ represents the variation not explained by the model\n\nIn our case, the value of $x$ (`detected`, the explanatory variable) - can only be TRUE or FALSE. It is usual in this case to assign FALSE a value of 0 and TRUE a value of 1.\n\n* If *H. tumulorum* is absent, $x$ equals 0.\n* When $x$ is zero, the line intercepts the y axis - so the intercept $\\beta_0$ is the minimum temperature when *H. tumulorum* is absent.\n* If *H. tumulorum* is present, $x$ equals 1.\n* The slope is the change in $y$ over one unit of $x$. So, the change in minimum temperature between $x$ = 0 and $x$ = 1, or the difference in mean temperature when *H. tumulorum* is present, compared to when it is absent.\n\nWe know these numbers already:\n\n::: {.cell}\n\n```{.r .cell-code}\ngt(spp_summary |> select(detected, mean))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"errmklciuo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#errmklciuo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#errmklciuo thead, #errmklciuo tbody, #errmklciuo tfoot, #errmklciuo tr, #errmklciuo td, #errmklciuo th {\n  border-style: none;\n}\n\n#errmklciuo p {\n  margin: 0;\n  padding: 0;\n}\n\n#errmklciuo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#errmklciuo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#errmklciuo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#errmklciuo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#errmklciuo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#errmklciuo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#errmklciuo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#errmklciuo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#errmklciuo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#errmklciuo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#errmklciuo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#errmklciuo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#errmklciuo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#errmklciuo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#errmklciuo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#errmklciuo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#errmklciuo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#errmklciuo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#errmklciuo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#errmklciuo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#errmklciuo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#errmklciuo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#errmklciuo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#errmklciuo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#errmklciuo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#errmklciuo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#errmklciuo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#errmklciuo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#errmklciuo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#errmklciuo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#errmklciuo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#errmklciuo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#errmklciuo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#errmklciuo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#errmklciuo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#errmklciuo .gt_left {\n  text-align: left;\n}\n\n#errmklciuo .gt_center {\n  text-align: center;\n}\n\n#errmklciuo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#errmklciuo .gt_font_normal {\n  font-weight: normal;\n}\n\n#errmklciuo .gt_font_bold {\n  font-weight: bold;\n}\n\n#errmklciuo .gt_font_italic {\n  font-style: italic;\n}\n\n#errmklciuo .gt_super {\n  font-size: 65%;\n}\n\n#errmklciuo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#errmklciuo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#errmklciuo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#errmklciuo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#errmklciuo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#errmklciuo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#errmklciuo .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#errmklciuo .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#errmklciuo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"detected\">detected</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean\">mean</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"detected\" class=\"gt_row gt_center\">FALSE</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">0.1128519</td></tr>\n    <tr><td headers=\"detected\" class=\"gt_row gt_center\">TRUE</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">1.3747955</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThe difference between the two means is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiff <- pull(present, mean) - pull(absent, mean)\nprint(diff)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.261944\n```\n\n\n:::\n:::\n\n\nWhen the bee is absent, $x = 0$:\n\n$$\ny = 0.11 + (1.26 \\times 0) + \\epsilon\n$$\n\nso:\n\n$$\ny = 0.11 + \\epsilon\n$$\n\nWhen the bee is present, $x = 1$:\n\n$$\ny = 0.11 + (1.26 \\times 1) + \\epsilon\n$$\n\nso:\n\n$$\ny = 1.37 + \\epsilon\n$$\nOur **t-test** tests whether there is evidence that the difference between the mean values of the two groups is different from zero.\n\nOur **linear model** tests whether there is evidence that the slope of the line is different from zero.\n\nThey are therefore testing exactly the same thing.\n\n### Fitting linear models in R\n\nLet's see if this is correct by fitting a linear model to our data in R. We do this with the function `lm()` and the same formula we used previously - `response ~ explanatory`.\n\nWe can summarise the linear model using the function `summary()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_model <- lm(min_temp_coldest_month ~ detected,\n  data = spp_presence\n)\nprint(summary(linear_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = min_temp_coldest_month ~ detected, data = spp_presence)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.40085 -0.61417  0.02203  0.60461  2.55090 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    0.1129     0.1579   0.715    0.477    \ndetectedTRUE   1.2619     0.2204   5.726 2.07e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9603 on 74 degrees of freedom\nMultiple R-squared:  0.307,\tAdjusted R-squared:  0.2977 \nF-statistic: 32.79 on 1 and 74 DF,  p-value: 2.073e-07\n```\n\n\n:::\n:::\n\n\nThis function gives us a lot of information, including the numbers we calculated above.\n\n* The estimated intercept is our mean minimum temperature without *H. tumulorum*\n* The estimated slope (listed as `detectedTRUE`) is the difference in minimum temperature with and without *H. tumulorum*. \n* The p-value for the slope is identical to the p-value we calculated earlier with our t-test.\n\nWe can extract the 95% confidence intervals from our linear model with the function `confint()` with one argument - the fitted model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nci <- confint(linear_model)\nprint(ci)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  2.5 %    97.5 %\n(Intercept)  -0.2017249 0.4274287\ndetectedTRUE  0.8228055 1.7010818\n```\n\n\n:::\n:::\n\nThe second confidence interval here is the confidence interval of the slope of the line - and again it's identical to our t-test values above.\n\n### Visualising linear models in R\n\nWe can easily visualise our linear model in ggplot.\n\nFirst, we plot a scatter plot with our `detected` variable on the x-axis and minimum temperature on the y-axis.\n\nWe need to convert our `detected` column to show 0 for FALSE and 1 for TRUE. To convert a column to numeric, we use the function `as.numeric()`. For a boolean column, it will automatically do what we want - convert FALSE to 0 and TRUE to 1.\n\nWe can then use the function `geom_smooth()` to apply and plot a linear model to the data. This corresponds to plotting a line between 0.11 when x is 0 and 1.37 when x is 1.\n\nLet's also add a horizontal line using `geom_hline()` showing a slope of 0 and the same mean for both groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspp_presence <- spp_presence |>\n  mutate(detected_num = as.numeric(detected))\n\noverall_mean <- spp_presence |>\n  pull(min_temp_coldest_month) |>\n  mean()\n\nggplot(spp_presence, aes(\n  x = detected_num,\n  y = min_temp_coldest_month\n)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  theme_bw() +\n  geom_hline(aes(yintercept = overall_mean), color = \"red\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](04-02_hypothesis_testing_files/figure-html/lm_lowest_temp-1.png){width=672}\n:::\n:::\n\n\n\n## ANOVA\n\nWith exactly two groups, a classical one-way ANOVA is also mathematically equivalent to either of these tests. \n\nA one-way ANOVA with two groups is testing:\n\n*Does allowing the two groups to have different means explain significantly more variation than assuming they have the same mean*\n\nThis can be simplified to - is there evidence that these two means are not equal?\n\nThis is asking the same question we've already asked twice, in a different way.\n\nLet's try an ANOVA. We run ANOVA in R on an existing linear model - which we already created above, using the function `anova()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_lm <- anova(linear_model)\nanova_lm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: min_temp_coldest_month\n          Df Sum Sq Mean Sq F value    Pr(>F)    \ndetected   1 30.237 30.2366  32.786 2.073e-07 ***\nResiduals 74 68.245  0.9222                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nAs you can see, we've again found an identical p-value. As it's the same linear model, our confidence intervals are, by definition, also the same.\n\nThe advantage of ANOVA is that, unlike a t-test, we can use it when our categorical explanatory variable has more than two groups - we'll come to this in the next section.\n",
    "supporting": [
      "04-02_hypothesis_testing_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}