{
  "hash": "9597620dcf7ccd39f66058e2f94729f4",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: html\npractical: Practical_4_Statistics\ndoc-id: \"0401\"\nauthor: \"Katy Brown\"\n---\n\n\n\n# Part 1: Estimators\n\n## The dataset\n\nThe dataset we will use in this practical is [pan-trap survey data](https://catalogue.ceh.ac.uk/documents/9df83130-e98f-48b0-bbfc-32f5920eedb0) from the UK Pollinator Monitoring Scheme. In this scheme, multiple [pan-traps](https://en.wikipedia.org/wiki/Pan_trap) are set in each of a set of specific 1km squares across the UK. On four days each summer, volunteers will set out traps for six hours, then send the insects to be counted. Flowering plants within a 2m radius of the trap are also recorded.\n\n[comment]: todo_katy link to the preprocessing.\n\nThe data from the scheme is provided as data per trap, for this practical we have amalgamated the data across all dates and across each 1km square. The preprocessing of the data is described in XXXX. \n\nYou have been provided with four data files:\n\n* In the **insect counts** CSV file - `data/insect_counts.csv` each row represents a combination of an insect species and a sampling site, and the total number of times that insect was observed at that site. Many of the counts will be zero.\n\n* In the **flower counts** CSV file - `data/flower_counts.csv` each row reprsents a combination of a flower species and a sampling site, plus TRUE or FALSE depending if that flower was ever observed within 2m of the site.\n\n* In the **site metadata** CSV file - `data/site_metadata.csv`, each row represents a single 1km square sampling site. The data frame contains information about the geographical location, plus land use and climate at the sample site. Additional climate data has been added based  [WorldClim](https://nordata.physics.utoronto.ca/en/annexes-datasets-descriptions/72-precipitation/worldclim-version-2/) data, which has detailed climate data by square averaged from 1970-2000. Various additional statistics have been calculated based on the information in the original data frame.\n\n* In the **insect metadata** CSV file - `data/insect_metadata.csv`, each row represents a single species of bee or hoverfly and its common name (where available), order and family. Additional data about the mass and length of the insects has been added from the [pollimetry](https://www.rdocumentation.org/packages/pollimetry/versions/1.0.1) R package.\n\n* In the **flower metadata** CSV file - `data/flower_metadata.csv`, each row represents a single species of plant and its common name (where available), order and family.\n\n::: {.callout-exercise #ex_summarise_bees}\nIn your `insects.qmd` Quarto file:\n\n* Read the five CSV files:\n\n  * `data/insect_counts.csv`\n  * `data/flower_counts.csv`\n  * `data/site_metadata.csv`\n  * `data/insect_metadata.csv`\n  * `data/flower_metadata.csv`\n\n* Count how many unique sites there are. Site ID is in the `x1km_square` column of the insect counts data frame and site metadata data frame. \n* Count how many unique observations of insects there are - including multiple observations of the same insect at the same site, on the same day. Number of observations is in the `n_observed` column os the insect counts data frame.\n* Find the insect species which was observed most frequently and how many times it was observed. Insect species is in the column `species` of the insect counts data frame and the insect metadata data frame.\n\n::: {.callout-answer #ex_summarise_bees_ans}\n\n[Read the five CSV files]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsect_counts <- read_csv(\"data/insect_counts.csv\")\nflower_counts <- read_csv(\"data/flower_counts.csv\")\nsite_metadata <- read_csv(\"data/site_metadata.csv\")\ninsect_metadata <- read_csv(\"data/insect_metadata.csv\")\nflower_metadata <- read_csv(\"data/flower_metadata.csv\")\n```\n:::\n\n\n[Count how many unique sites there are. Site ID is in the `x1km_square` column of the insect counts data frame and site metadata data frame. ]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsite_count <- nrow(site_metadata)\nprint(site_count)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 76\n```\n\n\n:::\n:::\n\nThere are 76 sites.\n\n[Count how many unique observations of insects there are - including multiple observations of the same insect at the same site. Number of observations is in the `n_observed` column os the insect counts data frame]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntotal_insect_obs <- insect_counts |>\n  pull(n_observed) |>\n  sum()\nprint(total_insect_obs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15126\n```\n\n\n:::\n:::\n\nThere are 15126 unique insect observations.\n\n[Find the insect species which was observed most frequently and how many times it was observed. Insect species is in the column `species` of the insect counts data frame and the insect metadata data frame.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsect_totals <- insect_counts |>\n  group_by(species) |>\n  summarise(n_obs = sum(n_observed))\n\ninsect_totals <- insect_totals |>\n  arrange(desc(n_obs))\n\ngt(head(insect_totals))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vfonqzbrga\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vfonqzbrga table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vfonqzbrga thead, #vfonqzbrga tbody, #vfonqzbrga tfoot, #vfonqzbrga tr, #vfonqzbrga td, #vfonqzbrga th {\n  border-style: none;\n}\n\n#vfonqzbrga p {\n  margin: 0;\n  padding: 0;\n}\n\n#vfonqzbrga .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vfonqzbrga .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vfonqzbrga .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vfonqzbrga .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vfonqzbrga .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vfonqzbrga .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vfonqzbrga .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vfonqzbrga .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vfonqzbrga .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vfonqzbrga .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vfonqzbrga .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vfonqzbrga .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vfonqzbrga .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vfonqzbrga .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vfonqzbrga .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vfonqzbrga .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vfonqzbrga .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vfonqzbrga .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vfonqzbrga .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vfonqzbrga .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vfonqzbrga .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vfonqzbrga .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vfonqzbrga .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vfonqzbrga .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vfonqzbrga .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vfonqzbrga .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vfonqzbrga .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vfonqzbrga .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vfonqzbrga .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vfonqzbrga .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vfonqzbrga .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vfonqzbrga .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vfonqzbrga .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vfonqzbrga .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vfonqzbrga .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vfonqzbrga .gt_left {\n  text-align: left;\n}\n\n#vfonqzbrga .gt_center {\n  text-align: center;\n}\n\n#vfonqzbrga .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vfonqzbrga .gt_font_normal {\n  font-weight: normal;\n}\n\n#vfonqzbrga .gt_font_bold {\n  font-weight: bold;\n}\n\n#vfonqzbrga .gt_font_italic {\n  font-style: italic;\n}\n\n#vfonqzbrga .gt_super {\n  font-size: 65%;\n}\n\n#vfonqzbrga .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vfonqzbrga .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vfonqzbrga .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vfonqzbrga .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vfonqzbrga .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vfonqzbrga .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vfonqzbrga .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vfonqzbrga .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vfonqzbrga div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"species\">species</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_obs\">n_obs</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"species\" class=\"gt_row gt_left\">Episyrphus balteatus</td>\n<td headers=\"n_obs\" class=\"gt_row gt_right\">1034</td></tr>\n    <tr><td headers=\"species\" class=\"gt_row gt_left\">Apis mellifera</td>\n<td headers=\"n_obs\" class=\"gt_row gt_right\">744</td></tr>\n    <tr><td headers=\"species\" class=\"gt_row gt_left\">Bombus lucorum</td>\n<td headers=\"n_obs\" class=\"gt_row gt_right\">705</td></tr>\n    <tr><td headers=\"species\" class=\"gt_row gt_left\">Syrphus ribesii</td>\n<td headers=\"n_obs\" class=\"gt_row gt_right\">625</td></tr>\n    <tr><td headers=\"species\" class=\"gt_row gt_left\">Helophilus pendulus</td>\n<td headers=\"n_obs\" class=\"gt_row gt_right\">538</td></tr>\n    <tr><td headers=\"species\" class=\"gt_row gt_left\">Lasioglossum calceatum</td>\n<td headers=\"n_obs\" class=\"gt_row gt_right\">490</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThe most commonly observed species was Episyrphus balteatus, which was observed 1034 times.\n\n:::\n:::\n\n## Estimators\n\nLet's concentrate on a single aspect of the data for now - the species richness, measured as the number of unique species.\n\nAcross the whole dataset, we know the total number of unique species - we have one species for each row in our insect metadata data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_unique_species <- nrow(insect_metadata)\nprint(n_unique_species)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 255\n```\n\n\n:::\n:::\n\nThere are 255 unique species.\n\nThe data we have here is only a sample of the whole population, but for this exercise, we will treat the complete dataset as a pseudo-population and explore what happens when we take samples from this population.\n\nLet's say we wanted to estimate the total species richness across the full data set based on 20 sites and we have three possible estimators:\n\n* Observed richness - total number of unique species across 20 sites\n* Scaled observed richness - total number of unique species across 20 sites * (total number of sites / 20)\n* The Chao1 richness estimator, which uses the number of rare species in the sample to estimate how many species may have gone undetected.\n\nFirst let's take a sample of 20 random sites.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrandom_sites <- site_metadata |>\n  distinct(x1km_square) |>\n  slice_sample(n = 20) |>\n  pull(x1km_square)\n```\n:::\n\n\nNow we can extract these rows from our insect counts data frame. For this part of the practical, we're not interested in insects with a count of 0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsect_sample <- insect_counts |>\n  filter(\n    x1km_square %in% random_sites,\n    n_observed != 0\n  )\n\ngt(head(insect_sample))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"fjuqtcskow\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fjuqtcskow table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fjuqtcskow thead, #fjuqtcskow tbody, #fjuqtcskow tfoot, #fjuqtcskow tr, #fjuqtcskow td, #fjuqtcskow th {\n  border-style: none;\n}\n\n#fjuqtcskow p {\n  margin: 0;\n  padding: 0;\n}\n\n#fjuqtcskow .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fjuqtcskow .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fjuqtcskow .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fjuqtcskow .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fjuqtcskow .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fjuqtcskow .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fjuqtcskow .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fjuqtcskow .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fjuqtcskow .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fjuqtcskow .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fjuqtcskow .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fjuqtcskow .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fjuqtcskow .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fjuqtcskow .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fjuqtcskow .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fjuqtcskow .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fjuqtcskow .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fjuqtcskow .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fjuqtcskow .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fjuqtcskow .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fjuqtcskow .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fjuqtcskow .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fjuqtcskow .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fjuqtcskow .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fjuqtcskow .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fjuqtcskow .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fjuqtcskow .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fjuqtcskow .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fjuqtcskow .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fjuqtcskow .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fjuqtcskow .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fjuqtcskow .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fjuqtcskow .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fjuqtcskow .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fjuqtcskow .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fjuqtcskow .gt_left {\n  text-align: left;\n}\n\n#fjuqtcskow .gt_center {\n  text-align: center;\n}\n\n#fjuqtcskow .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fjuqtcskow .gt_font_normal {\n  font-weight: normal;\n}\n\n#fjuqtcskow .gt_font_bold {\n  font-weight: bold;\n}\n\n#fjuqtcskow .gt_font_italic {\n  font-style: italic;\n}\n\n#fjuqtcskow .gt_super {\n  font-size: 65%;\n}\n\n#fjuqtcskow .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fjuqtcskow .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fjuqtcskow .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fjuqtcskow .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fjuqtcskow .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fjuqtcskow .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fjuqtcskow .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#fjuqtcskow .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#fjuqtcskow div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"x1km_square\">x1km_square</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"species\">species</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_observed\">n_observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"genus\">genus</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC0429</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Episyrphus balteatus</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">1</td>\n<td headers=\"genus\" class=\"gt_row gt_left\">Episyrphus</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC0429</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Melanogaster hirtella</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">2</td>\n<td headers=\"genus\" class=\"gt_row gt_left\">Melanogaster</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC0429</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Syrphus ribesii</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">1</td>\n<td headers=\"genus\" class=\"gt_row gt_left\">Syrphus</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC0429</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Syrphus torvus</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">1</td>\n<td headers=\"genus\" class=\"gt_row gt_left\">Syrphus</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC0429</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Syrphus vitripennis</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">1</td>\n<td headers=\"genus\" class=\"gt_row gt_left\">Syrphus</td></tr>\n    <tr><td headers=\"x1km_square\" class=\"gt_row gt_left\">NC0429</td>\n<td headers=\"species\" class=\"gt_row gt_left\">Xylota segnis</td>\n<td headers=\"n_observed\" class=\"gt_row gt_right\">1</td>\n<td headers=\"genus\" class=\"gt_row gt_left\">Xylota</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n#### Observed richness\n\nThe observed richness is just the total number of unique species observed across all sites.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_rich <- insect_sample |>\n  distinct(species) |>\n  pull(species)\nn_obs_rich <- length(obs_rich)\nprint(n_obs_rich)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 177\n```\n\n\n:::\n:::\n\nThe  observed richness estimator for this sample is 177.\n\n#### Scaled observed richness\n\nThe scaled observed richness is the total number of unique species observed across all sites, multiplied by \n(total number of sites / number of sites in sample).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_sites_sample <- 20\nscaled_obs_rich <- n_obs_rich * (site_count / n_sites_sample)\nprint(scaled_obs_rich)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 672.6\n```\n\n\n:::\n:::\n\nThe scaled observed richness estimator for this sample is 673.\n\n#### Chao1 estimator\n\nThe Chao1 estimator estimates unseen species based on the number of species represented only once or twice in your sample.\n\n$$\n\\hat{S}_{Chao1} = S_{obs} + \\frac{f_1^2}{2f_2}\n$$\n\nwhere:\n\n- $S_{obs}$ is the number of species observed in the sample.\n- $f_1$ is the number of species observed exactly once (singletons).\n- $f_2$ is the number of species observed exactly twice (doubletons).\n\n::: {.callout-note #note-chao}\nYou do not need to remember this - it is just an example of an estimator. \n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_per_insect <- insect_sample |>\n  group_by(species) |>\n  summarise(n_total = sum(n_observed))\n\nonce <- obs_per_insect |> filter(n_total == 1)\ntwice <- obs_per_insect |> filter(n_total == 2)\n\nn_once <- nrow(once)\nn_twice <- nrow(twice)\n\nchao <- n_obs_rich + ((n_once^2) / (2 * n_twice))\nprint(chao)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 241\n```\n\n\n:::\n:::\n\nThe chao1 estimator for this sample is 241.\n\nNone of these did a particularly good job of finding our real value of 255.\n\nHowever, you can't measure how good an estimator is based on a single sample. Let's try simulation and generate multiple samples.\n\nRemember (from the lectures): An unbiased estimator gives the correct value on average across repeated samples. The efficiency of an estimator is determined by its variance: estimators with lower variance give more consistent estimates. Mean square error (MSE) combines bias and variance and measures how far, overall, estimates tend to be from the true value.\n\n::: {.callout-exercise #ex-simulate_estimators}\n\nUsing a for loop, with 10,000 iterations (this might take a minute or two to run).\n\n* Take a sample of 20 sites, then extract the insect counts for these sites from the data frame.\n* Calculate observed richness, scaled observed richness and chao1 for each sample.\n* Store the results for each estimator in a separate vector.\n* Combine these into a data frame.\n* For each estimator:\n  * Calculate the bias, as the difference between the mean value across samples and the real value from our pseudo population.\n  * Calculate the variance.\n  * Calculate the mean square error.\n* Which estimator would you use, if any?\n\n::: {.callout-answer collapse=\"true\" #ex-simulate_estimators_ans}\n\n[Take a sample of 20 sites, then extract the insect counts for these sites from the data frame.]{.blue-text}\n\n[Calculate observed richness, scaled observed richness and chao1 for each sample.]{.blue-text}\n\n[Store the results for each estimator in a separate vector.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_rich_vec <- c()\nscaled_obs_rich_vec <- c()\nchao_vec <- c()\n\n# Loop for 10,000 iterations\nfor (i in seq_len(10000)) {\n  # Sample 20 sites\n  random_sites <- site_metadata |>\n    distinct(x1km_square) |>\n    slice_sample(n = 20) |>\n    pull(x1km_square)\n\n  # Extract the insect counts for these sites\n  insect_sample <- insect_counts |>\n    filter(\n      x1km_square %in% random_sites,\n      n_observed != 0\n    )\n\n  # Calculate observed richness\n  obs_rich <- insect_sample |>\n    distinct(species) |>\n    pull(species)\n  n_obs_rich <- length(obs_rich)\n  # Store\n  obs_rich_vec <- c(obs_rich_vec, n_obs_rich)\n\n  # Calculate the scaled observed richness\n  scaled_obs_rich <- n_obs_rich * (site_count / 20)\n  # Store\n  scaled_obs_rich_vec <- c(scaled_obs_rich_vec, scaled_obs_rich)\n\n  # Calculate Chao1\n  obs_per_insect <- insect_sample |>\n    group_by(species) |>\n    summarise(n_total = sum(n_observed))\n\n  once <- obs_per_insect |> filter(n_total == 1)\n  twice <- obs_per_insect |> filter(n_total == 2)\n\n  n_once <- nrow(once)\n  n_twice <- nrow(twice)\n\n  chao <- n_obs_rich + ((n_once^2) / (2 * n_twice))\n  # Store\n  chao_vec <- c(chao_vec, chao)\n}\n```\n:::\n\n\n[Combine these into a data frame.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimator_df <- tibble(\n  Observed = obs_rich_vec,\n  Scaled_Observed = scaled_obs_rich_vec,\n  Chao1 = chao_vec)\n```\n:::\n\n\n\n\n[For each estimator:]{.blue-text}\n\n[Calculate the bias]{.blue-text}\n\n[Calculate the efficiency]{.blue-text}\n\n[Calculate the mean square error.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimator_summary <- estimator_df |>\n  summarise(\n    Bias_Observed = mean(Observed) - n_unique_species,\n    Bias_Scaled_Observed = mean(Scaled_Observed) - n_unique_species,\n    Bias_Chao1 = mean(Chao1) - n_unique_species,\n    Eff_Observed = var(Observed),\n    Eff_Scaled_Observed = var(Scaled_Observed),\n    Eff_Chao1 = var(Chao1),\n    MSE_Observed = mean((Observed - n_unique_species)^2),\n    MSE_Scaled_Observed =mean((Scaled_Observed - n_unique_species)^2),\n    MSE_Chao1 = mean((Chao1 - n_unique_species)^2)\n  )\ngt(estimator_summary)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"umoypqcoti\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#umoypqcoti table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#umoypqcoti thead, #umoypqcoti tbody, #umoypqcoti tfoot, #umoypqcoti tr, #umoypqcoti td, #umoypqcoti th {\n  border-style: none;\n}\n\n#umoypqcoti p {\n  margin: 0;\n  padding: 0;\n}\n\n#umoypqcoti .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#umoypqcoti .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#umoypqcoti .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#umoypqcoti .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#umoypqcoti .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#umoypqcoti .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#umoypqcoti .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#umoypqcoti .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#umoypqcoti .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#umoypqcoti .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#umoypqcoti .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#umoypqcoti .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#umoypqcoti .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#umoypqcoti .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#umoypqcoti .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#umoypqcoti .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#umoypqcoti .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#umoypqcoti .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#umoypqcoti .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#umoypqcoti .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#umoypqcoti .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#umoypqcoti .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#umoypqcoti .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#umoypqcoti .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#umoypqcoti .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#umoypqcoti .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#umoypqcoti .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#umoypqcoti .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#umoypqcoti .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#umoypqcoti .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#umoypqcoti .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#umoypqcoti .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#umoypqcoti .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#umoypqcoti .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#umoypqcoti .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#umoypqcoti .gt_left {\n  text-align: left;\n}\n\n#umoypqcoti .gt_center {\n  text-align: center;\n}\n\n#umoypqcoti .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#umoypqcoti .gt_font_normal {\n  font-weight: normal;\n}\n\n#umoypqcoti .gt_font_bold {\n  font-weight: bold;\n}\n\n#umoypqcoti .gt_font_italic {\n  font-style: italic;\n}\n\n#umoypqcoti .gt_super {\n  font-size: 65%;\n}\n\n#umoypqcoti .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#umoypqcoti .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#umoypqcoti .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#umoypqcoti .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#umoypqcoti .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#umoypqcoti .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#umoypqcoti .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#umoypqcoti .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#umoypqcoti div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Bias_Observed\">Bias_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Bias_Scaled_Observed\">Bias_Scaled_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Bias_Chao1\">Bias_Chao1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Eff_Observed\">Eff_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Eff_Scaled_Observed\">Eff_Scaled_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Eff_Chao1\">Eff_Chao1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MSE_Observed\">MSE_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MSE_Scaled_Observed\">MSE_Scaled_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MSE_Chao1\">MSE_Chao1</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Bias_Observed\" class=\"gt_row gt_right\">-86.7319</td>\n<td headers=\"Bias_Scaled_Observed\" class=\"gt_row gt_right\">384.4188</td>\n<td headers=\"Bias_Chao1\" class=\"gt_row gt_right\">-49.38669</td>\n<td headers=\"Eff_Observed\" class=\"gt_row gt_right\">57.8032</td>\n<td headers=\"Eff_Scaled_Observed\" class=\"gt_row gt_right\">834.6782</td>\n<td headers=\"Eff_Chao1\" class=\"gt_row gt_right\">278.429</td>\n<td headers=\"MSE_Observed\" class=\"gt_row gt_right\">7580.22</td>\n<td headers=\"MSE_Scaled_Observed\" class=\"gt_row gt_right\">148612.4</td>\n<td headers=\"MSE_Chao1\" class=\"gt_row gt_right\">2717.446</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n[Which estimator would you use, if any?]{.blue-text}\n\nOf the three, the Chao1 estimator has the lowest mean square error, however it is still has a negative bias and a low efficiency.\n\n:::\n:::\n\nPlotting our simulated estimators also provides a lot of information.\n\nWe can combine all three estimators into a single plot, first we need to convert the data from wide to long format (see @sec-long_wide).\n\nThe function `everything()` tells R to pivot all of the columns in the table. A new column, `estimator` will be created to specify if each row is an observed, scaled observed or chao1 estimator.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimator_long <- estimator_df |>\n  pivot_longer(\n    everything(),\n    names_to = \"estimator\",\n    values_to = \"estimate\"\n  )\n\ngt(head(estimator_long))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"osgtskxxwd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#osgtskxxwd table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#osgtskxxwd thead, #osgtskxxwd tbody, #osgtskxxwd tfoot, #osgtskxxwd tr, #osgtskxxwd td, #osgtskxxwd th {\n  border-style: none;\n}\n\n#osgtskxxwd p {\n  margin: 0;\n  padding: 0;\n}\n\n#osgtskxxwd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#osgtskxxwd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#osgtskxxwd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#osgtskxxwd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#osgtskxxwd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#osgtskxxwd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#osgtskxxwd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#osgtskxxwd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#osgtskxxwd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#osgtskxxwd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#osgtskxxwd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#osgtskxxwd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#osgtskxxwd .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#osgtskxxwd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#osgtskxxwd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#osgtskxxwd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#osgtskxxwd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#osgtskxxwd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#osgtskxxwd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#osgtskxxwd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#osgtskxxwd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#osgtskxxwd .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#osgtskxxwd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#osgtskxxwd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#osgtskxxwd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#osgtskxxwd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#osgtskxxwd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#osgtskxxwd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#osgtskxxwd .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#osgtskxxwd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#osgtskxxwd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#osgtskxxwd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#osgtskxxwd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#osgtskxxwd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#osgtskxxwd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#osgtskxxwd .gt_left {\n  text-align: left;\n}\n\n#osgtskxxwd .gt_center {\n  text-align: center;\n}\n\n#osgtskxxwd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#osgtskxxwd .gt_font_normal {\n  font-weight: normal;\n}\n\n#osgtskxxwd .gt_font_bold {\n  font-weight: bold;\n}\n\n#osgtskxxwd .gt_font_italic {\n  font-style: italic;\n}\n\n#osgtskxxwd .gt_super {\n  font-size: 65%;\n}\n\n#osgtskxxwd .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#osgtskxxwd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#osgtskxxwd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#osgtskxxwd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#osgtskxxwd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#osgtskxxwd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#osgtskxxwd .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#osgtskxxwd .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#osgtskxxwd div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimator\">estimator</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimator\" class=\"gt_row gt_left\">Observed</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">163.0000</td></tr>\n    <tr><td headers=\"estimator\" class=\"gt_row gt_left\">Scaled_Observed</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">619.4000</td></tr>\n    <tr><td headers=\"estimator\" class=\"gt_row gt_left\">Chao1</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">195.4000</td></tr>\n    <tr><td headers=\"estimator\" class=\"gt_row gt_left\">Observed</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">173.0000</td></tr>\n    <tr><td headers=\"estimator\" class=\"gt_row gt_left\">Scaled_Observed</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">657.4000</td></tr>\n    <tr><td headers=\"estimator\" class=\"gt_row gt_left\">Chao1</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">199.3269</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nNow, let's plot the values of each estimator as histograms. \n\nThe function `facet_wrap()` splits the data from a single data frame into multiple plots, based on the values in a categorical column. The first argument should be the variable you would like to facet by, preceded by a `~` symbol. The argument `scales = \"free\"` means that each plot can have a different scale bar - by default they are all the same.\n\nThe function `geom_vline()` adds a vertical line at a specific point, specified by the argument `xintercept`. In this case, the line is at our pseudo-population total species richness.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(estimator_long, aes(x = estimate)) +\n  geom_histogram(bins=50) +\n  facet_wrap(~ estimator, scales = \"free\") +\n  geom_vline(xintercept = n_unique_species, color='red')\n```\n\n::: {.cell-output-display}\n![](04-01_estimators_files/figure-html/plot_simulated_estimators-1.png){width=672}\n:::\n:::\n\nHere it is clear again that none of these are great estimators, but that Chao1 is probably the best. \n\nSometimes an estimator is bad because the sample size is too small, sometimes it's just bad. Let's try taking 50 sites per sample, instead of 20.\n\nThe code below is identical to the above except for samples of 50 sites.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_rich_vec_50 <- c()\nscaled_obs_rich_vec_50 <- c()\nchao_vec_50 <- c()\n\n# Loop for 10,000 iterations\nfor (i in seq_len(10000)) {\n  # Sample 50 sites\n  random_sites <- site_metadata |>\n    distinct(x1km_square) |>\n    slice_sample(n = 50) |>\n    pull(x1km_square)\n\n  # Extract the insect counts for these sites\n  insect_sample <- insect_counts |>\n    filter(\n      x1km_square %in% random_sites,\n      n_observed != 0\n    )\n\n  # Calculate observed richness\n  obs_rich <- insect_sample |>\n    distinct(species) |>\n    pull(species)\n  n_obs_rich <- length(obs_rich)\n  # Store\n  obs_rich_vec_50 <- c(obs_rich_vec_50, n_obs_rich)\n\n  # Calculate the scaled observed richness\n  scaled_obs_rich <- n_obs_rich * (site_count / 50)\n  # Store\n  scaled_obs_rich_vec_50 <- c(scaled_obs_rich_vec_50, scaled_obs_rich)\n\n  # Calculate Chao1\n  obs_per_insect <- insect_sample |>\n    group_by(species) |>\n    summarise(n_total = sum(n_observed))\n\n  once <- obs_per_insect |> filter(n_total == 1)\n  twice <- obs_per_insect |> filter(n_total == 2)\n\n  n_once <- nrow(once)\n  n_twice <- nrow(twice)\n\n  chao <- n_obs_rich + ((n_once^2) / (2 * n_twice))\n  # Store\n  chao_vec_50 <- c(chao_vec_50, chao)\n}\n\nestimator_df_50 <- tibble(\n  Observed = obs_rich_vec_50,\n  Scaled_Observed = scaled_obs_rich_vec_50,\n  Chao1 = chao_vec_50)\n```\n:::\n\n\n\n\nNow we can look at the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimator_summary_50 <- estimator_df_50 |>\n  summarise(\n    Bias_Observed = mean(Observed) - n_unique_species,\n    Bias_Scaled_Observed = mean(Scaled_Observed) - n_unique_species,\n    Bias_Chao1 = mean(Chao1) - n_unique_species,\n    Eff_Observed = var(Observed),\n    Eff_Scaled_Observed = var(Scaled_Observed),\n    Eff_Chao1 = var(Chao1),\n    MSE_Observed = mean((Observed - n_unique_species)^2),\n    MSE_Scaled_Observed =mean((Scaled_Observed - n_unique_species)^2),\n    MSE_Chao1 = mean((Chao1 - n_unique_species)^2)\n  )\ngt(estimator_summary_50)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ssvojzozex\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ssvojzozex table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ssvojzozex thead, #ssvojzozex tbody, #ssvojzozex tfoot, #ssvojzozex tr, #ssvojzozex td, #ssvojzozex th {\n  border-style: none;\n}\n\n#ssvojzozex p {\n  margin: 0;\n  padding: 0;\n}\n\n#ssvojzozex .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ssvojzozex .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ssvojzozex .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ssvojzozex .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ssvojzozex .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ssvojzozex .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ssvojzozex .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ssvojzozex .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ssvojzozex .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ssvojzozex .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ssvojzozex .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ssvojzozex .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ssvojzozex .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ssvojzozex .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ssvojzozex .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ssvojzozex .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ssvojzozex .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ssvojzozex .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ssvojzozex .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ssvojzozex .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ssvojzozex .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ssvojzozex .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ssvojzozex .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ssvojzozex .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ssvojzozex .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ssvojzozex .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ssvojzozex .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ssvojzozex .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ssvojzozex .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ssvojzozex .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ssvojzozex .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ssvojzozex .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ssvojzozex .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ssvojzozex .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ssvojzozex .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ssvojzozex .gt_left {\n  text-align: left;\n}\n\n#ssvojzozex .gt_center {\n  text-align: center;\n}\n\n#ssvojzozex .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ssvojzozex .gt_font_normal {\n  font-weight: normal;\n}\n\n#ssvojzozex .gt_font_bold {\n  font-weight: bold;\n}\n\n#ssvojzozex .gt_font_italic {\n  font-style: italic;\n}\n\n#ssvojzozex .gt_super {\n  font-size: 65%;\n}\n\n#ssvojzozex .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ssvojzozex .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ssvojzozex .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ssvojzozex .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ssvojzozex .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ssvojzozex .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ssvojzozex .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ssvojzozex .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ssvojzozex div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Bias_Observed\">Bias_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Bias_Scaled_Observed\">Bias_Scaled_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Bias_Chao1\">Bias_Chao1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Eff_Observed\">Eff_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Eff_Scaled_Observed\">Eff_Scaled_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Eff_Chao1\">Eff_Chao1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MSE_Observed\">MSE_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MSE_Scaled_Observed\">MSE_Scaled_Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MSE_Chao1\">MSE_Chao1</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Bias_Observed\" class=\"gt_row gt_right\">-38.6048</td>\n<td headers=\"Bias_Scaled_Observed\" class=\"gt_row gt_right\">73.9207</td>\n<td headers=\"Bias_Chao1\" class=\"gt_row gt_right\">-4.336045</td>\n<td headers=\"Eff_Observed\" class=\"gt_row gt_right\">21.62138</td>\n<td headers=\"Eff_Scaled_Observed\" class=\"gt_row gt_right\">49.95403</td>\n<td headers=\"Eff_Chao1\" class=\"gt_row gt_right\">149.1186</td>\n<td headers=\"MSE_Observed\" class=\"gt_row gt_right\">1511.95</td>\n<td headers=\"MSE_Scaled_Observed\" class=\"gt_row gt_right\">5514.22</td>\n<td headers=\"MSE_Chao1\" class=\"gt_row gt_right\">167.905</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThese are still not great, but they have improved quite a lot. Chao1 still looks best.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimator_long_50 <- estimator_df_50 |>\n  pivot_longer(\n    everything(),\n    names_to = \"estimator\",\n    values_to = \"estimate\"\n  )\n\nggplot(estimator_long_50, aes(x = estimate)) +\n  geom_histogram(bins=50) +\n  geom_vline(xintercept = n_unique_species, color='red') +\n  facet_wrap(~ estimator, scales = \"free\")\n```\n\n::: {.cell-output-display}\n![](04-01_estimators_files/figure-html/simulate_estimators_sample_50_ggplot-1.png){width=672}\n:::\n:::\n\nChao1 actually looks pretty good here - it is generating an approximately unbiased estimate of the pseudo-population, although it has a higher variance, and therefore lower efficiency, than either other estimator. \n\n::: {.callout-note #uk_poms_citation}\n**Data citation**\n\nUK Pollinator Monitoring Scheme (2024). 1km square pan trap data from the UK Pollinator Monitoring Scheme, 2017-2021. NERC EDS Environmental Information Data Centre. (Dataset).\n\nThe UK Pollinator Monitoring Scheme (PoMS) is a partnership funded jointly by UKCEH and JNCC (through funding from Defra, Scottish Government, Welsh Government, and DAERA). UKCEH’s contribution is funded by the Natural Environment Research Council award number NE/R016429/1 as part of the UK-SCAPE programme delivering National Capability. Between 2017 and 2021, PoMS was funded by UKCEH and Defra (England), Welsh Government, Scottish Government, DAERA (Northern Ireland), and JNCC.\nPoMS is indebted to the many volunteers who carry out surveys and contribute data to the scheme.\n\n:::\n\n\n",
    "supporting": [
      "04-01_estimators_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}