{
  "hash": "ecef592a1133bbd11f730ad293c23d24",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: html\npractical: Practical_6_Further_Statistics\ndoc-id: \"0604\"\nauthor: \"Katy Brown\"\n---\n\n\n\n# Part 4: Generalised Linear Models - Binomial {#sec-p4_glms_binomial}\n\n::: {.callout-note .partmenu #parts-0604}\n## Sections\n- @sec-binary_response\n- @sec-not_linear [(Extension)]{.extension-text}\n- @sec-fitting_binomial_glms\n- @sec-link_functions\n- @sec-predictions_binom_glms\n- @sec-multiple_predictors [(Recommended)]{.rec-text}\n- @sec-parameter_estimation [(Extension)]{.extension-text}\n- @sec-parameter_space [(Extension)]{.extension-text}\n- @sec-assumptions_binom\n- @sec-summary_0604\n:::\n\n:::{.callout-tip .objectives}\n#### Learning objectives\nBy the end of this part of the practical you will be able to:\n\n* Fit and interpret a binomial generalised linear model (GLM) in R.\n* Explain the role of the logit link function in a binomial GLM.\n* Use a fitted binomial GLM to predict probabilities.\n* Fit binomial GLMs containing multiple explanatory variables and interactions.\n* Describe the main assumptions of a binomial GLM.\n\n:::\n\nIn this part of the practical, you will need two Quarto documents:\n\n* `prac6_exercises.qmd` for short programming exercises.\n* `glms.qmd` for applying GLMs to pollinator data.\n\nAs you may have noticed, all of the statistical tests introduced in Practical 4 (except for chi-squared) expect a **continuous response variable**.\n\nA standard linear model assumes that the response variable is continuous, with observations normally distributed around an expected value. A linear combination of the explanatory variables determines this expected value.\n\nHowever, not all response variables are continuous or normally distributed. As you learned in the lectures, a **generalised linear model** (GLM) extends the idea of a linear model to response variables with other distributions.\n\n## Binomial response variables {#sec-binary_response .core}\n\n[**Core**]{.core-text}\n\n[↑ top](#)\n\nIn @sec-p2_hypothesis_testing_1, we treated the presence or absence of a species as our explanatory variable when asking whether mean temperature differed between sites where a species was present and absent. We then used our model to predict mean temperature in the presence of this species in @sec-p6_predictions.\n\nHowever, we may instead want to ask: **does the probability of species presence change with temperature?**\n\nIn the case of *H. tumulorum* we would therefore have the following hypotheses:\n\n* **Null hypothesis**: There is no relationship between minimum temperature in the coldest month and the probability of detecting *H. tumulorum*.\n* **Alternative hypothesis**: There is a relationship between minimum temperature in the coldest month and the probability of detecting *H. tumulorum*.\n\nIn this case, detection of *H. tumulorum* becomes our response variable and minimum temperature becomes our explanatory variable.\n\nOur response variable is **binary**: at each site H. tumulorum was either detected (1) or not detected (0). We can model this using a binomial distribution, where $p$ represents the **probability** of detection. We therefore need our predicted values of $p$ to lie between 0 and 1.\n\n## Why not use a linear model? {#sec-not_linear .fold .extension}\n\n[**Extension**]{.extension-text}\n\n[↑ top](#)\n\nLet's try just using a linear model. First, we need to load our *H. tumulorum* dataset. We should also use the `as.integer()` function to convert our logical (TRUE / FALSE) `detected` column into a numerical column with `1` for detected and `0` for not detected.\n\nThen we can apply our linear model, with minimum temperature as the explanatory variable and detection of *H. tumulorum* as the response.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data, convert detected to integers\nht_df <- read_csv(\"data/ht_df.csv\") |>\n  mutate(detected_01 = as.integer(detected))\n\n# Apply linear model\nlm_binary <- lm(detected_01 ~ min_temp_coldest_month, data = ht_df)\n\n# Display linear model\nsummary(lm_binary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = detected_01 ~ min_temp_coldest_month, data = ht_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.97623 -0.39746  0.08645  0.35050  0.71455 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             0.32815    0.05817   5.641 2.92e-07 ***\nmin_temp_coldest_month  0.24330    0.04249   5.726 2.07e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4217 on 74 degrees of freedom\nMultiple R-squared:  0.307,\tAdjusted R-squared:  0.2977 \nF-statistic: 32.79 on 1 and 74 DF,  p-value: 2.073e-07\n```\n\n\n:::\n:::\n\nNow let's try to use this model to predict the presence or absence of *H. tumulorum* at 0°C.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_unknown <- tibble(min_temp_coldest_month = 0)\n\npred <- predict(lm_binary, newdata = df_unknown)\nprint(pred)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1 \n0.3281477 \n```\n\n\n:::\n:::\n\n\nOur model predicts a 32.81% probability of detecting *H. tumulorum* at this temperature. This seems feasible.\n\nLet's try some more extreme temperatures.\n\n::: {.callout-exercise #ex-binary_lm .extension}\n\n### Predictions using a linear model\n\n[**Extension**]{.extension-text}\n\nIn your `glms.qmd` Quarto file, use `predict()` with this model to predict the probability of detecting *H. tumulorum* when the minimum temperature in the coldest month is:\n\n* -10°C\n* 20°C\n\n:::{.callout-answer collapse=\"true\" #ex-binary_lm_ans}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_unknown <- tibble(min_temp_coldest_month = c(-10, 20))\npred <- predict(lm_binary, newdata = df_unknown)\nprint(pred)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1         2 \n-2.104826  5.194096 \n```\n\n\n:::\n:::\n\n:::\n:::\n\nOK, so *H. tumulorum* will be present at -21% of sites at -10°C and 519% of sites at 20°C - this is not working.\n\nLet's plot our real data against our model nevertheless:.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  ht_df,\n  aes(x = min_temp_coldest_month, y = detected_01)\n) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](06-04_glms_binom_files/figure-html/plot_binary_response-1.png){width=672}\n:::\n:::\n\n\nA linear model can predict any numerical value, whereas a probability must always lie between 0 and 1 (0–100%). We therefore need a model that retains the useful linear relationship with our explanatory variable, but converts its predictions onto a scale appropriate for a probability.\n\n## Link functions in binomial GLMs {#sec-link_functions .core}\n\n[**Core**]{.core-text}\n\n[↑ top](#)\n\nA link function transforms the expected value of the response so that it can be modelled as a linear combination of the explanatory variables.\n\nIn a binomial GLM, the **logit** link function transforms probabilities into log-odds. \n\n$$\n\\operatorname{logit}(p) = \\ln\\left(\\frac{p}{1-p}\\right)\n$$\n\n::: {.callout-exercise #ex-odds .core}\n\n### Write a log-odds function\n\n[**Core**]{.core-text}\n\nIn your `prac6_exercises.qmd` Quarto file, write a function to calculate the log-odds from a probability. In R `log()` is the natural logarithm.\n\nUse your function to calculate the log-odds for a sequence of probabilities from 0 to 1, with increment 0.1 (you can generate this with `seq(0, 1, 0.1)`).  Observe what happens to the log-odds as the probability increases.\n\n::: {.callout-answer collapse=\"true\" #ex-odds_ans .core}\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write the function\ncalc_log_odds <- function(prob) {\n  odds <- prob / (1 - prob)\n  log_odds <- log(odds)\n  return(log_odds)\n}\n\n# Apply the function to the sequence\nlo_vec <- c()\nfor (val in seq(0, 1, 0.1)) {\n  lo <- calc_log_odds(val)\n  lo_vec <- c(lo_vec, lo)\n}\nprint(lo_vec)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]       -Inf -2.1972246 -1.3862944 -0.8472979 -0.4054651  0.0000000\n [7]  0.4054651  0.8472979  1.3862944  2.1972246        Inf\n```\n\n\n:::\n:::\n\nThere is an increase in log-odds as probability increases.\n:::\n:::\n\nThe natural logarithm of the odds (log-odds) can take any value from $-\\infty$ to $\\infty$. We can therefore model the log-odds as a linear combination of our explanatory variables. \n\n## Fitting binomial GLMs in R {#sec-fitting_binomial_glms .core}\n\nIf we use a GLM instead of a linear model, it estimates the linear relationship between minimum temperature and presence / absence on the log-odds scale.\n\nWe can apply a GLM in R using the `glm()` function. We use the argument `family = binomial` to specify that we want to predict a binomial response. Otherwise, the function is applied in the same way as a linear model, but with `glm()` instead of `lm()`.\n\n::: {.callout-exercise #ex-fit_binomial_glm_ht .core}\n\n### Fit a GLM\n\n[**Core**]{.core-text}\n\nIn your `glms.qmd` Quarto file, use `glm()` to test whether the probability of detecting *H. tumulorum* is associated with minimum temperature in the coldest month.\n\nUse:\n\n- `detected_01` as the response variable\n- `min_temp_coldest_month` as the explanatory variable\n- `family = binomial` to fit a binomial GLM\n\nSave your model as `glm_ht` and examine it using `summary()`.\n\n::: {.callout-answer collapse=\"true\" #ex-fit_binomial_glm_ht_ans}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm_ht <- glm(detected_01 ~ min_temp_coldest_month,\n  data = ht_df,\n  family = binomial\n)\nsummary(glm_ht)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = detected_01 ~ min_temp_coldest_month, family = binomial, \n    data = ht_df)\n\nCoefficients:\n                       Estimate Std. Error z value Pr(>|z|)    \n(Intercept)             -1.2589     0.4516  -2.787 0.005314 ** \nmin_temp_coldest_month   1.6535     0.4268   3.874 0.000107 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 105.31  on 75  degrees of freedom\nResidual deviance:  75.69  on 74  degrees of freedom\nAIC: 79.69\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n:::\n:::\n\nWe would report these findings as follows:\n\n::: {.highlight-box}\nThere was strong evidence that minimum temperature in the coldest month was associated with the probability of detecting *H. tumulorum* (binomial GLM, $\\beta$ = 1.65, $z$ = 3.87), $p$ = 0.0001. The positive coefficient estimate for `min_temp_coldest_month` indicates that *H. tumulorum* is more likely to be detected at sites with higher minimum temperatures.\n:::\n\n$\\beta$ = 1.65 tells us that for every 1°C increase in minimum temperature, the log-odds of detecting *H. tumulorum* increase by 1.65.\n\nWe can exponentiate this to get the odds ratio:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeta <- glm_ht$coefficients[2]\nexpo <- exp(beta)\nprint(expo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmin_temp_coldest_month \n              5.225079 \n```\n\n\n:::\n:::\n\n\nSo, for every 1°C increase in minimum temperature, the odds of detecting *H. tumulorum* are multiplied by approximately 5.2.\n\nLet's plot our data and our GLM prediction.\n\nTo plot the predicted values we use `geom_smooth()`, as we did for linear models, but with the arguments `method = \"glm\"` and `method.args = list(family = binomial)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  ht_df,\n  aes(\n    x = min_temp_coldest_month,\n    y = detected_01\n  )\n) +\n  geom_point() +\n  geom_smooth(\n    method = \"glm\",\n    method.args = list(family = binomial)\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](06-04_glms_binom_files/figure-html/visualise_glm-1.png){width=672}\n:::\n:::\n\n\nAs you can see, the prediction is limited to probabilities between 0 and 1.\n\n## Making predictions {#sec-predictions_binom_glms .core}\n\n::: {.callout-exercise #ex-predict_with_glm .core}\n\n### Make predictions using a GLM\n\n[**Core**]{.core-text}\n\nIn your `glms.qmd` Quarto file, use your GLM to predict the probability of detecting *H. tumulorum* at the following temperatures:\n\n* 0°C\n* 1°C\n* 2°C\n\nBy default, `predict()` returns predictions from this model on the log-odds scale. The argument `type = \"response\"` applies the inverse link function and returns predictions on the original response scale — in this case, probabilities.\n\n::: {.callout-answer collapse=\"true\" #ex_predict_with_glm_ans}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make a data frame of the temperatures for which\n# we want to predict probabilities\ndf_unknown <- tibble(\n  min_temp_coldest_month = c(0, 1, 2)\n)\n\n# Predict the probability of presence or absence at these\n# temperatures\npred <- predict(\n  glm_ht,\n  newdata = df_unknown,\n  type = \"response\"\n)\n\n# Put the results in a data frame\npred_df <- tibble(\n  min_temp = c(0, 1, 2),\n  predicted_prob = pred\n)\ngt(pred_df)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"wneqjzxdhe\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wneqjzxdhe table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wneqjzxdhe thead, #wneqjzxdhe tbody, #wneqjzxdhe tfoot, #wneqjzxdhe tr, #wneqjzxdhe td, #wneqjzxdhe th {\n  border-style: none;\n}\n\n#wneqjzxdhe p {\n  margin: 0;\n  padding: 0;\n}\n\n#wneqjzxdhe .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wneqjzxdhe .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wneqjzxdhe .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wneqjzxdhe .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wneqjzxdhe .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wneqjzxdhe .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wneqjzxdhe .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wneqjzxdhe .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wneqjzxdhe .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wneqjzxdhe .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wneqjzxdhe .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wneqjzxdhe .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wneqjzxdhe .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wneqjzxdhe .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wneqjzxdhe .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wneqjzxdhe .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wneqjzxdhe .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wneqjzxdhe .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wneqjzxdhe .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wneqjzxdhe .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wneqjzxdhe .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wneqjzxdhe .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wneqjzxdhe .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wneqjzxdhe .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wneqjzxdhe .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wneqjzxdhe .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wneqjzxdhe .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wneqjzxdhe .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wneqjzxdhe .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wneqjzxdhe .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wneqjzxdhe .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wneqjzxdhe .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wneqjzxdhe .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wneqjzxdhe .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wneqjzxdhe .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wneqjzxdhe .gt_left {\n  text-align: left;\n}\n\n#wneqjzxdhe .gt_center {\n  text-align: center;\n}\n\n#wneqjzxdhe .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wneqjzxdhe .gt_font_normal {\n  font-weight: normal;\n}\n\n#wneqjzxdhe .gt_font_bold {\n  font-weight: bold;\n}\n\n#wneqjzxdhe .gt_font_italic {\n  font-style: italic;\n}\n\n#wneqjzxdhe .gt_super {\n  font-size: 65%;\n}\n\n#wneqjzxdhe .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wneqjzxdhe .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wneqjzxdhe .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wneqjzxdhe .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wneqjzxdhe .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wneqjzxdhe .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wneqjzxdhe .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wneqjzxdhe .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#wneqjzxdhe div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"min_temp\">min_temp</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"predicted_prob\">predicted_prob</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"min_temp\" class=\"gt_row gt_right\">0</td>\n<td headers=\"predicted_prob\" class=\"gt_row gt_right\">0.2211643</td></tr>\n    <tr><td headers=\"min_temp\" class=\"gt_row gt_right\">1</td>\n<td headers=\"predicted_prob\" class=\"gt_row gt_right\">0.5973837</td></tr>\n    <tr><td headers=\"min_temp\" class=\"gt_row gt_right\">2</td>\n<td headers=\"predicted_prob\" class=\"gt_row gt_right\">0.8857500</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n:::\n:::\n\nSo, there is a 22.12% probability of seeing *H. tumulorum* with a minimum temperature of 0°C, a 59.74% probability at 1°C and an 88.57% probability at 2°C.\n\nLet's go back to our extreme temperatures, -10°C and 20°C, and do the same thing again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_extreme <- tibble(\n  min_temp_coldest_month = c(-10, 20)\n)\n\npred <- predict(\n  glm_ht,\n  newdata = df_extreme,\n  type = \"response\"\n)\n\npred_df <- tibble(\n  min_temp = c(-10, 20),\n  predicted_prob = pred\n)\ngt(pred_df)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"tshagcftnm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tshagcftnm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tshagcftnm thead, #tshagcftnm tbody, #tshagcftnm tfoot, #tshagcftnm tr, #tshagcftnm td, #tshagcftnm th {\n  border-style: none;\n}\n\n#tshagcftnm p {\n  margin: 0;\n  padding: 0;\n}\n\n#tshagcftnm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tshagcftnm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tshagcftnm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tshagcftnm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tshagcftnm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tshagcftnm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tshagcftnm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tshagcftnm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tshagcftnm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tshagcftnm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tshagcftnm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tshagcftnm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tshagcftnm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tshagcftnm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tshagcftnm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tshagcftnm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tshagcftnm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tshagcftnm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tshagcftnm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tshagcftnm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tshagcftnm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tshagcftnm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tshagcftnm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tshagcftnm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tshagcftnm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tshagcftnm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tshagcftnm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tshagcftnm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tshagcftnm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tshagcftnm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tshagcftnm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tshagcftnm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tshagcftnm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tshagcftnm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tshagcftnm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tshagcftnm .gt_left {\n  text-align: left;\n}\n\n#tshagcftnm .gt_center {\n  text-align: center;\n}\n\n#tshagcftnm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tshagcftnm .gt_font_normal {\n  font-weight: normal;\n}\n\n#tshagcftnm .gt_font_bold {\n  font-weight: bold;\n}\n\n#tshagcftnm .gt_font_italic {\n  font-style: italic;\n}\n\n#tshagcftnm .gt_super {\n  font-size: 65%;\n}\n\n#tshagcftnm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tshagcftnm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tshagcftnm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tshagcftnm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tshagcftnm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tshagcftnm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tshagcftnm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#tshagcftnm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#tshagcftnm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"min_temp\">min_temp</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"predicted_prob\">predicted_prob</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"min_temp\" class=\"gt_row gt_right\">-10</td>\n<td headers=\"predicted_prob\" class=\"gt_row gt_right\">1.872149e-08</td></tr>\n    <tr><td headers=\"min_temp\" class=\"gt_row gt_right\">20</td>\n<td headers=\"predicted_prob\" class=\"gt_row gt_right\">1.000000e+00</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThese values, essentially 0 at -10°C and 1 at 20°C may still be incorrect, but they are at least valid probabilites. Our model describes the relationship supported by the observed data, which has a minimum temperature of -2.29°C and a maximum temperature of 3.49°C. There is no guarantee that the same relationship continues beyond this range. Making predictions outside the observed range is called **extrapolation**, and these predictions can be highly unreliable.\n\nFor example, let's predict the probability of finding *H. tumulorum* at 1000°C.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_extremer <- tibble(\n  min_temp_coldest_month = 1000\n)\n\npred <- predict(\n  glm_ht,\n  newdata = df_extremer,\n  type = \"response\"\n)\n\npred_df <- tibble(\n  min_temp = 1000,\n  predicted_prob = pred\n)\ngt(pred_df)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gvizduezns\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gvizduezns table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gvizduezns thead, #gvizduezns tbody, #gvizduezns tfoot, #gvizduezns tr, #gvizduezns td, #gvizduezns th {\n  border-style: none;\n}\n\n#gvizduezns p {\n  margin: 0;\n  padding: 0;\n}\n\n#gvizduezns .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gvizduezns .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gvizduezns .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gvizduezns .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gvizduezns .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gvizduezns .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gvizduezns .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gvizduezns .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gvizduezns .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gvizduezns .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gvizduezns .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gvizduezns .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gvizduezns .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gvizduezns .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gvizduezns .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gvizduezns .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gvizduezns .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gvizduezns .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gvizduezns .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gvizduezns .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gvizduezns .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gvizduezns .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gvizduezns .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gvizduezns .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gvizduezns .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gvizduezns .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gvizduezns .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gvizduezns .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gvizduezns .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gvizduezns .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gvizduezns .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gvizduezns .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gvizduezns .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gvizduezns .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gvizduezns .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gvizduezns .gt_left {\n  text-align: left;\n}\n\n#gvizduezns .gt_center {\n  text-align: center;\n}\n\n#gvizduezns .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gvizduezns .gt_font_normal {\n  font-weight: normal;\n}\n\n#gvizduezns .gt_font_bold {\n  font-weight: bold;\n}\n\n#gvizduezns .gt_font_italic {\n  font-style: italic;\n}\n\n#gvizduezns .gt_super {\n  font-size: 65%;\n}\n\n#gvizduezns .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gvizduezns .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gvizduezns .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gvizduezns .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gvizduezns .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gvizduezns .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gvizduezns .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gvizduezns .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gvizduezns div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"min_temp\">min_temp</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"predicted_prob\">predicted_prob</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"min_temp\" class=\"gt_row gt_right\">1000</td>\n<td headers=\"predicted_prob\" class=\"gt_row gt_right\">1</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nAccording to our model, we are guaranteed to find *H. tumulorum* at this temperature.\n\n![A fire bee](images/fire_bee.png){#fig-bee width=\"50%\"}\n\nUsing the logit function forces the predicted probability to be between 0 and 1, however it doesn't guarantee it is correct.\n\n## Multiple predictors {#sec-multiple_predictors .rec}\n\n[**Recommended**]{.rec-text}\n\n[↑ top](#)\n\nAdditional predictors and interactions can be added to GLMs exactly as we added them to linear models in  @sec-multiple_linear_regression.\n\n::: {.callout-exercise #ex-two_predictors .rec}\n\n### Fitting a GLM with multiple predictors\n\n[**Recommended**]{.rec-text}\n\nIn your `glms.qmd` Quarto file, apply a single binomial GLM to assess the following hypotheses, based on the data in `data/site_metadata.csv`.\n\n#### Annual mean temperature\n\n* **Null hypothesis**: At the average latitude, the probability of Halictidae being the dominant insect family is not associated with annual mean temperature.\n* **Alternative hypothesis**: At the average latitude, the probability of Halictidae being the dominant insect family is associated with annual mean temperature.\n\n#### Latitude\n\n* **Null hypothesis**: At the average annual mean temperature, the probability of Halictidae being the dominant insect family is not associated with latitude.\n* **Alternative hypothesis**: At the average annual mean temperature, the probability of Halictidae being the dominant insect family is associated with latitude.\n\n#### Interaction\n\n* **Null hypothesis**: The relationship between annual mean temperature and the probability of Halictidae being the dominant insect family does not depend on latitude.\n* **Alternative hypothesis**: The relationship between annual mean temperature and the probability of Halictidae being the dominant insect family depends on latitude.\n\nYou will need to add a column to `site_metadata` with 1 if the value of the column `dominant_family` is Halictidae and 0 otherwise. You will also need to **centre** your `annual_mean_temp` and `latitude` columns around 0 by subtracting the column mean from each value.\n\nDraw a conclusion based on the summary of the fitted model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsite_metadata <- read_csv(\"data/site_metadata.csv\")\nsite_metadata <- site_metadata |>\n  mutate(\n    dom_hali = as.integer(dominant_family == \"Halictidae\"),\n    cent_temp = annual_mean_temp - mean(annual_mean_temp),\n    cent_lat = latitude - mean(latitude)\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm_hali <- glm(dom_hali ~ cent_lat * cent_temp,\n  data = site_metadata,\n  family = binomial\n)\nprint(summary(glm_hali))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = dom_hali ~ cent_lat * cent_temp, family = binomial, \n    data = site_metadata)\n\nCoefficients:\n                   Estimate Std. Error z value Pr(>|z|)    \n(Intercept)         -4.2633     1.0514  -4.055 5.01e-05 ***\ncent_lat             0.3635     0.4379   0.830   0.4065    \ncent_temp            1.9129     1.0226   1.871   0.0614 .  \ncent_lat:cent_temp  -0.5155     0.2233  -2.309   0.0210 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 51.147  on 75  degrees of freedom\nResidual deviance: 37.022  on 72  degrees of freedom\nAIC: 45.022\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n::: {.highlight-box}\n\nFor **latitude**, the estimated coefficient is 0.363 with a p-value of 0.406. We therefore fail to reject the null hypothesis: there is no evidence that latitude is associated with the probability of Halictidae being the dominant insect family **at the average annual mean temperature**.\n\nFor **annual mean temperature**, the estimated coefficient is 1.913 with a p-value of 0.0614. We therefore fail to reject the null hypothesis: there is no evidence that annual mean temperature is associated with the probability of Halictidae being the dominant insect family **at the average latitude**.\n\nFor the **interaction between latitude and annual mean temperature**, the estimated coefficient is -0.516 with a p-value of 0.021. We therefore reject the null hypothesis and conclude that there is evidence that the relationship between annual mean temperature and the probability of Halictidae being the dominant insect family **depends on latitude**.\n:::\n:::\n\n## Estimating model parameters using maximum likelihood {#sec-parameter_estimation .fold .extension}\n\n[**Extension**]{.extension-text}\n\n[↑ top](#)\n\nR uses maximum likelihood to estimate the parameters for the model.\n\nLet's fit a two-parameter model to some simple data. Seagulls like to steal chips, and are more common near to the sea.  Let's see if there is an association between being nearer to the sea and having your chips stolen.\n\n![A seagull stealing a chip](images/seagull.jpg){#fig-gull width=\"50%\"}\n\nYou've been provided with a dataset in `data/seagulls.csv`.\n\n::: {.callout-exercise #ex-seagulls .extension}\n\n### Fit a binomial GLM\n\n[**Extension**]{.extension-text}\n\nIn your `prac6_exercises.qmd` Quarto file:\n\n* Read the data frame `data/seagulls.csv`.\n* Plot a box plot with `chips_stolen` on the x axis and `distance_from_sea` on the y axis.\n* Fit a binomial GLM with `chips_stolen` as the response variable.\n* View the GLM output with `summary()` and draw a brief conclusion.\n\n::: {.callout-answer collapse=\"true\" #ex-seagulls_ans}\n\n[Read the data frame `data/seagulls.csv`.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseagulls <- read_csv(\"data/seagulls.csv\")\n```\n:::\n\n\n[Plot a box plot with `chips_stolen` on the x axis and `distance_from_sea` on the y axis.]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(seagulls, aes(x = chips_stolen, y = distance_from_sea, fill = chips_stolen)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](06-04_glms_binom_files/figure-html/seagulls_ans2-1.png){width=672}\n:::\n:::\n\n\n[Fit a binomial GLM with `chips_stolen` as the response variable.]{.blue-text}\n\n[View the GLM output with `summary()`]{.blue-text}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseagull_glm <- glm(chips_stolen ~ distance_from_sea,\n                    data = seagulls,\n                    family = binomial)\nprint (summary(seagull_glm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = chips_stolen ~ distance_from_sea, family = binomial, \n    data = seagulls)\n\nCoefficients:\n                  Estimate Std. Error z value Pr(>|z|)   \n(Intercept)         1.3711     0.6889   1.990   0.0466 * \ndistance_from_sea  -0.5219     0.1612  -3.238   0.0012 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 61.086  on 49  degrees of freedom\nResidual deviance: 45.130  on 48  degrees of freedom\nAIC: 49.13\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n\n\n[Draw a brief conclusion]{.blue-text}\n\n::: {.highlight-box}\n\nThe estimated coefficient for distance from the sea is -0.522. As distance from the sea increases, the log-odds of having your chips stolen by a seagull therefore decreases ($p$ = 0.0012). We therefore reject the null hypothesis and conclude that there is evidence of an association between distance from the sea and the probability of having your chips stolen by a seagull.\n\n:::\n:::\n:::\n\nIn this case, R will have estimated both $\\beta_0$ (1.3711) and $\\beta_1$ (-0.5219) using **maximum likelihood estimation**. This process finds the values of the model parameters that make the observed data most likely.\n\nTo understand how this works, let's fix $\\beta_0$ at 1.3711 and calculate the likelihood of the observed data for a range of possible values of $\\beta_1$, from -1 to +1.\n\nThe model we are using is therefore:\n\n$$\n\\operatorname{logit}(p_{\\text{stolen}}) =\n1.3711 + \\beta_1 \\times \\text{distance from sea}\n$$\n\nWe can then try a range of values of $\\beta_1$ and see which value gives us a model with the highest likelihood of our observed data.\n\nFor each observation in the data frame, we calculate the probability of the outcome that was actually observed, given its distance from the sea and the value of $\\beta_1$ being tested. We then combine these probabilities to calculate the likelihood of the complete dataset.\n\nFor convenience, we use the logarithms of the probabilities. This allows us to add log-probabilities rather than multiplying together many very small probabilities. The value of $\\beta_1$ that gives the highest log-likelihood will also give the highest likelihood.\n\nFor each value of $\\beta_1$ we will:\n\n* Use the model equation and each observed `distance_from_sea` value to calculate the log-odds of chips being stolen.\n* Convert the log-odds to a probability using the inverse logit equation:\n\n$$\np = \\frac{e^{\\text{log-odds}}}{1 + e^{\\text{log-odds}}}\n$$\n\n* For rows where `chips_stolen` is `TRUE`, add the log of the probability of the chips being stolen, $\\log(p)$, to the total log-likelihood.\n* For rows where `chips_stolen` is `FALSE`, add the log of the probability of the chips not being stolen, $\\log(1-p)$, to the total log-likelihood.\n* Select the value of $\\beta_1$ that gives the highest log-likelihood.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npossible_beta1s <- seq(-1, 1, by = 0.01)\nlog_likelihoods <- c()\nb0 <- coef(seagull_glm)[\"(Intercept)\"]\n\nfor (beta in possible_beta1s) {\n  # Calculate log-odds using this possible coefficient\n  log_odds <- b0 + beta * pull(seagulls, distance_from_sea)\n  \n  # Convert log-odds to probability\n  probs <- exp(log_odds) / (1 + exp(log_odds))\n  \n  # Filter the data frame to only rows where chips\n  # were stolen and add a row with the probability\n  # of this happening under the model\n  chips_stolen <- seagulls |>\n    mutate(probs = probs,\n           log_probs = log(probs)) |>\n    filter(chips_stolen == TRUE)\n\n  # Filter the data frame to only rows where chips\n  # were not stolen and add a row with the probability\n  # of this happening under the model\n  chips_not_stolen <- seagulls |>\n    mutate(probs = (1 - probs),\n           log_probs = log(probs)) |>\n    filter(chips_stolen == FALSE)\n\n  # Calculate the log likelihood of the observed data\n  tot_stolen <- chips_stolen |> pull(log_probs) |> sum()\n  tot_not <- chips_not_stolen |> pull(log_probs) |> sum()\n  log_likelihood <- tot_stolen + tot_not\n  \n  # Add this to our vector of log likelihoods\n  log_likelihoods <- c(log_likelihoods, log_likelihood)\n}\n\n# Put the results into a data frame\ndf_likelihood <- tibble(beta = possible_beta1s,\n                        log_likelihood = log_likelihoods)\ngt(head(df_likelihood))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"aaknkbriwi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#aaknkbriwi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#aaknkbriwi thead, #aaknkbriwi tbody, #aaknkbriwi tfoot, #aaknkbriwi tr, #aaknkbriwi td, #aaknkbriwi th {\n  border-style: none;\n}\n\n#aaknkbriwi p {\n  margin: 0;\n  padding: 0;\n}\n\n#aaknkbriwi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#aaknkbriwi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#aaknkbriwi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#aaknkbriwi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#aaknkbriwi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#aaknkbriwi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aaknkbriwi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#aaknkbriwi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#aaknkbriwi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#aaknkbriwi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#aaknkbriwi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#aaknkbriwi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#aaknkbriwi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#aaknkbriwi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#aaknkbriwi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#aaknkbriwi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#aaknkbriwi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#aaknkbriwi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#aaknkbriwi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aaknkbriwi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#aaknkbriwi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#aaknkbriwi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#aaknkbriwi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aaknkbriwi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#aaknkbriwi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#aaknkbriwi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aaknkbriwi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aaknkbriwi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#aaknkbriwi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aaknkbriwi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#aaknkbriwi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aaknkbriwi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#aaknkbriwi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aaknkbriwi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#aaknkbriwi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aaknkbriwi .gt_left {\n  text-align: left;\n}\n\n#aaknkbriwi .gt_center {\n  text-align: center;\n}\n\n#aaknkbriwi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#aaknkbriwi .gt_font_normal {\n  font-weight: normal;\n}\n\n#aaknkbriwi .gt_font_bold {\n  font-weight: bold;\n}\n\n#aaknkbriwi .gt_font_italic {\n  font-style: italic;\n}\n\n#aaknkbriwi .gt_super {\n  font-size: 65%;\n}\n\n#aaknkbriwi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#aaknkbriwi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#aaknkbriwi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#aaknkbriwi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#aaknkbriwi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#aaknkbriwi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#aaknkbriwi .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#aaknkbriwi .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#aaknkbriwi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"beta\">beta</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"log_likelihood\">log_likelihood</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-1.00</td>\n<td headers=\"log_likelihood\" class=\"gt_row gt_right\">-31.34183</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.99</td>\n<td headers=\"log_likelihood\" class=\"gt_row gt_right\">-31.05762</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.98</td>\n<td headers=\"log_likelihood\" class=\"gt_row gt_right\">-30.77579</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.97</td>\n<td headers=\"log_likelihood\" class=\"gt_row gt_right\">-30.49641</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.96</td>\n<td headers=\"log_likelihood\" class=\"gt_row gt_right\">-30.21954</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.95</td>\n<td headers=\"log_likelihood\" class=\"gt_row gt_right\">-29.94527</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nNow we have our log-likelihood for each value of beta. Let's find the most likely value of $\\beta_1$ by sorting our data frame by descending likelihood.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmax_likelihood <- df_likelihood |>\n  arrange(desc(log_likelihood))\ngt(head(max_likelihood))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"fqixnkbezc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fqixnkbezc table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fqixnkbezc thead, #fqixnkbezc tbody, #fqixnkbezc tfoot, #fqixnkbezc tr, #fqixnkbezc td, #fqixnkbezc th {\n  border-style: none;\n}\n\n#fqixnkbezc p {\n  margin: 0;\n  padding: 0;\n}\n\n#fqixnkbezc .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fqixnkbezc .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fqixnkbezc .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fqixnkbezc .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fqixnkbezc .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fqixnkbezc .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fqixnkbezc .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fqixnkbezc .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fqixnkbezc .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fqixnkbezc .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fqixnkbezc .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fqixnkbezc .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fqixnkbezc .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fqixnkbezc .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fqixnkbezc .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fqixnkbezc .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fqixnkbezc .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fqixnkbezc .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fqixnkbezc .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fqixnkbezc .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fqixnkbezc .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fqixnkbezc .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fqixnkbezc .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fqixnkbezc .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fqixnkbezc .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fqixnkbezc .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fqixnkbezc .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fqixnkbezc .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fqixnkbezc .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fqixnkbezc .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fqixnkbezc .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fqixnkbezc .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fqixnkbezc .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fqixnkbezc .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fqixnkbezc .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fqixnkbezc .gt_left {\n  text-align: left;\n}\n\n#fqixnkbezc .gt_center {\n  text-align: center;\n}\n\n#fqixnkbezc .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fqixnkbezc .gt_font_normal {\n  font-weight: normal;\n}\n\n#fqixnkbezc .gt_font_bold {\n  font-weight: bold;\n}\n\n#fqixnkbezc .gt_font_italic {\n  font-style: italic;\n}\n\n#fqixnkbezc .gt_super {\n  font-size: 65%;\n}\n\n#fqixnkbezc .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fqixnkbezc .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fqixnkbezc .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fqixnkbezc .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fqixnkbezc .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fqixnkbezc .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fqixnkbezc .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#fqixnkbezc .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#fqixnkbezc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"beta\">beta</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"log_likelihood\">log_likelihood</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.52</td>\n<td headers=\"log_likelihood\" class=\"gt_row gt_right\">-22.56500</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.53</td>\n<td headers=\"log_likelihood\" class=\"gt_row gt_right\">-22.56913</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.51</td>\n<td headers=\"log_likelihood\" class=\"gt_row gt_right\">-22.57443</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.54</td>\n<td headers=\"log_likelihood\" class=\"gt_row gt_right\">-22.58626</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.50</td>\n<td headers=\"log_likelihood\" class=\"gt_row gt_right\">-22.59805</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.55</td>\n<td headers=\"log_likelihood\" class=\"gt_row gt_right\">-22.61582</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nWe can also plot our estimates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df_likelihood,\n       aes(x = beta, y = log_likelihood)) +\n  geom_point() +\n  geom_vline(xintercept = -0.52)\n```\n\n::: {.cell-output-display}\n![](06-04_glms_binom_files/figure-html/plot_ml_seagulls-1.png){width=672}\n:::\n:::\n\n\nOur maximum likelihood estimate of $\\beta_1$ is -0.52, very similar to the estimate in the model of -0.5219.\n\nNote that maximising the likelihood and maximising the log-likelihood will identify the same value of $\\beta_1$. Log-likelihood is generally more convenient to work with because it allows products of many small probabilities to be replaced by sums of their logarithms, avoiding extremely small numbers.\n\n::: {.callout-exercise #ex-not_log_likelihood .extension}\n\n### Non-log likelihood\n\n[**Extension**]{.extension-text}\n\nIn your `prac6_exercises.qmd` Quarto file, adapt the code above to use the product of the likelihood of the data under the model for each $\\beta_1$ value, rather than the log likelihood. The R function for product is `prod()`.\n\n::: {.callout-answer collapse=\"true\" #ex_not_log_likelihood_ans}\n\n\n::: {.cell}\n\n```{.r .cell-code}\npossible_beta1s <- seq(-1, 1, by = 0.01)\nlikelihoods <- c()\nb0 <- coef(seagull_glm)[\"(Intercept)\"]\n\nfor (beta in possible_beta1s) {\n  # Calculate log-odds using this possible coefficient\n  log_odds <- b0 + beta * pull(seagulls, distance_from_sea)\n  \n  # Convert log-odds to probability\n  probs <- exp(log_odds) / (1 + exp(log_odds))\n  \n  # Filter the data frame to only rows where chips\n  # were stolen and add a row with the probability\n  # of this happening under the model\n\n  chips_stolen <- seagulls |>\n    mutate(probs = probs) |>\n    filter(chips_stolen == TRUE)\n\n  # Filter the data frame to only rows where chips\n  # were not stolen and add a row with the probability\n  # of this happening under the model\n  chips_not_stolen <- seagulls |>\n    mutate(probs = (1 - probs)) |>\n    filter(chips_stolen == FALSE)\n\n  # Calculate the likelihood of the observed data\n  tot_stolen <- chips_stolen |> pull(probs) |> prod()\n  tot_not <- chips_not_stolen |> pull(probs) |> prod()\n  \n  likelihood <- tot_stolen * tot_not\n\n  likelihoods <- c(likelihoods, likelihood)\n}\n\ndf_likelihood_nolog <- tibble(beta = possible_beta1s,\n                              likelihood = likelihoods)\ngt(head(df_likelihood_nolog))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"bcpuuabzvj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#bcpuuabzvj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#bcpuuabzvj thead, #bcpuuabzvj tbody, #bcpuuabzvj tfoot, #bcpuuabzvj tr, #bcpuuabzvj td, #bcpuuabzvj th {\n  border-style: none;\n}\n\n#bcpuuabzvj p {\n  margin: 0;\n  padding: 0;\n}\n\n#bcpuuabzvj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#bcpuuabzvj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#bcpuuabzvj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#bcpuuabzvj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#bcpuuabzvj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bcpuuabzvj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bcpuuabzvj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bcpuuabzvj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#bcpuuabzvj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#bcpuuabzvj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#bcpuuabzvj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#bcpuuabzvj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#bcpuuabzvj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#bcpuuabzvj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#bcpuuabzvj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#bcpuuabzvj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#bcpuuabzvj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#bcpuuabzvj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#bcpuuabzvj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bcpuuabzvj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#bcpuuabzvj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#bcpuuabzvj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#bcpuuabzvj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bcpuuabzvj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#bcpuuabzvj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#bcpuuabzvj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bcpuuabzvj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bcpuuabzvj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#bcpuuabzvj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bcpuuabzvj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#bcpuuabzvj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bcpuuabzvj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bcpuuabzvj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bcpuuabzvj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bcpuuabzvj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bcpuuabzvj .gt_left {\n  text-align: left;\n}\n\n#bcpuuabzvj .gt_center {\n  text-align: center;\n}\n\n#bcpuuabzvj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#bcpuuabzvj .gt_font_normal {\n  font-weight: normal;\n}\n\n#bcpuuabzvj .gt_font_bold {\n  font-weight: bold;\n}\n\n#bcpuuabzvj .gt_font_italic {\n  font-style: italic;\n}\n\n#bcpuuabzvj .gt_super {\n  font-size: 65%;\n}\n\n#bcpuuabzvj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#bcpuuabzvj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#bcpuuabzvj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#bcpuuabzvj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#bcpuuabzvj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#bcpuuabzvj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#bcpuuabzvj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#bcpuuabzvj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#bcpuuabzvj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"beta\">beta</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"likelihood\">likelihood</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-1.00</td>\n<td headers=\"likelihood\" class=\"gt_row gt_right\">2.445775e-14</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.99</td>\n<td headers=\"likelihood\" class=\"gt_row gt_right\">3.249717e-14</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.98</td>\n<td headers=\"likelihood\" class=\"gt_row gt_right\">4.307681e-14</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.97</td>\n<td headers=\"likelihood\" class=\"gt_row gt_right\">5.696121e-14</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.96</td>\n<td headers=\"likelihood\" class=\"gt_row gt_right\">7.513117e-14</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.95</td>\n<td headers=\"likelihood\" class=\"gt_row gt_right\">9.883997e-14</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmax_likelihood <- df_likelihood_nolog |>\n  arrange(desc(likelihood))\ngt(head(max_likelihood))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jrbkyotbai\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jrbkyotbai table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jrbkyotbai thead, #jrbkyotbai tbody, #jrbkyotbai tfoot, #jrbkyotbai tr, #jrbkyotbai td, #jrbkyotbai th {\n  border-style: none;\n}\n\n#jrbkyotbai p {\n  margin: 0;\n  padding: 0;\n}\n\n#jrbkyotbai .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jrbkyotbai .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jrbkyotbai .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jrbkyotbai .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jrbkyotbai .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jrbkyotbai .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jrbkyotbai .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jrbkyotbai .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jrbkyotbai .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jrbkyotbai .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jrbkyotbai .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jrbkyotbai .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jrbkyotbai .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jrbkyotbai .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jrbkyotbai .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jrbkyotbai .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jrbkyotbai .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jrbkyotbai .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jrbkyotbai .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jrbkyotbai .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jrbkyotbai .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jrbkyotbai .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jrbkyotbai .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jrbkyotbai .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jrbkyotbai .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jrbkyotbai .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jrbkyotbai .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jrbkyotbai .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jrbkyotbai .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jrbkyotbai .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jrbkyotbai .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jrbkyotbai .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jrbkyotbai .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jrbkyotbai .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jrbkyotbai .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jrbkyotbai .gt_left {\n  text-align: left;\n}\n\n#jrbkyotbai .gt_center {\n  text-align: center;\n}\n\n#jrbkyotbai .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jrbkyotbai .gt_font_normal {\n  font-weight: normal;\n}\n\n#jrbkyotbai .gt_font_bold {\n  font-weight: bold;\n}\n\n#jrbkyotbai .gt_font_italic {\n  font-style: italic;\n}\n\n#jrbkyotbai .gt_super {\n  font-size: 65%;\n}\n\n#jrbkyotbai .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jrbkyotbai .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jrbkyotbai .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jrbkyotbai .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jrbkyotbai .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jrbkyotbai .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jrbkyotbai .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jrbkyotbai .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jrbkyotbai div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"beta\">beta</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"likelihood\">likelihood</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.52</td>\n<td headers=\"likelihood\" class=\"gt_row gt_right\">1.585428e-10</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.53</td>\n<td headers=\"likelihood\" class=\"gt_row gt_right\">1.578887e-10</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.51</td>\n<td headers=\"likelihood\" class=\"gt_row gt_right\">1.570535e-10</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.54</td>\n<td headers=\"likelihood\" class=\"gt_row gt_right\">1.552076e-10</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.50</td>\n<td headers=\"likelihood\" class=\"gt_row gt_right\">1.533878e-10</td></tr>\n    <tr><td headers=\"beta\" class=\"gt_row gt_right\">-0.55</td>\n<td headers=\"likelihood\" class=\"gt_row gt_right\">1.506860e-10</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df_likelihood_nolog,\n       aes(x = beta, y = likelihood)) +\n  geom_point() +\n  geom_vline(xintercept = -0.52)\n```\n\n::: {.cell-output-display}\n![](06-04_glms_binom_files/figure-html/plot_ml_seagulls_nolog-1.png){width=672}\n:::\n:::\n\n:::\n:::\n\nThis process gives the same answer, but the numbers are becoming impossibly small. With only 50 data points, R can cope with these values. Eventually, they may be too small for R to represent and be rounded to zero. Taking logarithms converts these products into sums and avoids this problem. \n\n## Parameter space {#sec-parameter_space .fold .extension}\n\n[**Extension**]{.extension-text}\n\nWe are looking for the most likely value of a single parameter, so we can test a suitable range of possible values. However, we have used R's estimate for $\\beta_0$. Without this, we would need to find the **combination** of $\\beta_0$ and $\\beta_1$ that gives the highest likelihood of observing our data, requiring us to search across a two-dimensional parameter space.\n\nWith additional parameters, the number of dimensions increases and the search becomes increasingly complex.\n\nIn practice, `glm()` uses an optimisation algorithm to find the combination of parameter values that maximises the likelihood, rather than testing every possible combination.\n\n## Assumptions {#sec-assumptions_binom .core}\n\n[**Core**]{.core-text}\n\n[↑ top](#)\n\nSome assumptions are common to all GLMs and some are specific depending on the type of response variable.\n\nFor all GLMs we assume:\n\n* Independence of observations - this is mostly a study-design/data-structure issue.\n\n* Linearity on the link scale - GLMs assume that the linear predictor is linear with respect to the explanatory variables\n\nFor binomial GLMs we additionally assume that the response is compatible with a binomial distribution (see @sec-binomial).\n\n## Review {#sec-summary_0604}\n\n[↑ top](#)\n\n::: {.callout-note #note-summary_0604}\n\n### Summary\n\n#### Statistics\n\n* **Generalised linear models (GLMs)** extend linear models to response variables that are not continuous and normally distributed.\n* A **binomial GLM** can be used when the response variable is binary, such as presence or absence.\n* A standard linear model is unsuitable for a binary response because it can predict values outside the possible range of probabilities from 0 to 1.\n* In a binomial GLM, the **logit link function** transforms probabilities into log-odds, which can take any value from $-\\infty$ to $\\infty$.\n* The coefficients of a binomial GLM describe changes in **log-odds**. Exponentiating a coefficient gives an **odds ratio**.\n* Predictions from a binomial GLM can be converted back to probabilities between 0 and 1.\n* Predictions made outside the range of the observed data are **extrapolations** and may be unreliable, even though the predicted probabilities remain between 0 and 1.\n* Binomial GLMs can contain multiple explanatory variables and interactions in the same way as standard linear models.\n* GLMs assume independence of observations and linearity on the link scale. A binomial GLM additionally requires a response compatible with a binomial distribution.\n\n#### Programming\n\n* We can fit a generalised linear model using `glm()`, specifying the response distribution using the `family` argument.\n* We can fit a binomial GLM using `family = binomial`.\n* We can examine a fitted GLM using `summary()` and access its estimated coefficients using `coef()`.\n* We can use `predict()` to make predictions from a fitted GLM, and `type = \"response\"` to return predictions on the response scale.\n* We can plot a fitted binomial GLM using `geom_smooth(method = \"glm\", method.args = list(family = binomial))`.\n\n:::\n\nFor this part of the practical, the main files you have created are:\n\n* `prac6_exercises.qmd`\n* `glms.qmd`\n\nThese are the files you should select when making your Git commit.\n\nRemember to save and commit your work before moving on to Part 5.\n\n::: {.callout-tip}\n## Commit your changes\nRemember to save your progress regularly by committing your changes with Git.\n\n1. Save your changes to the files above in RStudio with the `Save` button.\n2. Render any Quarto documents with the `Render` button.\n3. Open the `Git` tab in RStudio.\n4. Tick the files listed above, don't worry about any others.\n5. Click `Commit` and write a short message in the `Commit message` describing your changes, something like e.g. \"Practical 1 part 1\" is sufficient, then click `Commit`. Close the `Commit` popup.\n\n:::\n\t\n\n",
    "supporting": [
      "06-04_glms_binom_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}