{
  "hash": "0d5f43fd0cfeaa4356129d5aaca6a7cd",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: html\npractical: Practical_4_Statistics\ndoc-id: \"0405\"\nauthor: \"Katy Brown\"\n---\n\n\n# Part 5: Hypothesis Testing Exercises\n\nHere is a reminder of some statistical tests and the data types they are appropriate for.\n\n| Response variable | Explanatory variable(s) | Statistical test/model |\n|---|---|---|\n| Continuous | One categorical variable, 2 groups | Two-sample t-test or one-way ANOVA |\n| Continuous | One categorical variable, 3+ groups | One-way ANOVA |\n| Continuous | One continuous variable | Linear regression |\n| Continuous | Multiple categorical variables | Multi-way ANOVA |\n| Continuous | Multiple continuous variables | Multiple linear regression |\n| Continuous | Mixture of categorical and continuous variables | Multiple linear regression / linear model |\n| Categorical* | Categorical* | Chi-squared test |\n\n* For a chi-squared test, neither variable needs to be considered the explanatory or response variable.\n\nAs long as there are many possible values (e.g. the values aren't limited to 1, 2 or 3), count data (such as number of insects) can be treated as continuous when used as an **explanatory** variable. For the tests in this table, **response** variables described as continuous should usually be genuinely continuous rather than counts.\n\nNow we are ready to test some hypotheses based on the POMS data.\n\n::: {.callout-exercise #ex-pollinators_ht}\n\nIn your `pollinators.qmd` Quarto file, using the appropriate statistical tests, investigate at least three of the following questions. Try to choose questions requiring different tests.\n\nFor each hypothesis, choose an appropriate statistical test and visualisation (a box plot, bar chart or scatter plot). Interpret the result using the relevant test statistic, degrees of freedom and p-value. Where relevant to the test used, also consider the confidence interval, effect size and proportion of variation explained by the model.\n\nFor this exercise, assume that the underlying assumptions of the appropriate model have been met — you do not need to check or plot these. There is also no need to plot maps.\n\nThe data you need are in the `site_metadata` data frame unless otherwise specified.\n\n\n1. Different countries in the UK are quite diverse in terms of habitat and climate. Test the hypothesis that country (Scotland, England or Wales; column `country`) is associated with whether sites are dominated by bees (family Apidae) or hoverflies (family Syrphidae) (column `dominant_family`, you will need to filter to include only these families).\n\n::: {.callout-answer collapse=\"true\" #ex-pollinators_ht_ans1}\n\nCount the groups for the plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsites_apidae_syrphidae <- site_metadata |>\n  filter(dominant_family %in% c(\"Apidae\", \"Syrphidae\"))\ncountry_family_counts <- sites_apidae_syrphidae |>\n  count(country, dominant_family)\n```\n:::\n\n\nPlot a bar chart of the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(country_family_counts, aes(x = country, y = n, fill = dominant_family)) +\n  geom_col() +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](04-05_hypothesis_testing_exercises_files/figure-html/pollinators_ht_ans1.2-1.png){width=672}\n:::\n:::\n\nMake a contingency table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncont_table <- xtabs(\n  ~ country + dominant_family,\n  data = sites_apidae_syrphidae\n)\nprint(cont_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          dominant_family\ncountry    Apidae Syrphidae\n  England      20         8\n  Scotland      7        15\n  Wales         7        10\n```\n\n\n:::\n:::\n\n\nPerform a chi-squared test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncs <- chisq.test(cont_table)\nprint(cs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  cont_table\nX-squared = 8.5683, df = 2, p-value = 0.01379\n```\n\n\n:::\n:::\n\nThere is evidence of an association between dominant insect family (Apidae vs Syrphidae) and country ($\\chi^2$(2) = 8.57, $p$ = 0.0138). Sites in Scotland and Wales were observed to be more frequently dominated by Syrphidae, whereas sites in England were more frequently dominated by Apidae.\n\n:::\n\n2.  Very broadly, increased biomass is thought to be associated with higher temperatures and higher precipitation. Test the hypothesis that total insect biomass (column `total_insect_biomass`) is associated with annual mean temperature (`annual_mean_temp`) and annual total precipitation (`annual_total_prec`), with an additive effect, at these UK sites. Does the direction of each estimated relationship agree with the hypothesis?\n\n::: {.callout-answer collapse=\"true\" #ex-pollinators_ht_ans2}\n\nConvert the data to long format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiomass_tp <- site_metadata |>\n  select(total_insect_biomass, annual_mean_temp, annual_total_prec) |>\n  pivot_longer(\n    c(annual_mean_temp, annual_total_prec),\n    names_to = \"variable\",\n    values_to = \"measurement\"\n  )\n```\n:::\n\n\nPlot the relationship between insect biomass and each explanatory variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(biomass_tp, aes(\n  x = measurement,\n  y = total_insect_biomass\n)) +\n  geom_point() +\n  geom_smooth(method = \"lm\") +\n  facet_wrap(~variable, scales = \"free_y\") +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](04-05_hypothesis_testing_exercises_files/figure-html/pollinators_ht_ans2.2-1.png){width=672}\n:::\n:::\n\nPerform a multiple linear regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_biomass_tp <- lm(total_insect_biomass ~ annual_mean_temp + annual_total_prec, data = site_metadata)\nlm_biomass_tp_summary <- summary(lm_biomass_tp)\nprint(lm_biomass_tp_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = total_insect_biomass ~ annual_mean_temp + annual_total_prec, \n    data = site_metadata)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -7253  -2897  -1172   1599  20796 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)  \n(Intercept)       16153.044   7780.387   2.076   0.0414 *\nannual_mean_temp   -672.935    682.706  -0.986   0.3275  \nannual_total_prec    -3.508      2.252  -1.558   0.1237  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5444 on 73 degrees of freedom\nMultiple R-squared:  0.03221,\tAdjusted R-squared:  0.005692 \nF-statistic: 1.215 on 2 and 73 DF,  p-value: 0.3027\n```\n\n\n:::\n:::\n\n\n\nThere is no evidence that total insect biomass is associated with annual mean temperature and annual total precipitation in this model ($F$(2, 73) = 1.21, p=0.3027). The model explained only 3.2% of the variation in total insect biomass ($R^2$ = 0.0322). There was no evidence of an association with either annual mean temperature (coefficient = -672.94, p=0.3275) or annual total precipitation (coefficient = -3.51, p=0.1237), after accounting for the other variable. Both estimated relationships were negative, which is opposite to the direction predicted by our hypothesis.\n\n:::\n\n3. Sites at higher elevation may be subject to greater temperature variation than sites at lower elevation. Test the hypothesis that elevation (`elevation`) is associated with annual temperature range (`temp_annual_range`). Does the direction of the estimated relationship agree with the hypothesis?\n\n::: {.callout-answer collapse=\"true\" #ex-pollinators_ht_ans3}\n\nPlot a scatter plot of the two variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  site_metadata,\n  aes(x = elevation, y = temp_annual_range)\n) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](04-05_hypothesis_testing_exercises_files/figure-html/pollinators_ht_ans3.1-1.png){width=672}\n:::\n:::\n\n\nPerform a linear regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp_elev <- lm(temp_annual_range ~ elevation, data = site_metadata)\ntemp_elev_summ <- summary(temp_elev)\nprint(temp_elev_summ)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = temp_annual_range ~ elevation, data = site_metadata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.0420 -0.9127  0.2317  1.1983  2.2673 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 18.813762   0.297097  63.325   <2e-16 ***\nelevation   -0.002533   0.001376  -1.841   0.0697 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.519 on 74 degrees of freedom\nMultiple R-squared:  0.04378,\tAdjusted R-squared:  0.03086 \nF-statistic: 3.388 on 1 and 74 DF,  p-value: 0.06968\n```\n\n\n:::\n:::\n\n\n\n\nThere is no evidence of an association between elevation and annual temperature range at these sites (coefficient = -0.0025, $t$(74) = -1.84, $p$ = 0.0697, $R^2$ = 0.0438). The estimated relationship is negative, which is opposite to the direction predicted by our hypothesis.\n\n:::\n\n4. *Melanostoma scalare*, the chequered hoverfly, can be associated with sand dunes and undercliffs. Test the hypothesis that sites where *M. scalare* is present (you will need to create this column from the insect counts data frame and join it to the site metadata data frame) have a different mean distance from the coast (column `distance_to_coast`) from sites where it is absent. Does the direction of the observed difference agree with the biological prediction?\n\n::: {.callout-answer collapse=\"true\" #ex-pollinators_ht_ans4}\n\nAdd a column showing the presence or absence of *M. scalare* to the site metadata data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nms_present <- insect_counts |>\n  filter(species == \"Melanostoma scalare\") |>\n  mutate(detected = n_observed > 0) |>\n  left_join(site_metadata)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nJoining with `by = join_by(x1km_square)`\n```\n\n\n:::\n:::\n\n\nPlot the distribution of distance from the coast according to the presence or absence of M. scalare.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  ms_present,\n  aes(\n    x = detected,\n    y = distance_to_coast,\n    fill = detected\n  )\n) +\n  geom_boxplot() +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](04-05_hypothesis_testing_exercises_files/figure-html/pollinators_ht_ans4.2-1.png){width=672}\n:::\n:::\n\n\nPerform a t-test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nms_coast_test <- t.test(\n  distance_to_coast ~ detected,\n  data = ms_present,\n  var.equal = TRUE\n)\n\nprint(ms_coast_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  distance_to_coast by detected\nt = -3.0162, df = 74, p-value = 0.003507\nalternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0\n95 percent confidence interval:\n -32.108294  -6.562073\nsample estimates:\nmean in group FALSE  mean in group TRUE \n           25.84124            45.17642 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nms_t <- round(ms_coast_test$statistic, 2)\nms_df <- round(ms_coast_test$parameter)\nms_p <- round(ms_coast_test$p.value, 4)\n\nms_ci_lower <- round(ms_coast_test$conf.int[1], 2)\nms_ci_upper <- round(ms_coast_test$conf.int[2], 2)\n\nms_mean_absent <- round(ms_coast_test$estimate[1], 2)\nms_mean_present <- round(ms_coast_test$estimate[2], 2)\n```\n:::\n\n\nThere is evidence that mean distance from the coast differs between sites where *M. scalare* is present and sites where it is absent ($t$(74) = -3.02, $p$ = 0.0035, 95% CI [-32.11, -6.56] km). Mean distance from the coast was 45.18 km at sites where *M. scalare* was present, compared with 25.84 km where it was absent. The direction of the observed difference therefore does not agree with the biological prediction: *M. scalare* was found at sites that were, on average, further from the coast.\n\n:::\n\n5. Buff-tailed bumblebees, *Bombus terrestris*, are big. Test the hypothesis that total insect biomass (column `total_insect_biomass`) differs according to presence/absence of *B. terrestris* (you will need to create this column based on the insect counts data frame).\n\n::: {.callout-answer collapse=\"true\" #ex-pollinators_ht_ans5}\n\nAdd a column showing the presence or absence of *B. terrestris* to the site metadata data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbumblebees <- insect_counts |>\n  filter(species == \"Bombus terrestris\") |>\n  mutate(detected = n_observed > 0) |>\n  left_join(site_metadata)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nJoining with `by = join_by(x1km_square)`\n```\n\n\n:::\n:::\n\n\nPlot the total insect biomass according to the presence or absence of *B. terrestris*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  bumblebees,\n  aes(\n    x = detected,\n    y = total_insect_biomass,\n    fill = detected\n  )\n) +\n  geom_boxplot() +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](04-05_hypothesis_testing_exercises_files/figure-html/pollinators_ht_ans5.2-1.png){width=672}\n:::\n:::\n\n\nPerform a t-test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbig_bee_test <- t.test(\n  total_insect_biomass ~ detected,\n  data = bumblebees,\n  var.equal = TRUE\n)\n\nprint(big_bee_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  total_insect_biomass by detected\nt = -4.1495, df = 74, p-value = 8.801e-05\nalternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0\n95 percent confidence interval:\n -8203.273 -2880.850\nsample estimates:\nmean in group FALSE  mean in group TRUE \n           2311.674            7853.736 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbb_t <- round(big_bee_test$statistic, 2)\nbb_df <- round(big_bee_test$parameter)\nbb_p <- round(big_bee_test$p.value, 4)\n\nbb_ci_lower <- round(big_bee_test$conf.int[1], 2)\nbb_ci_upper <- round(big_bee_test$conf.int[2], 2)\n\nbb_mean_absent <- round(big_bee_test$estimate[1], 2)\nbb_mean_present <- round(big_bee_test$estimate[2], 2)\n```\n:::\n\n\nThere is evidence that the total insect biomass differs between sites where *B. terrestris* is present and sites where it is absent ($t$(74) = -4.15, $p$ = 10^{-4}, 95% CI [-8203.27, -2880.85] g). Mean total insect biomass was 7853.74 g at sites where *B. terrestris* was present, compared with 2311.67 g where it was absent. The direction of the observed difference therefore agrees with the biological prediction: *B. terrestris* was found at sites with, on average, higher total insect biomass.\n\n:::\n\n6. The heath bumblebee *Bombus jonellus* is named because it likes heathland, and heathland is often dominated by the plant heather, *Calluna vulgaris*. Test the hypothesis that the presence of *B. jonellus* (you will need to create this column based on the insect counts data frame) is associated with the presence of *C.vulgaris* (you will need to create this column based on the flower counts data frame). \n\n::: {.callout-answer collapse=\"true\" #ex-pollinators_ht_ans6}\n\nCount the groups for the plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheath_df <- insect_counts |>\n  filter(species == \"Bombus jonellus\") |>\n  mutate(bees_detected = n_observed > 0) |>\n  left_join(site_metadata)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nJoining with `by = join_by(x1km_square)`\n```\n\n\n:::\n\n```{.r .cell-code}\nheath_df <- flower_counts |>\n  filter(flower_species == \"Calluna vulgaris\") |>\n  mutate(heather_detected = n_observed_flowers > 0) |>\n  left_join(heath_df)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nJoining with `by = join_by(x1km_square)`\n```\n\n\n:::\n\n```{.r .cell-code}\nheath_counts <- heath_df |>\n  count(bees_detected, heather_detected)\n```\n:::\n\n\nPlot a bar chart of the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(heath_counts, aes(x = bees_detected, y = n, fill = heather_detected)) +\n  geom_col() +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](04-05_hypothesis_testing_exercises_files/figure-html/pollinators_ht_ans6.2-1.png){width=672}\n:::\n:::\n\n\nMake a contingency table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncont_table <- xtabs(\n  ~ bees_detected + heather_detected,\n  data = heath_df\n)\nprint(cont_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             heather_detected\nbees_detected FALSE TRUE\n        FALSE    50   10\n        TRUE      6   10\n```\n\n\n:::\n:::\n\n\nPerform a chi-squared test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncs <- chisq.test(cont_table)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in chisq.test(cont_table): Chi-squared approximation may be incorrect\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(cs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  cont_table\nX-squared = 11.423, df = 1, p-value = 0.0007254\n```\n\n\n:::\n:::\n\nThere is evidence of an association between the presence of the heath bumblebee *B. jonellus* and of heather *C. vulgaris* ($\\chi^2$(1) = 11.42, $p$ = 0.0007). Sites in which *B. jonellus* is present more frequently have *C. vulgaris* present. \n\nNote: there are technically not quite enough values here for a chi-squared test, so you may see a warning. For the purposes of this exercise, don't worry about it.\n\n:::\n\n7. Environmental conditions and the diversity of available floral resources may influence the types of insects supported at a site. Test the hypothesis that mean insect mass (column `mean_insect_mass`) is associated with flower biodiversity (column `n_unique_flowers`), annual mean temperature (column `annual_mean_temp`), or an interaction between these two variables.\n\n::: {.callout-answer collapse=\"true\" #ex-pollinators_ht_ans7}\n\nCentre the explanatory variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncentered_site_md <- site_metadata |>\n  mutate(\n    centered_annual_mean_temp = annual_mean_temp -\n      mean(annual_mean_temp),\n    centered_n_unique_flowers = n_unique_flowers -\n      mean(n_unique_flowers)\n  )\n```\n:::\n\n\nConvert the data to long format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiomass_biodiv_temp <- centered_site_md |>\n  select(\n    mean_insect_mass,\n    centered_annual_mean_temp,\n    centered_n_unique_flowers\n  ) |>\n  pivot_longer(\n    c(\n      centered_annual_mean_temp,\n      centered_n_unique_flowers\n    ),\n    names_to = \"variable\",\n    values_to = \"measurement\"\n  )\n```\n:::\n\n\nPlot the relationship between mean insect mass and each explanatory variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(biomass_biodiv_temp, aes(\n  x = measurement,\n  y = mean_insect_mass\n)) +\n  geom_point() +\n  geom_smooth(method = \"lm\") +\n  facet_wrap(~variable, scales = \"free_y\") +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](04-05_hypothesis_testing_exercises_files/figure-html/pollinators_ht_ans7.3-1.png){width=672}\n:::\n:::\n\n\nPerform a multiple linear regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_mass_biodiv_temp <- lm(mean_insect_mass ~ centered_annual_mean_temp * centered_n_unique_flowers, data = centered_site_md)\nlm_mass_biodiv_temp_summary <- summary(lm_mass_biodiv_temp)\nprint(lm_mass_biodiv_temp_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean_insect_mass ~ centered_annual_mean_temp * centered_n_unique_flowers, \n    data = centered_site_md)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-21.129  -5.901  -1.003   4.990  25.509 \n\nCoefficients:\n                                                    Estimate Std. Error t value\n(Intercept)                                         27.96091    1.36364  20.505\ncentered_annual_mean_temp                           -0.82033    1.21463  -0.675\ncentered_n_unique_flowers                           -0.26172    0.11786  -2.221\ncentered_annual_mean_temp:centered_n_unique_flowers  0.12281    0.09203   1.334\n                                                    Pr(>|t|)    \n(Intercept)                                           <2e-16 ***\ncentered_annual_mean_temp                             0.5016    \ncentered_n_unique_flowers                             0.0295 *  \ncentered_annual_mean_temp:centered_n_unique_flowers   0.1863    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 9.686 on 72 degrees of freedom\nMultiple R-squared:  0.1608,\tAdjusted R-squared:  0.1258 \nF-statistic: 4.599 on 3 and 72 DF,  p-value: 0.005313\n```\n\n\n:::\n:::\n\n\n\n\nThere is evidence that the overall model is associated with mean insect mass ($F$(3, 72) = 4.6, $p$ = 0.0053, $R^2$ = 0.161), with the model explaining 16.1% of the variation in mean insect mass.\n\nAt the average annual mean temperature, there is evidence of an association between flower diversity and mean insect mass (coefficient = -0.26, $p$ = 0.0295). The estimated coefficient is negative, indicating that sites with greater flower diversity tend to have lower mean insect mass.\n\nAt the average level of flower diversity, there is no evidence of an association between annual mean temperature and mean insect mass (coefficient = -0.82, $p$ = 0.5016).\n\nThere is also no evidence of an interaction between annual mean temperature and flower diversity (interaction coefficient = 0.12, $p$ = 0.1863). Therefore, there is no evidence that the relationship between flower diversity and mean insect mass changes with annual mean temperature.\n\n:::\n\n8.  Bramble plants, particularly the blackberry plant *Rubus fruticosus*, are considered to be one of the major food sources for bees (family Apidae). Test the hypothesis that mean insect mass (column `mean_insect_mass`) differs according to the presence/absence of *R. fruticosus* (you will need to create this column from the flower counts data frame) and the dominant pollinator family (column `dominant_family`) or the interaction between these two variables.\n\nNote: If you want to use facet_wrap to plot both `dominant_family` and presence/absence of *R. fruticosus* with the same ggplot() function, you will need to convert your presence/absence column from logical to character type using the function `as.character()` before converting your data frame to long format.\n\n::: {.callout-answer collapse=\"true\" #ex-pollinators_ht_ans8}\n\nAdd a column showing the presence or absence of *R. fruticosus* to the site metadata data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nblackberries <- flower_counts |>\n  filter(flower_species == \"Rubus fruticosus\") |>\n  mutate(detected = n_observed_flowers > 0) |>\n  left_join(site_metadata)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nJoining with `by = join_by(x1km_square)`\n```\n\n\n:::\n:::\n\n\nConvert the data to long format for plotting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nblackberries_long <- blackberries |>\n  select(\n    x1km_square,\n    mean_insect_mass,\n    detected,\n    dominant_family\n  ) |>\n  mutate(detected_char = as.character(detected)) |>\n  pivot_longer(\n    c(\n      detected_char,\n      dominant_family\n    ),\n    names_to = \"variable\",\n    values_to = \"value\"\n  )\n```\n:::\n\n\nPlot box plots for each explanatory variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  blackberries_long,\n  aes(x = value, y = mean_insect_mass, fill = value)\n) +\n  geom_boxplot() +\n  facet_wrap(~variable, scales = \"free_x\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](04-05_hypothesis_testing_exercises_files/figure-html/pollinators_ht_ans8.3-1.png){width=672}\n:::\n:::\n\n\nPerform a two-way ANOVA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_blackberries <- lm(mean_insect_mass ~ detected * dominant_family, data = blackberries)\nblackberry_anova <- anova(lm_blackberries)\nprint(blackberry_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: mean_insect_mass\n                         Df Sum Sq Mean Sq F value    Pr(>F)    \ndetected                  1  668.5  668.46 10.7853  0.001609 ** \ndominant_family           3 2800.3  933.44 15.0606 1.222e-07 ***\ndetected:dominant_family  2  304.6  152.32  2.4577  0.093099 .  \nResiduals                69 4276.5   61.98                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nThere is evidence that mean insect mass differs according to the presence or absence of *R. fruticosus* ($F$(1, 69) = 10.79, $p$ = 0.0016) and according to dominant insect family ($F$(3, 69) = 15.06, $p$ = 0.00000012). There is no evidence of an interaction between *R. fruticosus* presence and dominant insect family ($F$(2, 69) = 2.46, $p$ = 0.0931). Therefore, there is no evidence that the relationship between dominant insect family and mean insect mass differs depending on whether *R. fruticosus* is present.\n\n:::\n\n9. Members of the plant order *Rosales* are popular with hoverflies (members of the family Syrphidae). Test the hypothesis that having *Rosales* as the dominant flower order (you will need to create a new column based on the column `dominant_flower_order`) is associated with having members of the hoverfly family (Syrphidae) as the dominant insect family as opposed to members of the bee family Apidae (column `dominant_family`, you will need to filter to include only these families).\n\n::: {.callout-answer collapse=\"true\" #ex-pollinators_ht_ans9}\n\nAdd a column showing the presence or absence of *Rosales* as the dominant flower order to the site metadata data frame and filter to include only Apidae and Syrphidae.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrosales <- site_metadata |>\n  mutate(rosales_dom = dominant_flower_order == \"Rosales\") |>\n  filter(dominant_family %in% c(\"Apidae\", \"Syrphidae\"))\n```\n:::\n\n\nCount the groups for the plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrosales_counts <- rosales |>\n  count(rosales_dom, dominant_family)\n```\n:::\n\n\nPlot a bar chart of the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(rosales_counts, aes(x = rosales_dom, y = n, fill = dominant_family)) +\n  geom_col() +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](04-05_hypothesis_testing_exercises_files/figure-html/pollinators_ht_ans9.3-1.png){width=672}\n:::\n:::\n\nMake a contingency table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncont_table <- xtabs(\n  ~ rosales_dom + dominant_family,\n  data = rosales\n)\nprint(cont_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           dominant_family\nrosales_dom Apidae Syrphidae\n      FALSE     25        26\n      TRUE       9         7\n```\n\n\n:::\n:::\n\n\nPerform a chi-squared test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncs <- chisq.test(cont_table)\nprint(cs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  cont_table\nX-squared = 0.047585, df = 1, p-value = 0.8273\n```\n\n\n:::\n:::\n\nThere is no evidence of an association between dominant insect family (Apidae vs Syrphidae) and having Rosales as the dominant flower order ($\\chi^2$($\\chi^2$(1)) = 0.05, $p$ = 0.8273). \n:::\n\n10. Different habitat types may favour smaller or larger insects. Test the hypothesis that mean insect mass (`mean_insect_mass`) differs among habitat types (`broad_habitat`).\n\n::: {.callout-answer collapse=\"true\" #ex-pollinators_ht_ans10}\n\nPlot mean insect mass for each habitat type.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  site_metadata,\n  aes(x = broad_habitat, y = mean_insect_mass, fill = broad_habitat)\n) +\n  geom_boxplot() +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](04-05_hypothesis_testing_exercises_files/figure-html/pollinators_ht_ans10.1-1.png){width=672}\n:::\n:::\n\nPerform a one-way ANOVA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_hab <- lm(mean_insect_mass ~ broad_habitat, data = site_metadata)\nhab_anova <- anova(lm_hab)\nprint(hab_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: mean_insect_mass\n              Df Sum Sq Mean Sq F value Pr(>F)\nbroad_habitat  4  530.3  132.57  1.2518 0.2971\nResiduals     71 7519.7  105.91               \n```\n\n\n:::\n:::\n\n\n\n\nThere is no evidence that mean insect mass differs among broad habitat types ($F$(4, 71) = 1.25, $p$ = 0.2971).\n\n",
    "supporting": [
      "04-05_hypothesis_testing_exercises_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}